### DISCUSSION TITLE
Run custom command when claims removed

### DISCUSSION THREAD

**Discussion by TomLewis** [GriefPrevention/GriefPrevention#1780] [Ideas]
Allow us to run a custom command when a claims auto removed, so that we can send a message to discord, send a message to players in -game etc, so the plot can be looted/checked over to make sure its not false posative.

**Comment by bigpresh** [comment]
I think an addon could easily do this by listening for the `ClaimDeletedEvent` event?

**Reply by TomLewis** [reply]
Sounds good! If the event exists it should be easier than I assumed then! It's just such a pain to download the logs and filter them, when if I could just send it to a discord channel using Discord srv then bam, all staff can make sure it's removing claims properly, I already use that extension to name claims? It could be added to that?

**Reply by TomLewis** [reply]
I just thought of something, if it also can pul all claim information as placeholders then we could actually automate loads of thing's, imagine making a backup of the claim as a schematic using FAWE cli tools, it just needs to //pos1 and //pos2 //copy //schem save and bam. It's been backed up before it was wiped! This could also //regen too...

Ok this just expanded ha

**Reply by Jikoo** [reply]
The `ClaimExpirationEvent` is called. The regular delete may also be called, but will not have information identifying the cause.

**Comment by Jikoo** [comment]
[GPCE](https://github.com/GPAddons/GPClaimExpiration) already has this capacity.

**Reply by Jikoo** [reply]
> I just thought of something, if it also can pul all claim information as placeholders then we could actually automate loads of thing's, imagine making a backup of the claim as a schematic using FAWE cli tools, it just needs to //pos1 and //pos2 //copy //schem save and bam. It's been backed up before it was wiped! This could also //regen too...

I don't actually know what the exact commands are, but I'd guess it would look like this with GPCE:
```yaml
expiration:
  # Note: used 316 for Y max because claims don't always have a high point at world height, GP generally ignores it.
  claim.commands:
  - /pos1 $world $locX $locY $locZ
  - /pos2 $world $locXMax 316 $locZMax
  - /copy
  - /schem save $world_$locX_$locZ-$playerUUID-$claimId
  - /regen
```
/e: I know there's a `//copy` flag to ignore air, would probably recommend that so it auto-trims.

**Reply by TomLewis** [reply]
Oh brilliant! Does this GPCE take over the existing claim expiration settings?

**Reply by Jikoo** [reply]
GPCE doesn't pull defaults from GP, but if you want to mimic default GP settings it's not hard:
```yaml
expiration:
  days_per_area:
       # 100 or more blocks of area -> 60 day expiration
       # Equivalent of AllClaims.DaysInactive: 60 
      100: 60
      # 0 or more blocks (which becomes a range of 0-99 with our 100 block setting, aka default chest claims)
      # Equivalent of ChestClaimDays: 30
      0: 30
```
The only thing GPCE lacks is GP's "unused" evaluation, which is neat but also tends to evaluate incorrectly for sufficiently large claims.

To "disable" GP's expiration (it sadly cannot be disabled fully, I had several failed attempts to knock it out of the scheduler):
```yaml
GriefPrevention:
  Claims:
    Expiration:
      AllClaims:
        ExceptWhenOwnerHasTotalClaimBlocks: 0
        ExceptWhenOwnerHasBonusClaimBlocks: 0
  Advanced:
    ClaimExpirationCheckRate: 100000 # Over a day between checks

**Reply by TomLewis** [reply]
So it dousnt take over the existing claim removal task? its in addition? 
Can I use them together then if theres no way to disable the built in system?

The only documentation I can find on the default claim expiration settings is the docs I wrote on my website years ago and Im not sure they are even right.

If you could explain the settings:
```
    Expiration:
      ChestClaimDays: 3
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 90
        ExceptWhenOwnerHasTotalClaimBlocks: 1000
        ExceptWhenOwnerHasBonusClaimBlocks: 2500
      AutomaticNatureRestoration:
        SurvivalWorlds: false
```

The best docs I could find were my own, and there extreamly dated https://piratemc.com/topic/claim-expiration-discussion-vote/

**Reply by Jikoo** [reply]
Yes, you can't disable the inbuilt expiration fully. That's why I included a config for the relevant GP config sections to effectively disable GP's expiration even if the task itself cannot be stopped.

You can use them together, but claims expired by GP will not cause GPCE to do post-expiration commands - the goal is to eventually get GPCE to the point where expiration is actually removed from GP and anyone looking to expire claims is directed to GPCE. Major blocker on that right now is that GPCE does not have the capacity to do nature restoration on expiration, but as you pointed out, FAWE can bandaid that. Nature restoration is slated to eventually become a separate addon, so I haven't pushed ahead on that front. How it will get decoupled is beyond me - its "player block" system is pretty core to a lot of other features.

Re: GP setting explanation:
```yaml
GriefPrevention:
  Claims:
    Expiration:
      # Claims created by chest placement with no claims.
      # GP does not track additional data for this. Internally it is an area check:
      #  Minimum area is default 100, 10x10.
      #  Automatic chest claim is default radius 4, 9x9 = 81 area.
      # If a claim is under the minimum claim area, it "must" be an automatic chest claim.
      ChestClaimDays: 3
      # GP uses a scoring system for player blocks to determine claim content value.
      # Claims are considered "unused" if their block value is below a certain threshold.
      # This does not account for chest contents, source of blocks (like structures -
      # a claimed village is used even if the player has never built a thing) or claim size.
      UnusedClaimDays: 14
      AllClaims:
        # All claims will attempt to expire if the owner has not been online for the specified number of days.
        DaysInactive: 90
        # Players who have achieved X claim blocks from play are exempt from expiration.
        # Note: This includes initial claim blocks!
        ExceptWhenOwnerHasTotalClaimBlocks: 1000
        # Players who have achieved Y bonus claim blocks (/acb, /buyclaimblocks, etc.) are exempt from expiration.
        ExceptWhenOwnerHasBonusClaimBlocks: 2500
      AutomaticNatureRestoration:
        # Run GP's nature restoration over survival world claims?
        # This cannot be disabled in creative worlds, it's a core feature of the mode.
        SurvivalWorlds: false
  Advanced:
    # Seconds between claim expiration checks.
    # Note that the first run always runs 60 seconds after startup, this only affects the following runs.
    ClaimExpirationCheckRate: 60
```
