### DISCUSSION TITLE
Add claimblocks to a user via voting/item

### DISCUSSION THREAD

**Discussion by iGarretttt** [GriefPrevention/GriefPrevention#2020] [Q&A]
I've searched all over the wiki and this git to find anything that would be helpful to answering this question but i have not found it.

I'm wondering if there is some sort of command or feature that allows you to give players claimblocks that adds to their balance via voting or an item that runs a command, i've seen this on other servers. I know there's a "/scb" command but you are forced to use the <player> identifier which doesn't help if you are trying to use -p to give them to the player that uses the item.

I'm probably overthinking this but i cant figure it out, lol..

**Comment by bigpresh** [comment]
`AdjustBonusClaimBlocks` will do the job.

For e.g. one of my VoteRoulette voting rewards is:

```yaml
    500 Claim Blocks:
        chance: 4%
        commands:
        - /AdjustBonusClaimBlocks %player% +500
        message: "Expand your empire by 500 blocks thanks to your vote!"
```
