### DISCUSSION TITLE
Brazilian Portuguese Translation (pt-br)

### DISCUSSION THREAD

**Discussion by Fortuneeeee** [GriefPrevention/GriefPrevention#2272] [Translations]
I have painstakingly translated all of the messages.yml file into Portuguese, here it is.
```
# Use a YAML editor like NotepadPlusPlus to edit this file.  
# After editing, back up your changes before reloading the server in case you made a syntax error.  
# Use dollar signs ($) for formatting codes, which are documented here: http://minecraft.gamepedia.com/Formatting_codes

Messages:
  RespectingClaims:
    Text: Agora respeitando terrenos.
  IgnoringClaims:
    Text: Agora ignorando terrenos.
  SuccessfulAbandon:
    Text: Reivindicações abandonadas.  Sobraram {0} blocos de terreno.
    Notes: '0: remaining blocks'
  RestoreNatureActivate:
    Text: Se prepare para restaurar a natureza! Botão-Direito para restaurar a natureza,
      e use /BasicClaims para parar.
  RestoreNatureAggressiveActivate:
    Text: Modo agressivo ativo.  NÃO use isso abaixo do que quiser manter!  Botão-Direito
      para restaurar a natureza agressivamente, e /BasicClaims para parar.
  FillModeActive:
    Text: Modo preencher ativo com raio {0}.  Botão-Direito para preencher.
    Notes: '0: fill radius'
  TransferClaimPermission:
    Text: Este comando precisa de permissões para terrenos administrativos.
  TransferClaimMissing:
    Text: Não há um terreno aqui.  Fique dentro do terreno administrativo para transferir.
  TransferClaimAdminOnly:
    Text: Somente terrenos administrativos podem ser transferidos para um jogador.
  PlayerNotFound2:
    Text: Nenhum jogador com este nome logou recentemente.
  TransferTopLevel:
    Text: Somente terrenos de nível superior (sem subdivisões) podem ser transferidos.  Fique
      fora da subdivisão e tente novamente.
  TransferSuccess:
    Text: Reivindicação transferida.
  TrustListNoClaim:
    Text: Fique dentro do terreno que você está curioso sobre.
  ClearPermsOwnerOnly:
    Text: Somente o dono do terreno pode limpar todas as permissões.
  UntrustIndividualAllClaims:
    Text: O acesso de {0} foi revogado de todos os seus terrenos.  Para dar permissão
      para um só terreno, fique dentro dele.
    Notes: '0: untrusted player'
  UntrustEveryoneAllClaims:
    Text: Foram limpadas as permissões de TODOS os seus terrenos.  Para dar permissão
      para um só terreno, fique dentro dele.
  NoPermissionTrust:
    Text: Você não tem a permissão de {0} para mudar permissões.
    Notes: '0: claim owner''s name'
  ClearPermissionsOneClaim:
    Text: Foram limpadas as permissões deste terreno.  Para dar permissão para TODOS
      os seus terrenos, fique fora deles.
  UntrustIndividualSingleClaim:
    Text: O acesso de {0} foi removido para este terreno.  Para remover permissão
      pata TODOS os seus terrenos, fique fora deles.
    Notes: '0: untrusted player'
  OnlySellBlocks:
    Text: Blocos de terreno só podem ser vendidos, não comprados.
  BlockPurchaseCost:
    Text: Cada bloco custa {0}.  Você tem {1}.
    Notes: '0: cost of one block; 1: player''s account balance'
  ClaimBlockLimit:
    Text: Você alcançou o seu limite de blocos de terrenos.  Você não pode comprar
      mais.
  InsufficientFunds:
    Text: Falta dinheiro.  Você precisa de {0}, mas só tem {1}.
    Notes: '0: total cost; 1: player''s account balance'
  MaxBonusReached:
    Text: Você não pode comprar mais {0} blocos de terreno. O servidor possui um limite
      de {1} blocos bonus.
    Notes: '0: block count; 1: bonus claims limit'
  PurchaseConfirmation:
    Text: Foram removidos {0} da sua conta.  Você agora tem {1} blocos de terreno
      disponíveis.
    Notes: '0: total cost; 1: remaining blocks'
  OnlyPurchaseBlocks:
    Text: Blocos de terreno só podem ser comprados, não vendidos.
  BlockSaleValue:
    Text: Cada bloco de terreno vale {0}.  Você tem {1} disponíveis para venda.
    Notes: '0: block value; 1: available blocks'
  NotEnoughBlocksForSale:
    Text: Você não tem blocos de terreno suficientes para vender.
  BlockSaleConfirmation:
    Text: Foram depositados {0} na sua conta.  Você agora tem {1} blocos de terreno
      disponíveis.
    Notes: '0: amount deposited; 1: remaining blocks'
  AdminClaimsMode:
    Text: Modo de terreno administrativo ativado.  Qual terreno criado vai ser grátis
      e editável por outros administradores.
  BasicClaimsMode:
    Text: Modo de criação de terreno comum reativado.
  SubdivisionMode:
    Text: Modo de subdivisão.  Use sua pá dourada para criar subdivisões de seus terrenos
      existentes.  Use /basicclaims para sair.
  SubdivisionVideo2:
    Text: 'Clique para ajuda com subdivisões: {0}'
    Notes: 0:video URL
  DeleteClaimMissing:
    Text: Nenhuma reivindicação aqui.
  DeletionSubdivisionWarning:
    Text: Esse terreno possui subdivisões.  Se tiver certeza que quer exclui-la, use
      /DeleteClaim novamente.
  DeleteSuccess:
    Text: Reivindicação excluida.
  CantDeleteAdminClaim:
    Text: Você não possui permissões para deletar terrenos administrativos.
  DeleteAllSuccess:
    Text: Excluídos todos os terrenos de {0}.
    Notes: '0: owner''s name'
  NoDeletePermission:
    Text: Você não tem permissão para deletar terrenos.
  AllAdminDeleted:
    Text: Todos os terrenos administrativos foram deletados.
  AdjustBlocksSuccess:
    Text: 'Os blocos de terreno bonus de {0} foram ajustados por {1}.  Novo total
      de blocos de terreno bonus: {2}.'
    Notes: '0: player; 1: adjustment; 2: new total'
  NotTrappedHere:
    Text: Você pode construir.  Se salve.
  RescuePending:
    Text: Se você ficar parado(a) por 10 segundos você será teleportado(a) para fora.  Por
      favor espere.
  NonSiegeWorld:
    Text: Cerco está desativado aqui.
  AlreadySieging:
    Text: Você já está envolvido(a) em um cerco.
  NotSiegableThere:
    Text: '{0} não está protegido(a) ali.'
    Notes: '0: defending player'
  SiegeTooFarAway:
    Text: Você está longe demais para um cerco.
  NoSiegeYourself:
    Text: Você não pode impor um cerco em si mesmo(a), que bobagem.
  NoSiegeDefenseless:
    Text: Esse jogador está indefeso.  Vá brigar com alguém do seu tamanho.
  AlreadyUnderSiegePlayer:
    Text: '{0} já está sobre um cerco.  Se junte à festa!'
    Notes: '0: defending player'
  AlreadyUnderSiegeArea:
    Text: Essa área já está sobre um cerco.  Se junte à festa!
  NoSiegeAdminClaim:
    Text: Cerco está desativo nesta área.
  SiegeOnCooldown:
    Text: Você ainda está em recarga do cerco para este defensor ou terreno.  Procure
      outra vítima.
  SiegeAlert:
    Text: Você está sobre cerco!  Se deslogar agora, morrerá.  Você deve derrotar
      {0}, esperar ele desistir, or fugir.
    Notes: '0: attacker name'
  SiegeConfirmed:
    Text: O cerco começou!  Se você deslogar agora, morrerá.  Você deve derrotar {0},
      fazer ele fugir, ou desistir.
    Notes: '0: defender name'
  AbandonClaimMissing:
    Text: Fique dentro do terreno que quiser abandonar, ou considere /AbandonAllClaims.
  NotYourClaim:
    Text: Este não é o seu terreno.
  DeleteTopLevelClaim:
    Text: Para deletar uma subdivisão, fique dentro dela.  Ou use /AbandonTopLevelClaim
      para deleter este terreno e todas as subdivisões.
  AbandonSuccess:
    Text: Terreno abandonado.  Sobraram {0} blocos de terreno.
    Notes: '0: remaining claim blocks'
  ConfirmAbandonAllClaims:
    Text: Você tem certeza que quer abandonar TODOS os seus terrenos?  Por favor confirme
      com /AbandonAllClaims confirm
  CantGrantThatPermission:
    Text: Você não pode dar uma permissão que você não tem pra si próprio.
  GrantPermissionNoClaim:
    Text: Fique dentro do terreno para o qual você quer dar permissão.
  GrantPermissionConfirmation:
    Text: Concedida a {0} a seguinte permissão {1} {2}.
    Notes: '0: target player; 1: permission description; 2: scope (changed claims)'
  ManageUniversalPermissionsInstruction:
    Text: Para gerir permissões de TODOS os terrenos, fique fora deles.
  ManageOneClaimPermissionsInstruction:
    Text: Para gerir permissões de um terreno especifico, fique dentro dele.
  CollectivePublic:
    Text: o público
    Notes: as in 'granted the public permission to...'
  BuildPermission:
    Text: construir
  ContainersPermission:
    Text: acesso à contêineres e animais
  AccessPermission:
    Text: use botões e alavancas
  PermissionsPermission:
    Text: gerir permissões
  LocationCurrentClaim:
    Text: neste terreno
  LocationAllClaims:
    Text: em todos os seus terrenos
  PvPImmunityStart:
    Text: Você está protegido(a) de ataques de outros jogadores desde que seu inventário
      esteja vazio.
  SiegeNoDrop:
    Text: Você não pode dropar itens durante um cerco.
  DonateItemsInstruction:
    Text: Para doar o(s) item(ns) na sua mão, aperte Botão-Esquerdo no baú novamente.
  ChestFull:
    Text: O baú está cheio.
  DonationSuccess:
    Text: Os item(ns) foram transferidos ao baú!
  PlayerTooCloseForFire2:
    Text: Você não pode começar um incêndio tão perto de outro jogador.
  TooDeepToClaim:
    Text: Este baú não pode ser protegido porque está fundo demais.  Considere move-lo.
  ChestClaimConfirmation:
    Text: Este baú está protegido.
  AutomaticClaimNotification:
    Text: Este baú e blocos próximos estão protegidos contra vandalismo e roubo.
  AutomaticClaimOtherClaimTooClose:
    Text: Não podemos criar um terreno pro seu baú, tem um outro terreno mais próximo!
  UnprotectedChestWarning:
    Text: Este baú NÂO está protegido.  Considere usar uma pá dourada para expandir
      um terreno existente ou crie um novo.
  ThatPlayerPvPImmune:
    Text: Você não pode machucar jogadores indefesos.
  CantFightWhileImmune:
    Text: Você não pode lutar enquanto está protegido(a) contra PvP.
  NoDamageClaimedEntity:
    Text: Isto pertence a {0}.
    Notes: '0: owner name'
  ShovelBasicClaimMode:
    Text: Pá retornada ao modo de terrenos básico.
  RemainingBlocks:
    Text: Você pode reinvidicar até {0} mais blocos.
    Notes: '0: remaining blocks'
  CreativeBasicsVideo2:
    Text: 'Clique para receber ajuda sobre terrenos: {0}'
    Notes: '{0}: video URL'
  SurvivalBasicsVideo2:
    Text: 'Clique para receber ajuda sobre terrenos: {0}'
    Notes: '{0}: video URL'
  TrappedChatKeyword:
    Text: preso;stuck;trapped;armadilha
    Notes: When mentioned in chat, players get information about the /trapped command
      (multiple words can be separated with semi-colons)
  TrappedInstructions:
    Text: Preso no terreno de alguém?  Use o comando /trapped.
  PvPNoDrop:
    Text: Você não pode dropar itens durante PvP.
  SiegeNoTeleport:
    Text: Você não pode teleportar para fora de uma área de cerco.
  BesiegedNoTeleport:
    Text: Você não pode teleportar para dentro de uma área de cerco.
  SiegeNoContainers:
    Text: Você não pode acessar contêineres durante um cerco.
  PvPNoContainers:
    Text: Você não pode acessar contêineres durante PvP.
  PvPImmunityEnd:
    Text: Agora você pode lutar contra outros jogadores.
  NoBedPermission:
    Text: '{0} não te deu permissão para dormir aqui.'
    Notes: '0: claim owner'
  NoWildernessBuckets:
    Text: Você só pode usar baldes dentro de seus terrenos ou no subsolo.
  NoLavaNearOtherPlayer:
    Text: Você não pode por lava tão perto de {0}.
    Notes: '0: nearby player'
  TooFarAway:
    Text: Aí tá longe demais.
  BlockNotClaimed:
    Text: Ninguém reinvidicou este bloco.
  BlockClaimed:
    Text: Este bloco já reinvidicado por {0}.
    Notes: '0: claim owner'
  SiegeNoShovel:
    Text: Você não pode usar sua pé enquanto estiver envolvido(a) em um cerco.
  RestoreNaturePlayerInChunk:
    Text: Não é possível restaurar.  {0} está nesta chunk.
    Notes: '0: nearby player'
  NoCreateClaimPermission:
    Text: Você não tem permissão para criar terreno.
  ResizeNeedMoreBlocks:
    Text: Você não tem blocos o suficiente para este terreno.  Você precisa de {0}
      mais.
    Notes: '0: how many needed'
  NoCreativeUnClaim:
    Text: Você não pode abandonar este terreno.  Você só pode aumentar este terreno
      ou criar terrenos adicionais.
  ClaimResizeSuccess:
    Text: Terreno redimensionado.  {0} blocos de terreno restantes.
    Notes: '0: remaining blocks'
  ResizeFailOverlap:
    Text: Não é possível redimensionar o terreno porque ele sobreporia um terreno
      próximo.
  ResizeStart:
    Text: Redimensionando terreno.  Use a pá novamente no novo local para este canto.
  ResizeFailOverlapSubdivision:
    Text: Não é possível redimensionar a subdivisão porque ela sobreporia uma subdivisão
      próxima.  Considere /abandonclaim para deleta-la, ou use sua pá num canto para
      redimensiona-lo.
  SubdivisionStart:
    Text: Canto da subdivisão definido!  Use sua pá no local do canto oposto desta
      nova subdivisão.
  CreateSubdivisionOverlap:
    Text: Sua área selecionada sobrepõe uma outra subdivisão.
  SubdivisionSuccess:
    Text: Subdivisão criada!  Use /trust para compartilha-la com amigos.
  CreateClaimFailOverlap:
    Text: Você não pode criar o terreno porque ele sobreporia outro terreno.  Use
      /abandonclaim para deletar ele, ou use sua pá num canto para redimensiona-lo.
  CreateClaimFailOverlapOtherPlayer:
    Text: Você não pode criar um terreno aqui porque ele sobreporia o terreno de {0}.
    Notes: '0: other claim owner'
  ClaimsDisabledWorld:
    Text: Terrenos estão desativados neste mundo.
  ClaimStart:
    Text: Canto de terreno definido!  Use sua pá no canto oposto para criar um retângulo
      de terra.  Para cancelar, pare de segurar a pá.
  NewClaimTooNarrow:
    Text: Este terreno seria pequeno demais.  Qualquer terreno precisa ter {0} blocos
      de largura.
    Notes: '0: minimum claim width'
  CreateClaimInsufficientBlocks:
    Text: Você não possui blocos o suficiente para reinvidicar esta área.  Você precisa
      de {0} mais blocos.
    Notes: '0: additional blocks needed'
  AbandonClaimAdvertisement:
    Text: Para deletar outro terreno, use /AbandonClaim.
  CreateClaimFailOverlapShort:
    Text: Sua área selecionada sobrepõe um terreno existente.
  CreateClaimSuccess:
    Text: Terreno criado!  Use /trust para compartilha-lo com amigos.
  SiegeWinDoorsOpen:
    Text: Parabéns!  Botões e alavancas estão temporariamente desbloqueados.
  RescueAbortedMoved:
    Text: Você se moveu!  Resgate cancelado.
  SiegeDoorsLockedEjection:
    Text: Fim da pilhagem!  Você foi ejetado(a) do terreno.
  NoModifyDuringSiege:
    Text: Terrenos não podem ser modificados durante um cerco.
  OnlyOwnersModifyClaims:
    Text: Somente {0} pode modificar este terreno.
    Notes: '0: owner name'
  NoBuildUnderSiege:
    Text: Este terreno está sobre o cerco de {0}.  Ninguém pode construir aqui.
    Notes: '0: attacker name'
  NoBuildPvP:
    Text: Você não pode construir em terrenos durante PvP.
  NoBuildPermission:
    Text: Você não possui a permissão de {0} para construir aqui.
    Notes: '0: owner name'
  NonSiegeMaterial:
    Text: Esse material é duro demais pra quebrar.
  NoOwnerBuildUnderSiege:
    Text: Você não pode fazer mudanças durante o cerco.
  NoAccessPermission:
    Text: Você não possui a permissão de {0} para fazer isso.
    Notes: '0: owner name.  access permission controls buttons, levers, and beds'
  NoContainersSiege:
    Text: Este terreno está sobre cerco de {0}.  Ninguém pode acessar contêineres
      agora.
    Notes: '0: attacker name'
  NoContainersPermission:
    Text: Você não possui permissão de {0} para usar isso.
    Notes: '0: owner''s name.  containers also include crafting blocks'
  OwnerNameForAdminClaims:
    Text: um administrador
    Notes: as in 'You don't have an administrator's permission to build here.'
  ClaimTooSmallForEntities:
    Text: Este terreno não é grande o bastante para isto.  Tente aumentá-lo.
  TooManyEntitiesInClaim:
    Text: Este terrenos já possui entidades demais.  Tente aumentá-lo ou remover alguns
      animais, monstros, pinturas ou carrinhos de mina.
  YouHaveNoClaims:
    Text: Você não tem mais terrenos disponíveis.
  ConfirmFluidRemoval:
    Text: Abandonar este terreno removerá a lava dentro dele.  Se tiver certeza, use
      /AbandonClaim novamente.
  AutoBanNotify:
    Text: Banimento Automático {0}({1}).  Veja logs para ver detalhes.
  AdjustGroupBlocksSuccess:
    Text: 'Blocos de terreno bonus foram ajustados para jogadores com a permissão
      {0} por {1}.  Novo total: {2}.'
    Notes: '0: permission; 1: adjustment amount; 2: new total bonus'
  InvalidPermissionID:
    Text: Por favor especifique um nome de jogador, ou uma permissão em [colchetes].
  HowToClaimRegex:
    Text: (^|.*\W)como\W.*\W(reinvidicar|proteger|trancar)(\W.*|$)
    Notes: This is a Java Regular Expression.  Look it up before editing!  It's used
      to tell players about the demo video when they ask how to claim land.
  NoBuildOutsideClaims:
    Text: Você não pode construir aqui a menos que crie um terreno primeiro.
  PlayerOfflineTime:
    Text: '  Último login: {0} dias atrás.'
    Notes: '0: number of full days since last login'
  BuildingOutsideClaims:
    Text: Outros jogadores podem construir aqui também.  Considere criar um terreno
      para proteger seu trabalho duro!
  TrappedWontWorkHere:
    Text: Desculpe, não foi possível encontrar um lugar seguro para te teleportar.  Contate
      um admin.
  CommandBannedInPvP:
    Text: Você não pode usar este comando durante PvP.
  UnclaimCleanupWarning:
    Text: O terreno que você abandonou pode ser mudado por outros jogadores ou limpado
      por administradores.  Se você tem algo que quer manter, você tem que reinvidica-lo
  BuySellNotConfigured:
    Text: Desculpa, mas comprar e vender blocos de terreno tá desativado.
  NoTeleportPvPCombat:
    Text: Você não pode teleportar durante PvP.
  NoTNTDamageAboveSeaLevel:
    Text: 'Aviso: TNT não vai destruir blocos acima do nível do mar.'
  NoTNTDamageClaims:
    Text: 'Aviso: TNT não vai destruir blocos reinvidicados.'
  IgnoreClaimsAdvertisement:
    Text: Para ignorar, use /IgnoreClaims.
  NoPermissionForCommand:
    Text: Você não tem permissão para fazer isso!
  ClaimsListNoPermission:
    Text: Você não tem permissão para conseguir informação do terreno de outros jogadores.
  ExplosivesDisabled:
    Text: Este terreno está protegido contra explosões.  Use /ClaimExplosions novamente
      para desativar.
  ExplosivesEnabled:
    Text: Este terreno está vulnerável a explosões.  Use /ClaimExplosions novamente
      para reativar a proteção.
  ClaimExplosivesAdvertisement:
    Text: Para permitir que explosões destruam blocos no terreno use /ClaimExplosions.
  PlayerInPvPSafeZone:
    Text: Esse jogador está na área segura anti PvP.
  NoPistonsOutsideClaims:
    Text: 'Aviso: Pistões não moverão blocos fora de terrenos.'
  SoftMuted:
    Text: Soft-muted {0}.
    Notes: '0: The changed player''s name.'
  UnSoftMuted:
    Text: Un-soft-muted {0}.
    Notes: '0: The changed player''s name.'
  DropUnlockAdvertisement:
    Text: Outros jogadores não podem pegar seus itens dropados ao menos que use /UnlockDrops
      primeiro.
  PickupBlockedExplanation:
    Text: Você não pode pegar isto a menos que {0} use /UnlockDrops.
    Notes: '0: The item stack''s owner.'
  DropUnlockConfirmation:
    Text: Drops desbloqueados.  Outros jogadores podem pegar eles (até você morrer
      de novo).
  DropUnlockOthersConfirmation:
    Text: Os drops de {0} foram desbloqueados.
    Notes: '0: The owner of the unlocked drops.'
  AdvertiseACandACB:
    Text: Você pode usar /ACB para receber mais blocos de terreno, ou /AdminClaims
      para criar um terreno administrativo de graça.
  AdvertiseAdminClaims:
    Text: Você pode criar um terreno administrativo com /AdminClaims, que pode ser
      compartilhado com outros administradores.
  AdvertiseACB:
    Text: Você pode usar /ACB para receber mais blocos de terreno.
  NotYourPet:
    Text: Isso pertence à {0} até ele ser enviado pra você com /GivePet.
    Notes: '0: owner name'
  PetGiveawayConfirmation:
    Text: Pet transferido.
  PetTransferCancellation:
    Text: Transferimento de pet cancelado.
  ReadyToTransferPet:
    Text: Preparado para transferir!  Botão-Direito no pet se você gostaria de transferir
      ele ou cancele com /GivePet cancel.
  AvoidGriefClaimLand:
    Text: Previna griefing!  Se você criar um terreno, ele será imune à vandalismo.
  BecomeMayor:
    Text: Subdivida seu terreno e se torne prefeito!
  ClaimCreationFailedOverClaimCountLimit:
    Text: Você alcançou o seu limite de eventos.  Use /AbandonClaim para remover um
      antes de criar outro.
  CreateClaimFailOverlapRegion:
    Text: Você não pode reinvidicar tudo isso porque você não tem permissão para construir
      aqui.
  ResizeFailOverlapRegion:
    Text: Você não tem permissão para construir aqui, então você não pode reinvidicar
      aqui.
  ShowNearbyClaims:
    Text: Encontrados {0} terrenos.
    Notes: '0: Number of claims found.'
  NoChatUntilMove:
    Text: Desculpa, mas você tem que mover um pouco antes de falar no chat.  Nós temos
      muitos bots de spam por aqui.  :)
  SiegeImmune:
    Text: Esse jogador é imude ao /siege.
  SetClaimBlocksSuccess:
    Text: Blocos adquiridos atualizados.
  IgnoreConfirmation:
    Text: Você agora está ignorando mensagens deste jogador.
  NotIgnoringPlayer:
    Text: Você não está ignorando esse jogador.
  UnIgnoreConfirmation:
    Text: Você não está mais ignorando mensagens deste jogador.
  SeparateConfirmation:
    Text: Aqueles jogadores agora vão ignorar um ao outro no chat.
  UnSeparateConfirmation:
    Text: Aqueles jogadores agora não vão mais ignorar um ao outro no chat.
  NotIgnoringAnyone:
    Text: Você está ignorando ninguém.
  TrustListHeader:
    Text: 'Permissões explicitas aqui:'
    Notes: '0: The claim''s owner'
  Manage:
    Text: Gerir
  Build:
    Text: Construir
  Containers:
    Text: Contêineres
  Access:
    Text: Acesso
  HasSubclaimRestriction:
    Text: Este subdomínio não herda permissões do pai.
  StartBlockMath:
    Text: '{0} blocos por tempo de jogo + {1} bonus = {2} total.'
  ClaimsListHeader:
    Text: 'Terrenos:'
  ContinueBlockMath:
    Text: ' (-{0} blocos)'
  EndBlockMath:
    Text: ' = {0} blocos para gastar'
  NoClaimDuringPvP:
    Text: Você não pode reinvidicar terrenos durante PvP.
  UntrustAllOwnerOnly:
    Text: Somente o dono do terreno pode revogar as permissões de todos.
  ManagersDontUntrustManagers:
    Text: Somente o dono do terreno pode rebaixar um gerente.
  BookAuthor:
    Text: Fortune
  BookTitle:
    Text: Como Reinvidicar Terrenos
  BookIntro:
    Text: Reinvidique terreno e proteja sua terra!  Clique no link acima para aprender
      a reinvidicar terrenos em 3 minutos ou menos.  :)
  BookDisabledChestClaims:
    Text: '  Neste servidor, colocar um baú NÃO vai reinvidicar terra por você.'
  BookUsefulCommands:
    Text: 'Comandos Úteis:'
  BookLink:
    Text: 'Clique: {0}'
    Notes: '{0}: video URL'
  BookTools:
    Text: Nossas ferramentas de reinvidicação são {0} e {1}.
    Notes: '0: claim modification tool name; 1:claim information tool name'
  ResizeClaimTooNarrow:
    Text: O novo tamanho seria pequeno demais.  Terrenos precisam ter pelo menos {0}
      blocos de largura.
    Notes: '0: minimum claim width'
  ResizeClaimInsufficientArea:
    Text: O novo tamanho seria pequeno demais.  Terrenos precisam ter pelo menos {0}
      blocos no total.
    Notes: '0: minimum claim area'
  NoProfanity:
    Text: Por favor, olhe sua língua.
  PlayerNotIgnorable:
    Text: Você não pode ignorar este jogador.
  NoEnoughBlocksForChestClaim:
    Text: Porque você não tem nenhum bloco de terreno disponível, nenhum terreno automático
      foi criado por você.  Você pode usar /ClaimsList para monitorar seu total de
      blocos de terrenos.
  IsIgnoringYou:
    Text: Este jogador está te ignorando.
  MustHoldModificationToolForThat:
    Text: Você precisa segurar uma pá de ouro pra fazer isso.
  StandInClaimToResize:
    Text: Fique dentro do terreno que quiser redimensionar.
  ClaimsExtendToSky:
    Text: Terrenos sempre se extendem até a altura máxima de construção.
  ClaimsAutoExtendDownward:
    Text: Terrenos se extendem mais profundamente automaticamente quando você colocar
      blocos embaixo deles.
  MinimumRadius:
    Text: O raio mínimo é {0}.
    Notes: '0: minimum radius'
  RadiusRequiresGoldenShovel:
    Text: Você deve segurar uma pá dourada quando especificar o raio.
  ClaimTooSmallForActiveBlocks:
    Text: Este terreno não é grande o suficiente para suportar blocos ativos (funis,
      spawners, beacons...).  Faça um terreno maior primeiro.
  TooManyActiveBlocksInClaim:
    Text: Este terreno alcançou seu limite de blocos ativos (funis, spawners, beacons...).  Faça
      ele maior, ou remova outros blocos ativos primeiro.
  ConsoleOnlyCommand:
    Text: Esse comando só pode ser usado a partir do console.
  WorldNotFound:
    Text: Mundo não encontrado.
  AdjustBlocksAllSuccess:
    Text: O número de blocos de terreno bonus de todos os jogadores online foi ajustado
      por {0}.
    Notes: '0: adjustment amount'
  TooMuchIpOverlap:
    Text: Desculpa, mas existem jogadores demais logados com o seu endereço IP.
  StandInSubclaim:
    Text: Você precisa estar dentro de um subdomínio para restringi-lo.
  SubclaimRestricted:
    Text: As permissões deste subdomínio não vão mais herdar do domínio pai.
  SubclaimUnrestricted:
    Text: As permissões deste subdomínio agora vão herdar do domínio pai.
  NetherPortalTrapDetectionMessage:
    Text: Parece que você está preso(a) dentro de um portal! Iremos lhe resgatar em
      alguns segundos se esse for o caso!
    Notes: Sent to player on join, if they left while inside a nether portal.
```
