### DISCUSSION TITLE
German Translation (de)

### DISCUSSION THREAD

**Discussion by PaBox** [GriefPrevention/GriefPrevention#2449] [Translations]
I used ChatGPT and some manual labor to create the german version; I am just posting it as general information :)

```yaml
# Use a YAML editor like NotepadPlusPlus to edit this file.  
# After editing, back up your changes before reloading the server in case you made a syntax error.  
# Use dollar signs ($) for formatting codes, which are documented here: http://minecraft.gamepedia.com/Formatting_codes

Messages:
  RespectingClaims:
    Text: Claims werden jetzt respektiert.
  IgnoringClaims:
    Text: Claims werden jetzt ignoriert.
  SuccessfulAbandon:
    Text: Claims aufgegeben. Du hast nun {0} verfügbare Claim-Blöcke.
    Notes: '0: verbleibende Blöcke'
  RestoreNatureActivate:
    Text: Bereit, die Natur wiederherzustellen! Rechtsklick zum Wiederherstellen der Natur und verwende /basicclaims, um zu stoppen.
  RestoreNatureAggressiveActivate:
    Text: Aggressiver Modus aktiviert. VERWENDE DIESEN NICHT UNTER DINGEN, DIE DU BEHALTEN WILLST! Rechtsklick, um die Natur aggressiv wiederherzustellen. Verwende /basicclaims, um zu stoppen.
  FillModeActive:
    Text: Füllmodus mit Radius {0} aktiviert. Rechtsklick auf ein Gebiet, um es zu füllen.
    Notes: '0: Füllradius'
  TransferClaimPermission:
    Text: Dieser Befehl erfordert die administrative Claim-Berechtigung.
  TransferClaimMissing:
    Text: Hier gibt es keinen Claim. Stelle dich in den administrativen Claim, den du übertragen möchtest.
  TransferClaimAdminOnly:
    Text: Nur administrative Claims können an einen Spieler übertragen werden.
  PlayerNotFound2:
    Text: Kein Spieler hat sich kürzlich mit diesem Namen eingeloggt.
  TransferTopLevel:
    Text: Nur Haupt-Claims (keine Unter-Claims) können übertragen werden. Verlasse den Unter-Claim und versuche es erneut.
  TransferSuccess:
    Text: Claim übertragen.
  TrustListNoClaim:
    Text: Stelle dich in den Claim, über den du mehr erfahren möchtest.
  ClearPermsOwnerOnly:
    Text: Nur der Claim-Eigentümer kann alle Berechtigungen löschen.
  UntrustIndividualAllClaims:
    Text: Zugriff von {0} auf ALLE deine Claims widerrufen. Um Berechtigungen für einen einzelnen Claim zu setzen, stelle dich hinein.
    Notes: '0: nicht mehr vertrauenswürdiger Spieler'
  UntrustEveryoneAllClaims:
    Text: Alle Berechtigungen in ALLEN deinen Claims gelöscht. Um Berechtigungen für einen einzelnen Claim zu setzen, stelle dich hinein.
  NoPermissionTrust:
    Text: Du hast keine Berechtigung von {0}, um hier Berechtigungen zu verwalten.
    Notes: '0: Name des Claim-Eigentümers'
  ClearPermissionsOneClaim:
    Text: Berechtigungen in diesem Claim gelöscht. Um Berechtigungen für ALLE deine Claims zu setzen, stelle dich außerhalb.
  UntrustIndividualSingleClaim:
    Text: Zugriff von {0} auf diesen Claim widerrufen. Um Berechtigungen für ALLE deine Claims zu setzen, stelle dich außerhalb.
    Notes: '0: nicht mehr vertrauenswürdiger Spieler'
  OnlySellBlocks:
    Text: Claim-Blöcke können nur verkauft, nicht gekauft werden.
  BlockPurchaseCost:
    Text: Jeder Claim-Block kostet {0}. Dein Kontostand beträgt {1}.
    Notes: '0: Kosten eines Blocks; 1: Kontostand des Spielers'
  ClaimBlockLimit:
    Text: Du hast dein Limit für Claim-Blöcke erreicht. Du kannst keine weiteren kaufen.
  InsufficientFunds:
    Text: Du hast nicht genug Geld. Du brauchst {0}, hast aber nur {1}.
    Notes: '0: Gesamtkosten; 1: Kontostand des Spielers'
  MaxBonusReached:
    Text: Du kannst keine {0} weiteren Claim-Blöcke kaufen. Das Serverlimit liegt bei {1} Bonus-Claim-Blöcken.
    Notes: '0: Anzahl der Blöcke; 1: Bonuslimit'
  PurchaseConfirmation:
    Text: Es wurden {0} von deinem Konto abgebucht. Du hast nun {1} verfügbare Claim-Blöcke.
    Notes: '0: Gesamtkosten; 1: verbleibende Blöcke'
  OnlyPurchaseBlocks:
    Text: Claim-Blöcke können nur gekauft, nicht verkauft werden.
  BlockSaleValue:
    Text: Jeder Claim-Block ist {0} wert. Du hast {1} zum Verkauf verfügbar.
    Notes: '0: Wert eines Blocks; 1: verfügbare Blöcke'
  NotEnoughBlocksForSale:
    Text: Du hast nicht so viele Claim-Blöcke zum Verkauf verfügbar.
  BlockSaleConfirmation:
    Text: Es wurden {0} auf dein Konto eingezahlt. Du hast nun {1} verfügbare Claim-Blöcke.
    Notes: '0: Eingezahlter Betrag; 1: verbleibende Blöcke'
  AdminClaimsMode:
    Text: Administrativer Claim-Modus aktiv. Jeder erstellte Claim ist kostenlos und für andere Administratoren bearbeitbar.
  BasicClaimsMode:
    Text: Zurück zum Basis-Claim-Erstellungsmodus.
  SubdivisionMode:
    Text: Unterteilungsmodus. Verwende deine Schaufel, um Unterteilungen in deinen bestehenden Claims zu erstellen. Verwende /basicclaims, um zu beenden.
  SubdivisionVideo2:
    Text: 'Klicke für Unterteilungs-Hilfe: {0}'
    Notes: '0: Video-URL'
  DeleteClaimMissing:
    Text: Hier gibt es keinen Claim.
  DeletionSubdivisionWarning:
    Text: Dieser Claim enthält Unterteilungen. Falls du ihn wirklich löschen möchtest, verwende /deleteclaim erneut.
  DeleteSuccess:
    Text: Claim gelöscht.
  CantDeleteAdminClaim:
    Text: Du hast keine Berechtigung, administrative Claims zu löschen.
  DeleteAllSuccess:
    Text: Alle Claims von {0} gelöscht.
    Notes: '0: Name des Eigentümers'
  NoDeletePermission:
    Text: Du hast keine Berechtigung, Claims zu löschen.
  AllAdminDeleted:
    Text: Alle administrativen Claims gelöscht.
  AdjustBlocksSuccess:
    Text: 'Bonus-Claim-Blöcke von {0} um {1} angepasst. Neue Gesamtzahl: {2}.'
    Notes: '0: Spieler; 1: Anpassung; 2: neue Gesamtzahl'
  NotTrappedHere:
    Text: Du kannst hier bauen. Rette dich selbst.
  RescuePending:
    Text: Wenn du 10 Sekunden an Ort und Stelle bleibst, wirst du heraus teleportiert. Bitte warten.
  NonSiegeWorld:
    Text: Belagerungen sind hier deaktiviert.
  AlreadySieging:
    Text: Du bist bereits an einer Belagerung beteiligt.
  NotSiegableThere:
    Text: '{0} ist dort nicht geschützt.'
    Notes: '0: Verteidigender Spieler'
  SiegeTooFarAway:
    Text: Du bist zu weit entfernt, um eine Belagerung zu starten.
  NoSiegeYourself:
    Text: Du kannst dich nicht selbst belagern, sei nicht albern.
  NoSiegeDefenseless:
    Text: Dieser Spieler ist wehrlos. Such dir jemand anderen aus.
  AlreadyUnderSiegePlayer:
    Text: '{0} ist bereits unter Belagerung. Schließ dich der Party an!'
    Notes: '0: Verteidigender Spieler'
  AlreadyUnderSiegeArea:
    Text: Dieses Gebiet ist bereits unter Belagerung. Schließ dich der Party an!
  NoSiegeAdminClaim:
    Text: Belagerungen sind in diesem Bereich deaktiviert.
  SiegeOnCooldown:
    Text: Du bist noch in der Belagerungs-Abklingzeit für diesen Verteidiger oder Claim. Suche dir ein anderes Ziel.
  SiegeAlert:
    Text: Du wirst belagert! Wenn du dich jetzt ausloggst, wirst du sterben. Du musst {0} besiegen, warten, bis er aufgibt, oder entkommen.
    Notes: '0: Name des Angreifers'
  SiegeConfirmed:
    Text: Die Belagerung hat begonnen! Wenn du dich jetzt ausloggst, wirst du sterben. Du musst {0} besiegen, ihn vertreiben oder dich geschlagen geben und gehen.
    Notes: '0: Name des Verteidigers'
  AbandonClaimMissing:
    Text: Stelle dich in den Claim, den du löschen möchtest, oder verwende /abandonallclaims.
  NotYourClaim:
    Text: Dies ist nicht dein Claim.
  DeleteTopLevelClaim:
    Text: Um eine Unterteilung zu löschen, stelle dich hinein. Andernfalls verwende /abandontoplevelclaim, um diesen Claim und alle Unterteilungen zu löschen.
  AbandonSuccess:
    Text: Claim aufgegeben. Du hast nun {0} verfügbare Claim-Blöcke.
    Notes: '0: verbleibende Claim-Blöcke'
  ConfirmAbandonAllClaims:
    Text: Bist du sicher, dass du ALLE deine Claims aufgeben möchtest? Bestätige mit /abandonallclaims confirm
  CantGrantThatPermission:
    Text: Du kannst keine Berechtigung erteilen, die du selbst nicht hast.
  GrantPermissionNoClaim:
    Text: Stelle dich in den Claim, für den du eine Berechtigung erteilen möchtest.
  GrantPermissionConfirmation:
    Text: '{0} wurde die Berechtigung {1} für {2} erteilt.'
    Notes: '0: Zielspieler; 1: Berechtigungsbeschreibung; 2: Bereich (betroffene Claims)'
  ManageUniversalPermissionsInstruction:
    Text: Um Berechtigungen für ALLE deine Claims zu verwalten, stelle dich außerhalb von ihnen.
  ManageOneClaimPermissionsInstruction:
    Text: Um Berechtigungen für einen bestimmten Claim zu verwalten, stelle dich hinein.
  CollectivePublic:
    Text: der Öffentlichkeit
    Notes: wie in "hat der Öffentlichkeit die Berechtigung erteilt, ..."
  BuildPermission:
    Text: bauen
  ContainersPermission:
    Text: auf Container und Tiere zugreifen
  AccessPermission:
    Text: Knöpfe und Hebel benutzen
  PermissionsPermission:
    Text: Berechtigungen verwalten
  LocationCurrentClaim:
    Text: in diesem Claim
  LocationAllClaims:
    Text: in allen deinen Claims
  PvPImmunityStart:
    Text: Du bist vor Angriffen anderer Spieler geschützt, solange dein Inventar leer ist.
  SiegeNoDrop:
    Text: Du kannst keine Gegenstände weggeben, während du in einer Belagerung bist.
  DonateItemsInstruction:
    Text: Um die Gegenstände in deiner Hand zu verschenken, klicke erneut mit der linken Maustaste auf die Kiste.
  ChestFull:
    Text: Diese Kiste ist voll.
  DonationSuccess:
    Text: Gegenstand/Gegenstände in die Kiste übertragen!
  PlayerTooCloseForFire2:
    Text: Du kannst kein Feuer so nah an einem anderen Spieler entfachen.
  TooDeepToClaim:
    Text: Diese Kiste kann nicht geschützt werden, da sie zu tief unter der Erde ist. Erwäge, sie zu versetzen.
  ChestClaimConfirmation:
    Text: Diese Kiste ist geschützt.
  AutomaticClaimNotification:
    Text: Diese Kiste und nahegelegene Blöcke sind vor Zerstörung und Diebstahl geschützt.
  AutomaticClaimOtherClaimTooClose:
    Text: Es kann kein Claim für deine Kiste erstellt werden, da ein anderer Claim zu nahe ist!
  UnprotectedChestWarning:
    Text: Diese Kiste ist NICHT geschützt. Erwäge, eine goldene Schaufel zu benutzen, um einen bestehenden Claim zu erweitern oder einen neuen zu erstellen.
  ThatPlayerPvPImmune:
    Text: Du kannst wehrlose Spieler nicht verletzen.
  CantFightWhileImmune:
    Text: Du kannst niemanden angreifen, während du vor PvP geschützt bist.
  NoDamageClaimedEntity:
    Text: Das gehört {0}.
    Notes: '0: Name des Eigentümers'
  ShovelBasicClaimMode:
    Text: Schaufel zurück in den Basis-Claim-Modus versetzt.
  RemainingBlocks:
    Text: Du kannst noch bis zu {0} Blöcke claimen.
    Notes: '0: verbleibende Blöcke'
  CreativeBasicsVideo2:
    Text: 'Klicke für Claim-Hilfe: {0}'
    Notes: '{0}: Video-URL'
  SurvivalBasicsVideo2:
    Text: 'Klicke für Claim-Hilfe: {0}'
    Notes: '{0}: Video-URL'
  TrappedChatKeyword:
    Text: gefangen;feststecken;stecke
    Notes: Wenn diese Begriffe im Chat erwähnt werden, erhalten Spieler Informationen zum /trapped-Befehl (mehrere Wörter können durch Semikolons getrennt werden)
  TrappedInstructions:
    Text: Bist du in jemandes Claim gefangen? Versuche den Befehl /trapped.
  PvPNoDrop:
    Text: Du kannst während eines PvP-Kampfes keine Gegenstände ablegen.
  SiegeNoTeleport:
    Text: Du kannst dich nicht aus einem belagerten Gebiet teleportieren.
  BesiegedNoTeleport:
    Text: Du kannst dich nicht in ein belagertes Gebiet teleportieren.
  SiegeNoContainers:
    Text: Du kannst während einer Belagerung keine Container öffnen.
  PvPNoContainers:
    Text: Du kannst während eines PvP-Kampfes keine Container öffnen.
  PvPImmunityEnd:
    Text: Du kannst jetzt gegen andere Spieler kämpfen.
  NoBedPermission:
    Text: '{0} hat dir keine Erlaubnis gegeben, hier zu schlafen.'
    Notes: '0: Claim-Eigentümer'
  NoWildernessBuckets:
    Text: Du kannst Eimer nur innerhalb deiner Claims oder unterirdisch entleeren.
  NoLavaNearOtherPlayer:
    Text: Du kannst keine Lava so nah an {0} platzieren.
    Notes: '0: Name des nahen Spielers'
  TooFarAway:
    Text: Das ist zu weit entfernt.
  BlockNotClaimed:
    Text: Niemand hat diesen Block geclaimt.
  BlockClaimed:
    Text: Dieser Block wurde von {0} geclaimt.
    Notes: '0: Claim-Eigentümer'
  SiegeNoShovel:
    Text: Du kannst deine Schaufel während einer Belagerung nicht benutzen.
  RestoreNaturePlayerInChunk:
    Text: Wiederherstellung nicht möglich. {0} befindet sich in diesem Chunk.
    Notes: '0: Name des nahen Spielers'
  NoCreateClaimPermission:
    Text: Du hast keine Berechtigung, Claims zu erstellen.
  ResizeNeedMoreBlocks:
    Text: Du hast nicht genug Blöcke für diese Größe. Du brauchst {0} mehr.
    Notes: '0: Anzahl der zusätzlich benötigten Blöcke'
  NoCreativeUnClaim:
    Text: Du kannst diesen Bereich nicht unclaimen. Du kannst diesen Claim nur vergrößern oder neue Claims erstellen.
  ClaimResizeSuccess:
    Text: Claim angepasst. {0} verfügbare Claim-Blöcke verbleiben.
    Notes: '0: verbleibende Blöcke'
  ResizeFailOverlap:
    Text: Kann hier nicht vergrößern, da es sich mit einem anderen Claim überschneiden würde.
  ResizeStart:
    Text: Claim wird vergrößert. Benutze deine Schaufel erneut an der neuen Ecke.
  ResizeFailOverlapSubdivision:
    Text: Du kannst hier keine Unterteilung erstellen, da sie sich mit einer anderen überschneiden würde. Erwäge /abandonclaim, um sie zu löschen, oder benutze deine Schaufel an einer Ecke, um sie anzupassen.
  SubdivisionStart:
    Text: Ecke der Unterteilung gesetzt! Benutze deine Schaufel an der gegenüberliegenden Ecke dieser neuen Unterteilung.
  CreateSubdivisionOverlap:
    Text: Der ausgewählte Bereich überschneidet eine andere Unterteilung.
  SubdivisionSuccess:
    Text: Unterteilung erstellt! Verwende /trust, um sie mit Freunden zu teilen.
  CreateClaimFailOverlap:
    Text: Du kannst hier keinen Claim erstellen, da er sich mit deinem anderen Claim überschneiden würde. Verwende /abandonclaim, um ihn zu löschen, oder benutze deine Schaufel an einer Ecke, um ihn anzupassen.
  CreateClaimFailOverlapOtherPlayer:
    Text: Du kannst hier keinen Claim erstellen, da er sich mit dem Claim von {0} überschneiden würde.
    Notes: '0: Eigentümer des anderen Claims'
  ClaimsDisabledWorld:
    Text: Claims sind in dieser Welt deaktiviert.
  ClaimStart:
    Text: Claim-Ecke gesetzt! Benutze die Schaufel erneut an der gegenüberliegenden Ecke, um ein Rechteck zu claimen. Zum Abbrechen, lege deine Schaufel weg.
  NewClaimTooNarrow:
    Text: Dieser Claim wäre zu klein. Jeder Claim muss mindestens {0} Blöcke breit sein.
    Notes: '0: Mindestbreite des Claims'
  CreateClaimInsufficientBlocks:
    Text: Du hast nicht genug Blöcke, um dieses gesamte Gebiet zu claimen. Du brauchst {0} mehr Blöcke.
    Notes: '0: zusätzlich benötigte Blöcke'
  AbandonClaimAdvertisement:
    Text: Um einen anderen Claim zu löschen und Blöcke freizugeben, verwende /abandonclaim.
  CreateClaimFailOverlapShort:
    Text: Der ausgewählte Bereich überschneidet einen bestehenden Claim.
  CreateClaimSuccess:
    Text: Claim erstellt! Verwende /trust, um ihn mit Freunden zu teilen.
  SiegeWinDoorsOpen:
    Text: Glückwunsch! Knöpfe und Hebel sind vorübergehend entsperrt.
  RescueAbortedMoved:
    Text: Du hast dich bewegt! Rettung abgebrochen.
  SiegeDoorsLockedEjection:
    Text: Die Plünderungszeit ist vorbei! Du wurdest aus dem Claim entfernt.
  NoModifyDuringSiege:
    Text: Claims können während einer Belagerung nicht verändert werden.
  OnlyOwnersModifyClaims:
    Text: Nur {0} kann diesen Claim bearbeiten.
    Notes: '0: Name des Eigentümers'
  NoBuildUnderSiege:
    Text: Dieser Claim wird von {0} belagert. Niemand kann hier bauen.
    Notes: '0: Name des Angreifers'
  NoBuildPvP:
    Text: Du kannst während eines PvP-Kampfes nicht in Claims bauen.
  NoBuildPermission:
    Text: Du hast keine Erlaubnis von {0}, hier zu bauen.
    Notes: '0: Name des Eigentümers'
  NonSiegeMaterial:
    Text: Dieses Material ist zu widerstandsfähig, um es zu zerstören.
  NoOwnerBuildUnderSiege:
    Text: Du kannst während einer Belagerung keine Änderungen vornehmen.
  NoAccessPermission:
    Text: Du hast keine Erlaubnis von {0}, das zu benutzen.
    Notes: '0: Name des Eigentümers. Zugriffsbeschränkung für Knöpfe, Hebel und Betten'
  NoContainersSiege:
    Text: Dieser Claim wird von {0} belagert. Niemand kann momentan Container öffnen.
    Notes: '0: Name des Angreifers'
  NoContainersPermission:
    Text: Du hast keine Erlaubnis von {0}, das zu benutzen.
    Notes: '0: Name des Eigentümers. Container schließen auch Werkbänke mit ein'
  OwnerNameForAdminClaims:
    Text: ein Administrator
    Notes: wie in "Du hast keine Erlaubnis eines Administrators, hier zu bauen."
  ClaimTooSmallForEntities:
    Text: Dieser Claim ist nicht groß genug dafür. Versuche ihn zu vergrößern.
  TooManyEntitiesInClaim:
    Text: Dieser Claim hat bereits zu viele Entitäten. Vergrößere den Claim oder entferne einige Tiere, Monster, Gemälde oder Loren.
  YouHaveNoClaims:
    Text: Du hast keine Claims.
  ConfirmFluidRemoval:
    Text: Wenn du diesen Claim aufgibst, wird Lava innerhalb des Claims entfernt. Falls du dir sicher bist, verwende /abandonclaim erneut.
  AutoBanNotify:
    Text: 'Automatisch gebannt: {0}({1}). Siehe Protokolle für Details.'
  AdjustGroupBlocksSuccess:
    Text: 'Bonus-Claim-Blöcke für Spieler mit der Berechtigung {0} um {1} angepasst. Neue Gesamtzahl: {2}.'
    Notes: '0: Berechtigung; 1: Anpassungsmenge; 2: neue Gesamtzahl an Bonus-Blöcken'
  InvalidPermissionID:
    Text: Bitte gib einen Spielernamen oder eine Berechtigung in [eckigen Klammern] an.
  HowToClaimRegex:
    Text: (^|.*\W)wie\W.*\W(claim|protect|lock)(\W.*|$)
    Notes: Dies ist ein Java-Regulärer Ausdruck. Prüfe ihn vor der Bearbeitung! Er wird verwendet, um Spielern das Demo-Video zu zeigen, wenn sie fragen, wie man Land claimt.
  NoBuildOutsideClaims:
    Text: Du kannst hier nicht bauen, es sei denn, du claimst zuerst ein Grundstück.
  PlayerOfflineTime:
    Text: '  Letzte Anmeldung: vor {0} Tagen.'
    Notes: '0: Anzahl der vollen Tage seit der letzten Anmeldung'
  BuildingOutsideClaims:
    Text: Andere Spieler können hier ebenfalls bauen. Erwäge, einen Claim zu erstellen, um deine Bauwerke zu schützen!
  TrappedWontWorkHere:
    Text: Es konnte kein sicherer Teleportationsort für dich gefunden werden. Kontaktiere einen Admin.
  CommandBannedInPvP:
    Text: Du kannst diesen Befehl während eines PvP-Kampfes nicht verwenden.
  UnclaimCleanupWarning:
    Text: Das Land, das du unclaimed hast, könnte von anderen Spielern verändert oder von Administratoren bereinigt werden. Falls du dort etwas gebaut hast, das du behalten möchtest, solltest du es erneut claimen.
  BuySellNotConfigured:
    Text: Der Kauf und Verkauf von Claim-Blöcken ist deaktiviert.
  NoTeleportPvPCombat:
    Text: Du kannst dich nicht teleportieren, während du gegen einen anderen Spieler kämpfst.
  NoTNTDamageAboveSeaLevel:
    Text: 'Warnung: TNT wird keine Blöcke über dem Meeresspiegel zerstören.'
  NoTNTDamageClaims:
    Text: 'Warnung: TNT wird keine geclaimten Blöcke zerstören.'
  IgnoreClaimsAdvertisement:
    Text: Um dies zu umgehen, verwende /ignoreclaims.
  NoPermissionForCommand:
    Text: Du hast keine Berechtigung, dies zu tun.
  ClaimsListNoPermission:
    Text: Du hast keine Berechtigung, Informationen über die Claims eines anderen Spielers zu erhalten.
  ExplosivesDisabled:
    Text: Dieser Claim ist nun vor Explosionen geschützt. Verwende /claimexplosions erneut, um dies zu deaktivieren.
  ExplosivesEnabled:
    Text: Dieser Claim ist nun anfällig für Explosionen. Verwende /claimexplosions erneut, um den Schutz wieder zu aktivieren.
  ClaimExplosivesAdvertisement:
    Text: Um zuzulassen, dass Explosionen Blöcke in diesem Claim zerstören, verwende /claimexplosions.
  PlayerInPvPSafeZone:
    Text: Dieser Spieler befindet sich in einer PvP-Sicherheitszone.
  NoPistonsOutsideClaims:
    Text: 'Warnung: Kolben bewegen keine Blöcke außerhalb von Claims.'
  SoftMuted:
    Text: '{0} wurde stummgeschaltet.'
    Notes: '0: Name des Spielers'
  UnSoftMuted:
    Text: '{0} wurde wieder entsperrt.'
    Notes: '0: Name des Spielers'
  DropUnlockAdvertisement:
    Text: Andere Spieler können deine fallengelassenen Gegenstände nicht aufheben, es sei denn, du verwendest /unlockdrops.
  PickupBlockedExplanation:
    Text: Du kannst dies nicht aufheben, es sei denn, {0} verwendet /unlockdrops.
    Notes: '0: Eigentümer des Gegenstands'
  DropUnlockConfirmation:
    Text: Deine fallengelassenen Gegenstände sind nun freigegeben. Andere Spieler können sie nun aufheben (bis du erneut stirbst).
  DropUnlockOthersConfirmation:
    Text: "{0}'s fallengelassene Gegenstände wurden freigegeben."
    Notes: '0: Eigentümer der freigegebenen Gegenstände'
  AdvertiseACandACB:
    Text: Du kannst /acb verwenden, um dir mehr Claim-Blöcke zu geben, oder /adminclaims, um einen kostenlosen administrativen Claim zu erstellen.
  AdvertiseAdminClaims:
    Text: Du kannst stattdessen mit /adminclaims einen administrativen Claim erstellen, den du mit anderen Administratoren teilen kannst.
  AdvertiseACB:
    Text: Du kannst /acb verwenden, um dir mehr Claim-Blöcke zu geben.
  NotYourPet:
    Text: Dieses Tier gehört {0}, bis es dir mit /givepet gegeben wird.
    Notes: '0: Name des Eigentümers'
  PetGiveawayConfirmation:
    Text: Haustier übertragen.
  PetTransferCancellation:
    Text: Haustier-Übertragung abgebrochen.
  ReadyToTransferPet:
    Text: Bereit zur Übertragung! Rechtsklicke das Haustier, das du verschenken möchtest, oder breche mit /givepet cancel ab.
  AvoidGriefClaimLand:
    Text: Schütze dich vor Griefing! Wenn du dein Land claimst, bist du gegen Griefing geschützt.
  BecomeMayor:
    Text: Teile deinen Claim in Unterabschnitte und werde Bürgermeister!
  ClaimCreationFailedOverClaimCountLimit:
    Text: Du hast dein Limit an Claims erreicht. Verwende /abandonclaim, um einen zu entfernen, bevor du einen neuen erstellst.
  CreateClaimFailOverlapRegion:
    Text: Du kannst dieses Gebiet nicht claimen, da du hier nicht bauen darfst.
  ResizeFailOverlapRegion:
    Text: Du hast keine Berechtigung, hier zu bauen, daher kannst du diesen Bereich nicht claimen.
  ShowNearbyClaims:
    Text: '{0} Claims gefunden.'
    Notes: '0: Anzahl der gefundenen Claims'
  NoChatUntilMove:
    Text: Entschuldigung, aber du musst dich erst ein wenig bewegen, bevor du chatten kannst. Wir haben hier viele Spam-Bots. :)
  SiegeImmune:
    Text: Dieser Spieler ist immun gegen /siege.
  SetClaimBlocksSuccess:
    Text: Zugewiesene Claim-Blöcke aktualisiert.
  IgnoreConfirmation:
    Text: Du ignorierst nun Chat-Nachrichten von diesem Spieler.
  NotIgnoringPlayer:
    Text: Du ignorierst diesen Spieler nicht.
  UnIgnoreConfirmation:
    Text: Du ignorierst nun keine Chat-Nachrichten dieses Spielers mehr.
  SeparateConfirmation:
    Text: Diese Spieler werden sich nun gegenseitig im Chat ignorieren.
  UnSeparateConfirmation:
    Text: Diese Spieler werden sich nicht länger gegenseitig im Chat ignorieren.
  NotIgnoringAnyone:
    Text: Du ignorierst derzeit niemanden.
  TrustListHeader:
    Text: 'Explizite Berechtigungen hier:'
    Notes: '0: Eigentümer des Claims'
  Manage:
    Text: Verwalten
  Build:
    Text: Bauen
  Containers:
    Text: Container
  Access:
    Text: Zugriff
  HasSubclaimRestriction:
    Text: Dieser Unterclaim erbt keine Berechtigungen vom übergeordneten Claim.
  StartBlockMath:
    Text: '{0} Blöcke durch Spielzeit + {1} Bonus = {2} insgesamt.'
  ClaimsListHeader:
    Text: 'Claims:'
  ContinueBlockMath:
    Text: ' (-{0} Blöcke)'
  EndBlockMath:
    Text: ' = {0} Blöcke verbleibend'
  NoClaimDuringPvP:
    Text: Du kannst während eines PvP-Kampfes keine Claims erstellen.
  UntrustAllOwnerOnly:
    Text: Nur der Claim-Eigentümer kann alle Berechtigungen entfernen.
  ManagersDontUntrustManagers:
    Text: Nur der Claim-Eigentümer kann einen Manager degradieren.
  BookAuthor:
    Text: PaBox
  BookTitle:
    Text: Wie man Land claimt
  BookIntro:
    Text: Claim Land, um deine Sachen zu schützen! Klicke auf den obigen Link, um in weniger als 3 Minuten alles über Claims zu lernen. :)
  BookDisabledChestClaims:
    Text: '  Auf diesem Server wird durch das Platzieren einer Truhe KEIN automatischer Claim erstellt.'
  BookUsefulCommands:
    Text: 'Nützliche Befehle:'
  BookLink:
    Text: 'Klicke hier: {0}'
    Notes: '{0}: Video-URL'
  BookTools:
    Text: Unsere Claim-Werkzeuge sind {0} und {1}.
    Notes: '0: Werkzeug zur Claim-Modifikation; 1: Werkzeug zur Claim-Information'
  ResizeClaimTooNarrow:
    Text: Diese neue Größe wäre zu klein. Claims müssen mindestens {0} Blöcke breit sein.
    Notes: '0: Mindestbreite des Claims'
  ResizeClaimInsufficientArea:
    Text: Dieser Claim wäre zu klein. Jeder Claim muss mindestens {0} Claim-Blöcke umfassen.
    Notes: '0: Mindestfläche des Claims'
  NoProfanity:
    Text: Bitte achte auf deine Wortwahl.
  PlayerNotIgnorable:
    Text: Du kannst diesen Spieler nicht ignorieren.
  NoEnoughBlocksForChestClaim:
    Text: Da du keine verfügbaren Claim-Blöcke hast, wurde kein automatischer Claim für dich erstellt. Verwende /claimslist, um deine verfügbaren Claim-Blöcke zu überprüfen.
  IsIgnoringYou:
    Text: Dieser Spieler ignoriert dich.
  MustHoldModificationToolForThat:
    Text: Du musst eine goldene Schaufel halten, um das zu tun.
  StandInClaimToResize:
    Text: Stelle dich in den Claim, den du vergrößern möchtest.
  ClaimsExtendToSky:
    Text: Claims erstrecken sich immer bis zur maximalen Bauhöhe.
  ClaimsAutoExtendDownward:
    Text: Claims erweitern sich automatisch tiefer in den Boden, wenn du darunter Blöcke platzierst.
  MinimumRadius:
    Text: Der minimale Radius beträgt {0}.
    Notes: '0: Mindest-Radius'
  RadiusRequiresGoldenShovel:
    Text: Du musst eine goldene Schaufel halten, wenn du einen Radius angibst.
  ClaimTooSmallForActiveBlocks:
    Text: Dieser Claim ist nicht groß genug, um aktive Blöcke (Trichter, Spawner, Leuchtfeuer ...) zu unterstützen. Vergrößere ihn zuerst.
  TooManyActiveBlocksInClaim:
    Text: Dieser Claim hat das Limit für aktive Blöcke (Trichter, Spawner, Leuchtfeuer ...) erreicht. Vergrößere ihn oder entferne einige aktive Blöcke.
  ConsoleOnlyCommand:
    Text: Dieser Befehl kann nur über die Server-Konsole ausgeführt werden.
  WorldNotFound:
    Text: Welt nicht gefunden.
  AdjustBlocksAllSuccess:
    Text: Bonus-Claim-Blöcke für alle online Spieler um {0} angepasst.
    Notes: '0: Anpassungsbetrag'
  TooMuchIpOverlap:
    Text: Entschuldigung, es sind zu viele Spieler mit deiner IP-Adresse eingeloggt.
  StandInSubclaim:
    Text: Du musst dich in einem Unterclaim befinden, um ihn zu beschränken.
  SubclaimRestricted:
    Text: Die Berechtigungen dieses Unterclaims erben nicht mehr die des übergeordneten Claims.
  SubclaimUnrestricted:
    Text: Die Berechtigungen dieses Unterclaims erben nun wieder die des übergeordneten Claims.
  NetherPortalTrapDetectionMessage:
    Text: Es scheint, als wärst du in einem Nether-Portal gefangen. Falls das so ist, retten wir dich in wenigen Sekunden!
    Notes: Wird einem Spieler beim Betreten gesendet, falls er das Spiel verlassen hat, während er sich in einem Nether-Portal befand.
```
