### DISCUSSION TITLE
Ukranian translation (uk_UA)

### DISCUSSION THREAD

**Discussion by Ezdrael** [GriefPrevention/GriefPrevention#2464] [Translations]
```
# Use a YAML editor like NotepadPlusPlus to edit this file.  
# After editing, back up your changes before reloading the server in case you made a syntax error.  
# Use dollar signs ($) for formatting codes, which are documented here: http://minecraft.gamepedia.com/Formatting_codes

Messages:
  RespectingClaims:
    Text: Тепер враховуються ділянки.
  IgnoringClaims:
    Text: Тепер ігноруються ділянки.
  SuccessfulAbandon:
    Text: Ділянки скасовано. Тепер у вас є {0} доступних блоків.
    Notes: '0: кількість блоків, що залишилася'
  RestoreNatureActivate:
    Text: Готово до відновлення природи! Клацніть правою кнопкою миші, щоб відновити
      природу, та використовуйте /basicclaims щоб зупинити.
  RestoreNatureAggressiveActivate:
    Text: Агресивний режим активовано. НЕ використовуйте його під чимось, що хочете
      зберегти! Клацніть правою кнопкою миші, щоб агресивно відновити природу, та
      використовуйте /basicclaims, щоб зупинити.
  FillModeActive:
    Text: Режим заповнення активовано з радіусом {0}. Клацніть правою кнопкою миші
      на область, щоб заповнити.
    Notes: '0: радіус заповнення'
  TransferClaimPermission:
    Text: Ця команда вимагає дозволу на адміністративні ділянки.
  TransferClaimMissing:
    Text: Тут немає ділянки. Станьте в адміністративній ділянці, яку хочете передати.
  TransferClaimAdminOnly:
    Text: Лише адміністративні ділянки можуть бути передані гравцю.
  PlayerNotFound2:
    Text: Гравець з таким ім'ям нещодавно не заходив у гру.
  TransferTopLevel:
    Text: Лише ділянки верхнього рівня (не підрозділи) можуть бути передані. Станьте
      за межами підрозділу та спробуйте ще раз.
  TransferSuccess:
    Text: Ділянку передано.
  TrustListNoClaim:
    Text: Станьте всередині ділянки, яка вас цікавить.
  ClearPermsOwnerOnly:
    Text: Лише власник ділянки може видалити всі дозволи.
  UntrustIndividualAllClaims:
    Text: Скасовано доступ гравця {0} до ВСІХ ваших ділянок. Щоб налаштувати дозволи
      для однієї ділянки, станьте всередині неї.
    Notes: '0: гравець, доступ якого скасовано'
  UntrustEveryoneAllClaims:
    Text: Очищено дозволи у ВСІХ ваших ділянках. Щоб налаштувати дозволи для однієї
      ділянки, станьте всередині неї.
  NoPermissionTrust:
    Text: У вас немає дозволу гравця {0} керувати дозволами тут.
    Notes: '0: ім`я власника ділянки'
  ClearPermissionsOneClaim:
    Text: Очищено дозволи в цій ділянці. Щоб налаштувати дозволи для ВСІХ ваших ділянок,
      станьте за їх межами.
  UntrustIndividualSingleClaim:
    Text: Скасовано доступ гравця {0} до цієї ділянки. Щоб налаштувати дозволи для
      ВСІХ ваших ділянок, станьте за їх межами.
    Notes: '0: гравець, доступ якого скасовано'
  OnlySellBlocks:
    Text: Блоки для ділянок можна лише продавати, а не купувати.
  BlockPurchaseCost:
    Text: Кожен блок для ділянки коштує {0}. Ваш баланс становить {1}.
    Notes: '0: вартість одного блока; 1: баланс рахунку гравця'
  ClaimBlockLimit:
    Text: Ви досягли ліміту блоків для ділянок. Ви не можете придбати більше.
  InsufficientFunds:
    Text: У вас недостатньо грошей. Вам потрібно {0}, а у вас лише {1}.
    Notes: '0: загальна вартість; 1: баланс рахунку гравця'
  MaxBonusReached:
    Text: Неможливо придбати ще {0} блоків для ділянок. Сервер має ліміт у {1} бонусних
      блоків для ділянок.
    Notes: '0: кількість блоків; 1: ліміт бонусних ділянок'
  PurchaseConfirmation:
    Text: З вашого рахунку знято {0}. Тепер у вас є {1} доступних блоків для ділянок.
    Notes: '0: загальна вартість; 1: кількість блоків, що залишилася'
  OnlyPurchaseBlocks:
    Text: Блоки для ділянок можна лише купувати, а не продавати.
  BlockSaleValue:
    Text: Кожен блок для ділянки коштує {0}. У вас є {1} доступних для продажу.
    Notes: '0: вартість блока; 1: доступні блоки'
  NotEnoughBlocksForSale:
    Text: У вас немає стільки доступних для продажу блоків для ділянок.
  BlockSaleConfirmation:
    Text: На ваш рахунок зараховано {0}. Тепер у вас є {1} доступних блоків для ділянок.
    Notes: '0: зарахована сума; 1: кількість блоків, що залишилася'
  AdminClaimsMode:
    Text: Режим адміністративних приватів активовано. Будь-які створені привати будуть
      безкоштовними та доступними для редагування іншими адміністраторами.
  BasicClaimsMode:
    Text: Повернуто до основного режиму створення приватів.
  SubdivisionMode:
    Text: Режим підрозділів. Використовуйте свою лопату, щоб створювати підрозділи
      у ваших існуючих приватах. Використовуйте /basicclaims, щоб вийти.
  SubdivisionVideo2:
    Text: 'Натисніть для допомоги з підрозділами: {0}.'
    Notes: '0: URL відео'
  DeleteClaimMissing:
    Text: Тут немає привату.
  DeletionSubdivisionWarning:
    Text: Цей приват включає підрозділи. Якщо ви впевнені, що хочете його видалити,
      використайте /deleteclaim ще раз.
  DeleteSuccess:
    Text: Приват видалено.
  CantDeleteAdminClaim:
    Text: У вас немає дозволу видаляти адміністративні ділянки.
  DeleteAllSuccess:
    Text: Видалено всі ділянки гравця {0}.
    Notes: '0: ім`я власника'
  NoDeletePermission:
    Text: У вас немає дозволу видаляти ділянки.
  AllAdminDeleted:
    Text: Видалено всі адміністративні ділянки.
  AdjustBlocksSuccess:
    Text: 'Бонусні блоки ділянок гравця {0} змінено на {1}. Нова загальна кількість
      бонусних блоків: {2}.'
    Notes: '0: гравець; 1: зміна; 2: нова загальна кількість'
  NotTrappedHere:
    Text: Ви можете тут будувати. Врятуйте себе самі.
  RescuePending:
    Text: Якщо ви залишитеся на місці протягом 10 секунд, вас телепортує. Будь ласка,
      зачекайте.
  NonSiegeWorld:
    Text: Облоги тут вимкнено.
  AlreadySieging:
    Text: Ви вже берете участь в облозі.
  NotSiegableThere:
    Text: '{0} там не захищений.'
    Notes: '0: гравець, що захищається'
  SiegeTooFarAway:
    Text: Ви занадто далеко, щоб почати облогу.
  NoSiegeYourself:
    Text: Ви не можете обложити себе, не будьте смішним.
  NoSiegeDefenseless:
    Text: Цей гравець беззахисний. Знайдіть собі іншу жертву.
  AlreadyUnderSiegePlayer:
    Text: '{0} вже перебуває в облозі. Приєднуйтесь до вечірки!'
    Notes: '0: гравець, що захищається'
  AlreadyUnderSiegeArea:
    Text: Ця територія вже перебуває в облозі. Приєднуйтесь до вечірки!
  NoSiegeAdminClaim:
    Text: Облоги в цій зоні вимкнено.
  SiegeOnCooldown:
    Text: Ви ще перебуваєте на таймері облоги для цього захисника або ділянки. Знайдіть
      іншу жертву.
  SiegeAlert:
    Text: Вас обложили! Якщо ви зараз вийдете з гри, ви помрете. Ви повинні перемогти
      {0}, дочекатися, поки він здасться, або втекти.
    Notes: '0: ім`я нападника'
  SiegeConfirmed:
    Text: Облогу розпочато! Якщо ви зараз вийдете з гри, ви помрете. Ви повинні перемогти
      {0}, прогнати його або визнати поразку та піти.
    Notes: '0: ім`я захисника'
  AbandonClaimMissing:
    Text: Станьте в ділянці, яку хочете видалити, або розгляньте команду /abandonallclaims.
  NotYourClaim:
    Text: Це не ваша ділянка.
  DeleteTopLevelClaim:
    Text: Щоб видалити підрозділ, станьте всередині нього. В іншому випадку використовуйте
      /abandontoplevelclaim щоб видалити цю ділянку та всі підрозділи.
  AbandonSuccess:
    Text: Ділянку скасовано. Тепер у вас є {0} доступних блоків для ділянок.
    Notes: '0: кількість блоків для ділянок, що залишилася'
  ConfirmAbandonAllClaims:
    Text: Ви впевнені, що хочете скасувати ВСІ свої ділянки? Будь ласка, підтвердіть
      за допомогою /abandonallclaims confirm
  CantGrantThatPermission:
    Text: Ви не можете надати дозвіл, якого не маєте самі.
  GrantPermissionNoClaim:
    Text: Станьте всередині ділянки, де ви хочете надати дозвіл.
  GrantPermissionConfirmation:
    Text: Надано гравцю {0} дозвіл на {1} {2}.
    Notes: '0: цільовий гравець; 1: опис дозволу; 2: область дії (змінені ділянки)'
  ManageUniversalPermissionsInstruction:
    Text: Щоб керувати дозволами для ВСІХ своїх ділянок, станьте за їх межами.
  ManageOneClaimPermissionsInstruction:
    Text: Щоб керувати дозволами для конкретної ділянки, станьте всередині неї.
  CollectivePublic:
    Text: публічний
    Notes: як у фразі "надано публічний дозвіл на..."
  BuildPermission:
    Text: будувати
  ContainersPermission:
    Text: доступ до контейнерів і тварин
  AccessPermission:
    Text: використовувати кнопки та важелі
  PermissionsPermission:
    Text: керувати дозволами
  LocationCurrentClaim:
    Text: у цій ділянці
  LocationAllClaims:
    Text: у всіх ваших ділянках
  PvPImmunityStart:
    Text: Вас захищено від нападу інших гравців, доки ваш інвентар порожній.
  SiegeNoDrop:
    Text: Ви не можете віддавати предмети під час облоги.
  DonateItemsInstruction:
    Text: Щоб віддати предмет(и) у вашій руці, знову натисніть лівою кнопкою миші
      на скриню.
  ChestFull:
    Text: Ця скриня повна.
  DonationSuccess:
    Text: Предмет(и) передано до скрині!
  PlayerTooCloseForFire2:
    Text: Ви не можете розпалити вогонь так близько до іншого гравця.
  TooDeepToClaim:
    Text: Цю скриню неможливо захистити, оскільки вона занадто глибоко під землею.
      Радимо перемістити її.
  ChestClaimConfirmation:
    Text: Цю скриню захищено.
  AutomaticClaimNotification:
    Text: Цю скриню та сусідні блоки захищено від руйнування та крадіжки.
  AutomaticClaimOtherClaimTooClose:
    Text: Неможливо створити приват для вашої скрині, оскільки занадто близько знаходиться
      інший приват!
  UnprotectedChestWarning:
    Text: Ця скриня НЕ захищена. Радимо використовувати золоту лопату, щоб розширити
      існуючу ділянку або створити нову.
  ThatPlayerPvPImmune:
    Text: Ви не можете завдати шкоди беззахисним гравцям.
  CantFightWhileImmune:
    Text: Ви не можете битися з кимось, коли вас захищено від PvP.
  NoDamageClaimedEntity:
    Text: Це належить гравцю {0}.
    Notes: '0: ім`я власника'
  ShovelBasicClaimMode:
    Text: Лопату повернуто до основного режиму ділянок.
  RemainingBlocks:
    Text: Ви можете зайняти ще до {0} блоків.
    Notes: '0: кількість блоків, що залишилася'
  CreativeBasicsVideo2:
    Text: 'Натисніть для допомоги з приватними ділянками: {0}'
    Notes: '{0}: URL відео'
  SurvivalBasicsVideo2:
    Text: 'Натисніть для допомоги з приватними ділянками: {0}'
    Notes: '{0}: URL відео'
  TrappedChatKeyword:
    Text: trapped;stuck
    Notes: Коли згадується в чаті, гравці отримують інформацію про команду /trapped
      (кілька слів можна розділяти крапкою з комою)
  TrappedInstructions:
    Text: Ви застрягли на чиїйсь приватній території? Спробуйте команду /trapped.
  PvPNoDrop:
    Text: Ви не можете викидати предмети під час PvP-бою.
  SiegeNoTeleport:
    Text: Ви не можете телепортуватися з обложеної території.
  BesiegedNoTeleport:
    Text: Ви не можете телепортуватися на обложену територію.
  SiegeNoContainers:
    Text: Ви не можете отримувати доступ до контейнерів під час облоги.
  PvPNoContainers:
    Text: Ви не можете отримувати доступ до контейнерів під час PvP-бою.
  PvPImmunityEnd:
    Text: Тепер ви можете битися з іншими гравцями.
  NoBedPermission:
    Text: '{0} не дав вам дозволу спати тут.'
    Notes: '0: власник ділянки'
  NoWildernessBuckets:
    Text: Ви можете виливати відра лише у своїх ділянках або під землею.
  NoLavaNearOtherPlayer:
    Text: Ви не можете ставити лаву так близько до гравця {0}.
    Notes: '0: гравець поблизу'
  TooFarAway:
    Text: Це занадто далеко.
  BlockNotClaimed:
    Text: Цей блок ніким не зайнятий.
  BlockClaimed:
    Text: Цей блок зайнятий гравцем {0}.
    Notes: '0: власник ділянки'
  SiegeNoShovel:
    Text: Ви не можете використовувати інструмент-лопату під час облоги.
  RestoreNaturePlayerInChunk:
    Text: Не вдалося відновити. У цьому чанку знаходиться гравець {0}.
    Notes: '0: гравець поблизу'
  NoCreateClaimPermission:
    Text: У вас немає дозволу займати землю.
  ResizeNeedMoreBlocks:
    Text: У вас недостатньо блоків для такого розміру. Вам потрібно ще {0}.
    Notes: '0: скільки ще потрібно'
  NoCreativeUnClaim:
    Text: Ви не можете скасувати цю ділянку. Ви можете лише збільшити її або створити
      додаткові ділянки.
  ClaimResizeSuccess:
    Text: Розмір ділянки змінено. Залишилося {0} доступних блоків для ділянок.
    Notes: '0: кількість блоків, що залишилася'
  ResizeFailOverlap:
    Text: Неможливо змінити розмір тут, оскільки це призведе до перекриття іншої сусідньої
      ділянки.
  ResizeStart:
    Text: Зміна розміру ділянки. Використовуйте свою лопату знову в новому місці для
      цього кута.
  ResizeFailOverlapSubdivision:
    Text: Ви не можете створити тут підрозділ, оскільки це призведе до перекриття
      іншого підрозділу. Радимо використовувати /abandonclaim, щоб видалити його,
      або скористатися лопатою в кутку, щоб змінити його розмір.
  SubdivisionStart:
    Text: Кут підрозділу встановлено! Використовуйте свою лопату в місці розташування
      протилежного кута цього нового підрозділу.
  CreateSubdivisionOverlap:
    Text: Вибрана вами область перетинається з іншим підрозділом.
  SubdivisionSuccess:
    Text: Підрозділ створено! Використовуйте /trust, щоб поділитися ним з друзями.
  CreateClaimFailOverlap:
    Text: Ви не можете створити тут ділянку, оскільки вона перетинатиметься з вашою
      іншою ділянкою. Використовуйте /abandonclaim, щоб видалити її, або скористайтеся
      лопатою в кутку, щоб змінити її розмір.
  CreateClaimFailOverlapOtherPlayer:
    Text: Ви не можете створити тут ділянку, оскільки вона перетинатиметься з ділянкою
      гравця {0}.
    Notes: '0: власник іншої ділянки'
  ClaimsDisabledWorld:
    Text: Приватні ділянки вимкнено в цьому світі.
  ClaimStart:
    Text: Кут ділянки встановлено! Використовуйте лопату ще раз на протилежному куті,
      щоб зайняти прямокутну ділянку землі. Щоб скасувати, приберіть лопату.
  NewClaimTooNarrow:
    Text: Ця ділянка буде занадто малою. Будь-яка ділянка повинна бути не менше {0}
      блоків завширшки.
    Notes: '0: мінімальна ширина ділянки'
  CreateClaimInsufficientBlocks:
    Text: У вас недостатньо блоків, щоб зайняти всю цю територію. Вам потрібно ще
      {0} блоків.
    Notes: '0: додаткова кількість необхідних блоків'
  AbandonClaimAdvertisement:
    Text: Щоб видалити іншу ділянку та звільнити блоки, використайте /abandonclaim.
  CreateClaimFailOverlapShort:
    Text: Вибрана вами область перетинається з існуючою ділянкою.
  CreateClaimSuccess:
    Text: Приват створено! Використовуйте /trust, щоб поділитися ним з друзями.
  SiegeWinDoorsOpen:
    Text: Вітаємо! Кнопки та важелі тимчасово розблоковані.
  RescueAbortedMoved:
    Text: Ви рушили! Рятування скасовано.
  SiegeDoorsLockedEjection:
    Text: Час для пограбування вийшов! Вас вигнано з ділянки.
  NoModifyDuringSiege:
    Text: Ділянки не можна змінювати під час облоги.
  OnlyOwnersModifyClaims:
    Text: Лише {0} може змінювати цю ділянку.
    Notes: '0: ім`я власника'
  NoBuildUnderSiege:
    Text: Ця ділянка перебуває в облозі гравця {0}. Ніхто не може тут будувати.
    Notes: '0: ім`я нападника'
  NoBuildPvP:
    Text: Ви не можете будувати в приватних ділянках під час PvP-бою.
  NoBuildPermission:
    Text: У вас немає дозволу гравця {0} будувати тут.
    Notes: '0: ім`я власника'
  NonSiegeMaterial:
    Text: Цей матеріал занадто міцний, щоб його зламати.
  NoOwnerBuildUnderSiege:
    Text: Ви не можете вносити зміни під час облоги.
  NoAccessPermission:
    Text: У вас немає дозволу гравця {0} використовувати це.
    Notes: '0: ім`я власника. Дозвіл на доступ контролює кнопки, важелі та ліжка'
  NoContainersSiege:
    Text: Ця ділянка перебуває в облозі гравця {0}. Ніхто не може отримати доступ
      до контейнерів зараз.
    Notes: '0: ім`я нападника'
  NoContainersPermission:
    Text: У вас немає дозволу гравця {0} використовувати це.
    Notes: '0: ім`я власника. Контейнери також включають крафтові блоки'
  OwnerNameForAdminClaims:
    Text: адміністратора
    Notes: як у фразі "У вас немає дозволу адміністратора будувати тут."
  ClaimTooSmallForEntities:
    Text: Ця ділянка недостатньо велика для цього. Спробуйте її збільшити.
  TooManyEntitiesInClaim:
    Text: На цій ділянці вже занадто багато сутностей. Спробуйте збільшити ділянку
      або видалити деяких тварин, монстрів, картини чи вагонетки.
  YouHaveNoClaims:
    Text: У вас немає приватних ділянок.
  ConfirmFluidRemoval:
    Text: Скасування цієї ділянки призведе до видалення лави всередині неї. Якщо ви
      впевнені, використайте /abandonclaim ще раз.
  AutoBanNotify:
    Text: Автоматично забанено {0}({1}). Деталі дивіться в журналах.
  AdjustGroupBlocksSuccess:
    Text: 'Бонусні блоки ділянок для гравців з дозволом {0} змінено на {1}. Нова загальна
      кількість: {2}.'
    Notes: '0: дозвіл; 1: сума зміни; 2: нова загальна кількість бонусних блоків'
  InvalidPermissionID:
    Text: Будь ласка, вкажіть ім'я гравця або дозвіл у [квадратних дужках].
  HowToClaimRegex:
    Text: (^|.*\W)how\W.*\W(claim|protect|lock)(\W.*|$)
    Notes: Це регулярний вираз Java. Ознайомтеся з ним перед редагуванням! Він використовується
      щоб повідомити гравцям про демонстраційне відео, коли вони запитують, як зайняти
      землю.
  NoBuildOutsideClaims:
    Text: Ви не можете тут будувати, якщо спочатку не займете землю.
  PlayerOfflineTime:
    Text: '  Останній вхід: {0} днів тому.'
    Notes: '0: кількість повних днів з моменту останнього входу'
  BuildingOutsideClaims:
    Text: Інші гравці також можуть тут будувати. Радимо створити приватну ділянку,
      щоб захистити свою роботу!
  TrappedWontWorkHere:
    Text: Вибачте, не вдалося знайти безпечне місце для телепортації. Зверніться до
      адміністратора.
  CommandBannedInPvP:
    Text: Ви не можете використовувати цю команду під час PvP-бою.
  UnclaimCleanupWarning:
    Text: Земля, яку ви скасували, може бути змінена іншими гравцями або очищена адміністраторами.
      Якщо ви щось там побудували, що хочете зберегти, вам слід повернути цю ділянку.
  BuySellNotConfigured:
    Text: Вибачте, купівля та продаж блоків для ділянок вимкнено.
  NoTeleportPvPCombat:
    Text: Ви не можете телепортуватися під час бою з іншим гравцем.
  NoTNTDamageAboveSeaLevel:
    Text: 'Увага: TNT не руйнуватиме блоки вище рівня моря.'
  NoTNTDamageClaims:
    Text: 'Увага: TNT не руйнуватиме приватні блоки.'
  IgnoreClaimsAdvertisement:
    Text: Щоб обійти обмеження, використайте /ignoreclaims.
  NoPermissionForCommand:
    Text: У вас немає дозволу на це.
  ClaimsListNoPermission:
    Text: У вас немає дозволу на отримання інформації про ділянки іншого гравця.
  ExplosivesDisabled:
    Text: Ця ділянка тепер захищена від вибухів. Використайте /claimexplosions знову,
      щоб вимкнути захист.
  ExplosivesEnabled:
    Text: Ця ділянка тепер вразлива до вибухів. Використайте /claimexplosions знову,
      щоб увімкнути захист.
  ClaimExplosivesAdvertisement:
    Text: Щоб дозволити вибухам руйнувати блоки на цій ділянці, використайте /claimexplosions.
  PlayerInPvPSafeZone:
    Text: Цей гравець знаходиться в безпечній зоні PvP.
  NoPistonsOutsideClaims:
    Text: 'Увага: Поршні не переміщатимуть блоки за межами приватних ділянок.'
  SoftMuted:
    Text: Заглушено {0}.
    Notes: '0: Ім`я гравця, чий статус змінено.'
  UnSoftMuted:
    Text: Розблоковано звук для {0}.
    Notes: '0: Ім`я гравця, чий статус змінено.'
  DropUnlockAdvertisement:
    Text: Інші гравці не можуть піднімати ваші викинуті предмети, якщо ви спочатку
      не використаєте /unlockdrops.
  PickupBlockedExplanation:
    Text: Ви не можете це підняти, доки {0} не використає /unlockdrops.
    Notes: '0: Власник стопки предметів.'
  DropUnlockConfirmation:
    Text: Розблоковано ваші викинуті предмети. Інші гравці тепер можуть їх піднімати
      (до вашої наступної смерті).
  DropUnlockOthersConfirmation:
    Text: Розблоковано викинуті предмети гравця {0}.
    Notes: '0: Власник розблокованих викинутих предметів.'
  AdvertiseACandACB:
    Text: Ви можете використовувати /acb, щоб отримати більше блоків для ділянок,
      або /adminclaims, щоб створити безкоштовну адміністративну ділянку.
  AdvertiseAdminClaims:
    Text: Замість цього ви можете створити адміністративну ділянку за допомогою /adminclaims,
      якою ви поділитеся з іншими адміністраторами.
  AdvertiseACB:
    Text: Ви можете використовувати /acb, щоб отримати більше блоків для ділянок.
  NotYourPet:
    Text: Це належить гравцю {0}, доки він не передасть вам його за допомогою /givepet.
    Notes: '0: ім`я власника'
  PetGiveawayConfirmation:
    Text: Улюбленця передано.
  PetTransferCancellation:
    Text: Передачу улюбленця скасовано.
  ReadyToTransferPet:
    Text: Готово до передачі! Клацніть правою кнопкою миші на улюбленця, якого хочете
      віддати, або скасуйте за допомогою /givepet cancel.
  AvoidGriefClaimLand:
    Text: Запобігайте гріферству! Якщо ви займете свою землю, вона буде захищена від
      гріферів.
  BecomeMayor:
    Text: Розділіть свою ділянку та станьте мером!
  ClaimCreationFailedOverClaimCountLimit:
    Text: Ви досягли ліміту ділянок. Використайте /abandonclaim, щоб видалити одну
      перед створенням нової.
  CreateClaimFailOverlapRegion:
    Text: Ви не можете зайняти всю цю територію, оскільки вам не дозволено тут будувати.
  ResizeFailOverlapRegion:
    Text: У вас немає дозволу будувати там, тому ви не можете зайняти цю територію.
  ShowNearbyClaims:
    Text: Знайдено {0} ділянок.
    Notes: '0: Кількість знайдених ділянок.'
  NoChatUntilMove:
    Text: Вибачте, але вам потрібно трохи більше порухатися, перш ніж ви зможете писати
      в чат. Тут багато спам-ботів. :)
  SiegeImmune:
    Text: Цей гравець невразливий до /siege.
  SetClaimBlocksSuccess:
    Text: Оновлено нараховані блоки ділянок.
  IgnoreConfirmation:
    Text: Тепер ви ігноруєте повідомлення чату від цього гравця.
  NotIgnoringPlayer:
    Text: Ви не ігноруєте цього гравця.
  UnIgnoreConfirmation:
    Text: Ви більше не ігноруєте повідомлення чату від цього гравця.
  SeparateConfirmation:
    Text: Тепер ці гравці ігноруватимуть один одного в чаті.
  UnSeparateConfirmation:
    Text: Ці гравці більше не ігноруватимуть один одного в чаті.
  NotIgnoringAnyone:
    Text: Ви нікого не ігноруєте.
  TrustListHeader:
    Text: 'Тут явні дозволи:'
    Notes: '0: Власник ділянки'
  Manage:
    Text: Керувати
  Build:
    Text: Будувати
  Containers:
    Text: Контейнери
  Access:
    Text: Доступ
  HasSubclaimRestriction:
    Text: Цей підрозділ не успадковує дозволи від батьківської ділянки.
  StartBlockMath:
    Text: '{0} блоків з гри + {1} бонусних = {2} всього.'
  ClaimsListHeader:
    Text: 'Ділянки:'
  ContinueBlockMath:
    Text: ' (-{0} блоків)'
  EndBlockMath:
    Text: ' = {0} блоків залишилося'
  NoClaimDuringPvP:
    Text: Ви не можете займати ділянки під час PvP-бою.
  UntrustAllOwnerOnly:
    Text: Лише власник ділянки може видалити всі дозволи.
  ManagersDontUntrustManagers:
    Text: Лише власник ділянки може понизити менеджера.
  BookAuthor:
    Text: BigScary
  BookTitle:
    Text: Як зайняти землю
  BookIntro:
    Text: Займіть землю, щоб захистити свої речі! Натисніть на посилання вище, щоб
      дізнатися про приватні ділянки за 3 хвилини або менше. :)
  BookDisabledChestClaims:
    Text: '  На цьому сервері розміщення скрині НЕ буде автоматично займати для вас
      землю.'
  BookUsefulCommands:
    Text: 'Корисні команди:'
  BookLink:
    Text: 'Натисніть: {0}'
    Notes: '{0}: URL відео'
  BookTools:
    Text: Наші інструменти для ділянок - це {0} та {1}.
    Notes: '0: назва інструменту для зміни ділянки; 1: назва інструменту для інформації
      про ділянку'
  ResizeClaimTooNarrow:
    Text: Цей новий розмір буде занадто малим. Ділянки повинні бути не менше {0} блоків
      завширшки.
    Notes: '0: мінімальна ширина ділянки'
  ResizeClaimInsufficientArea:
    Text: Ця ділянка буде занадто малою. Будь-яка ділянка повинна використовувати
      не менше {0} загальних блоків.
    Notes: '0: мінімальна площа ділянки'
  NoProfanity:
    Text: Будь ласка, слідкуйте за своєю мовою.
  PlayerNotIgnorable:
    Text: Ви не можете ігнорувати цього гравця.
  NoEnoughBlocksForChestClaim:
    Text: Оскільки у вас немає доступних блоків для ділянок, автоматична ділянка не
      була створена. Ви можете використовувати /claimslist, щоб відстежувати загальну
      кількість доступних вам блоків.
  IsIgnoringYou:
    Text: Цей гравець вас ігнорує.
  MustHoldModificationToolForThat:
    Text: Для цього ви повинні тримати в руці золоту лопату.
  StandInClaimToResize:
    Text: Станьте всередині ділянки, розмір якої ви хочете змінити.
  ClaimsExtendToSky:
    Text: Приватні ділянки завжди простягаються до максимальної висоти будівництва.
  ClaimsAutoExtendDownward:
    Text: Приватні ділянки автоматично простягаються глибше під землю, коли ви розміщуєте
      блоки під ними.
  MinimumRadius:
    Text: Мінімальний радіус - {0}.
    Notes: '0: мінімальний радіус'
  RadiusRequiresGoldenShovel:
    Text: Вказуючи радіус, ви повинні тримати в руці золоту лопату.
  ClaimTooSmallForActiveBlocks:
    Text: Ця ділянка недостатньо велика для підтримки будь-яких активних блоків (лійки,
      спавнери, маяки...). Спочатку збільште ділянку.
  TooManyActiveBlocksInClaim:
    Text: Ця ділянка досягла ліміту для активних блоків (лійки, спавнери, маяки...).
      Або збільште її, або спочатку видаліть інші активні блоки.
  ConsoleOnlyCommand:
    Text: Цю команду можна виконувати лише з консолі сервера.
  WorldNotFound:
    Text: Світ не знайдено.
  AdjustBlocksAllSuccess:
    Text: Бонусні блоки ділянок для всіх онлайн-гравців змінено на {0}.
    Notes: '0: сума зміни'
  TooMuchIpOverlap:
    Text: Вибачте, занадто багато гравців увійшло з вашої IP-адреси.
  StandInSubclaim:
    Text: Щоб обмежити підрозділ, ви повинні перебувати всередині нього.
  SubclaimRestricted:
    Text: Дозволи цього підрозділу більше не успадковуватимуться від батьківської
      ділянки.
  SubclaimUnrestricted:
    Text: Дозволи цього підрозділу тепер успадковуватимуться від батьківської ділянки.
  NetherPortalTrapDetectionMessage:
    Text: Схоже, ви могли застрягти всередині порталу в Нижній світ. Якщо це так,
      ми врятуємо вас через кілька секунд!
    Notes: Надсилається гравцеві при вході, якщо він вийшов з гри, перебуваючи всередині
      порталу в Нижній світ.

```
