### DISCUSSION TITLE
Admin only claim worlds

### DISCUSSION THREAD

**Discussion by ShaneBeee** [GriefPrevention/GriefPrevention#500] [Ideas]
Hey Robo
I recently had someone bring this to my attention on my discord for GPFlags. But I thought Id post it here incase they dont find this.

I would like to recommend adding an AdminOnly option to the option for [which worlds you can claim in](
https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#limiting-which-worlds-griefprevention-runs-on)
An option where only admins (with permission) could claim admin claims in a world.

Ex:
```yaml
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_resource: -1
  Claims:
    Mode:
      world: Survival
      world_nether: Disabled
      world_resource: Admin <--- something like this
```

I came into this issue a while back where in my resource world, I didnt want players to be able to claim land, but I wanted to use GP to protect the spawn in the resource world. I ended up having to use WG which I really didnt want to have to do.

EDIT: **OR**
an option to allow admins to claim admin claims in "Disabled" worlds
