### DISCUSSION TITLE
/claim command does not always require claim modification tool to be held

### DISCUSSION THREAD

**Discussion by Camillo82** [GriefPrevention/GriefPrevention#517] [General]
Hello!
Is it possible for the admin or in the plugin config to disable _/claim_ command for players so it would be impossible to create any claim without a golden shovel?
If not - this is my small request ;)
Regards,
Camillo

**Comment by RoboMWM** [comment]
The `/claim` and `/extend` commands require you to hold the claim tool to use them.

**Comment by Jikoo** [comment]
If you REALLY don't want /claim or /extend to work, you could use a plugin I wrote back when I was annoyed at Essentials not setting permissions for their commands properly and instead using a later internal check. https://github.com/Jikoo/PermissionsSetup/releases

Config would look like this:
```YAML
commands:
  claim:
    permission: griefprevention.command.claim
    parents:
    - griefprevention.admin.*
  extendclaim:
    permission: griefprevention.command.extendclaim
    parents:
    - griefprevention.admin.*
```
