### DISCUSSION TITLE
Link issue

### DISCUSSION THREAD

**Discussion by aaaqueiroz** [GriefPrevention/GriefPrevention#944] [Q&A] [answered]
Is there any way I can exchange the video link for another link? It is in English, and the audience of the server is Portuguese and many cannot understand it well ...

**Comment by bigpresh** [comment, marked as answer]
You should be able to change it in messages.yml

There are several messages that refer to it, e.g.:

```
  CreativeBasicsVideo:
    Text: 'Land Claim Help: {0}'
    Notes: '{0}: video URL'
  SurvivalBasicsVideo:
    Text: 'Land Claim Help: {0}'
    Notes: '{0}: video URL'
```

The `{0}` would be replaced by the hardcoded video URL within the plugin, but you should be able to remove that placeholder and put your own video URL there instead?
