### ISSUE TITLE
Claiming Isn't Working

### ISSUE THREAD

**Issue by ArvickC** [GriefPrevention/GriefPrevention#1047]
### What happened:
When I try to claim with the shovel, it puts a diamond block and tells me to chose the other corner, when I go to do that, it just places another diamond-block?

### What was expected:
A claim to be created.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
![image](https://user-images.githubusercontent.com/69405114/95147346-5bd0be00-0735-11eb-968f-9af3b044bc46.png)

Paste of `/version GriefPrevention`: 
![image](https://user-images.githubusercontent.com/69405114/95147368-68551680-0735-11eb-97bd-41e5bea8d6fe.png)

### Stack trace/error or server log

```
Server logged nothing

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    Plots: -1
    world_NonOg_end: -1
    parkourmap3: -1
    RealKitPvp: -1
    bskyblock_world_the_end: -1
    ParkourMap2: -1
    caveblock-world_nether: -1
    caveblock-world_the_end: -1
    bskyblock_world: -1
    ParkourMap1: -1
    world_nonog_real: -1
    world_NonOg_nether: -1
    SmallNether: -1
    caveblock-world: -1
    HungerGamesMap4: -1
    HungerGamesMap2: -1
    HungerGamesMap1: -1
    Events: -1
    SmallSMP: -1
    BigHub: -1
    TheRealHungerGamesMap3: -1
    bskyblock_world_nether: -1
    KitPvp: -1
    worldsave: -1
    rpgtest: -1
  Claims:
    Mode:
      RealKitPvp: Disabled
      caveblock-world_nether: Disabled
      bskyblock_world: Disabled
      SmallNether: Disabled
      world_nonog_real: Survival
      caveblock-world: Disabled
      SmallSMP: Disabled
      world_nether: Survival
      HungerGamesMap2: Disabled
      BigHub: Disabled
      Plots: Disabled
      TheRealHungerGamesMap3: Disabled
      parkourmap3: Disabled
      world_NonOg_nether: Survival
      bskyblock_world_the_end: Disabled
      ParkourMap1: Disabled
      world: Survival
      caveblock-world_the_end: Disabled
      HungerGamesMap4: Disabled
      rpgtest: Disabled
      HungerGamesMap1: Disabled
      world_the_end: Survival
      ParkourMap2: Disabled
      worldsave: Disabled
      world_NonOg_end: Survival
      bskyblock_world_nether: Disabled
      Events: Disabled
      KitPvp: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 5000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: false
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      Plots: false
      world_NonOg_end: true
      parkourmap3: false
      RealKitPvp: false
      bskyblock_world_the_end: true
      ParkourMap2: false
      caveblock-world_nether: true
      caveblock-world_the_end: true
      bskyblock_world: true
      ParkourMap1: false
      world_nonog_real: true
      world_NonOg_nether: true
      SmallNether: true
      caveblock-world: true
      HungerGamesMap4: false
      HungerGamesMap2: false
      HungerGamesMap1: false
      Events: false
      SmallSMP: true
      BigHub: false
      TheRealHungerGamesMap3: false
      bskyblock_world_nether: true
      KitPvp: false
      worldsave: false
      rpgtest: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 5
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/warp l
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 5
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
