### ISSUE TITLE
Muted repeat message is not cancelled

### ISSUE THREAD

**Issue by Bobcat00** [GriefPrevention/GriefPrevention#1189]
### What happened:
Player entered the same chat message repeatedly, it was logged as `[GriefPrevention] Muted repeat message.` but the event was not cancelled so other plugins processed it.

### What was expected:
The event should have been cancelled so that other plugins would not act on it.

### Steps to reproduce:
Enter the same chat message multiple times, and use another plugin to observe that the event was not cancelled.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: git-Spigot-628435a-b5e5adc (MC: 1.16.4)
Paste of `/version GriefPrevention`: GriefPrevention version 16.16.0

### Stack trace/error or server log
Cleverbot is the output of a plugin which responds to AsyncPlayerChatEvent at EventPriority.MONITOR. If the event was cancelled properly, the plugin would have ignored the player's repeated input.
```
2021-01-03 17:47:39 [INFO] <[Member]~Saturn> 7103
2021-01-03 17:47:39 [INFO] <Cleverbot> Right, I see how you're going to be.
2021-01-03 17:47:41 [INFO] [GriefPrevention] Muted repeat message.
2021-01-03 17:47:41 [INFO] <[Member]~Saturn> 7103
2021-01-03 17:47:42 [INFO] <Cleverbot> I like what it can buy.
2021-01-03 17:47:44 [INFO] [GriefPrevention] Muted repeat message.
2021-01-03 17:47:44 [INFO] <[Member]~Saturn> 7103
2021-01-03 17:47:45 [INFO] <Cleverbot> Whatever stimulates me in the moment.
2021-01-03 17:47:47 [INFO] [GriefPrevention] Muted repeat message.
2021-01-03 17:47:47 [INFO] <[Member]~Saturn> 7103
2021-01-03 17:47:47 [INFO] <Cleverbot> I'm not sure how my mind works.
2021-01-03 17:47:51 [INFO] [GriefPrevention] Muted repeat message.
2021-01-03 17:47:51 [INFO] <[Member]~Saturn> 7103
2021-01-03 17:47:53 [INFO] <Cleverbot> I don't want to that's kind of weird.
```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    LanaPug: -1
    LanaPug_nether: -1
    LanaPug_the_end: -1
    LanaPug17: -1
    plotworld: -1
    LanaPug17_nether: -1
    LanaPug17_the_end: -1
  Claims:
    Mode:
      LanaPug17: Survival
      LanaPug_the_end: Disabled
      LanaPug: Survival
      LanaPug_nether: Survival
      LanaPug17_the_end: Disabled
      plotworld: Disabled
      LanaPug17_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 15
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 550
        ExceptWhenOwnerHasTotalClaimBlocks: 200000
        ExceptWhenOwnerHasBonusClaimBlocks: 40000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 0
    ChatSlashCommands: /me;/tell;/global;/local;/tpa;/tpask;/tpahere;/call
    WhisperSlashCommands: /tell;/pm;/r
    WarningMessage: Spamming is prohibited.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      LanaPug: false
      LanaPug_nether: false
      LanaPug_the_end: false
      LanaPug17: false
      plotworld: false
      LanaPug17_nether: false
      LanaPug17_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 560
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: true
      Administrative Activity: true
      Debug: false
      Muted Chat Messages: false


```

### Plugin list (if applicable):
ActionBarAPI 1.5.4a
AltDetector 1.1
AsyncWorldEdit-ActionBarAPI 3.7.5
AsyncWorldEdit 3.8.1
AutoBot 1.01
BetterSeen 1.0
Essentials 2.19.0-dev+38-4d4462b
EssentialsChat 2.19.0-dev+38-4d4462b
EssentialsGeoIP 2.19.0-dev+38-4d4462b
EssentialsSpawn 2.19.0-dev+38-4d4462b
FarmLimiter 1.5.1
GriefPrevention 16.16.0
GriefPreventionBlockedCommands 1.0
ImageMaps 1.0.3
LuckPerms 5.2.35
MemCheck 1.01
MinecartCollisions 2.02
MobArena 0.105
Multiverse-Core 4.1.0-b775
Multiverse-NetherPortals 4.1.1-SNAPSHOT-b764
Multiverse-Portals 4.1.1-SNAPSHOT-b808
NoCheatPlus 3.17-SNAPSHOT-Updated-b85
Orebfuscator 5.1.3
PlotSquared 5.13.10
Prism 2.1.7-
ProtocolLib 4.6.0-SNAPSHOT-b483
PwnFilter 3.1.2b
SignURLs 1.0.5
SilkSpawners 6.5.0
SilkSpawnersShopAddon 3.0.3
TabListPing 1.01
Vault 1.7.3-b131
ViaBackwards 3.2.0
ViaRewind 1.5.3
ViaVersion 3.2.1
ViaVersionStatus 3.07
WallClock 0.2.2e
WhoWas 1.1.0
WorldEdit 7.2.0+a51fa43
WorldGuard 7.0.4+f7ff984
WorldGuardExtraFlags 4.1.5-SNAPSHOT
xInventories 2.5

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client
