### ISSUE TITLE
Nether Ceiling Claims

### ISSUE THREAD

**Issue by the-najjar** [GriefPrevention/GriefPrevention#1259]
### What happened:
One of my players claimed an area above the nether ceiling, when they try to abandon that claim, trust anyone, make a subclaim inside it, it says that there's no claim. I even tried to set new owner for the claim, still didn't work. went to bedrock level and placed a block and removed it inside that claim and tried the previous steps none seems to detect the claim.

### What was expected:
GP should detect the claim as a claim, since the claim exists.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1- player claimed the area from block 1 higher than the bedrock nether ceiling
2- it couldn't detect the claim
3- if the player uses their stick below nether cieling it still doesn't detect claim
4- player goes to bedrock level all the way near y level 0 and places a block
5- claim gets updated and shows as their own claim
6- players goes back up and tries to execute any claim related command, the following message shows, even when trying to abandon the claim or make subclaim inside it
7- Note it only happend to this player, i tried to reproduce right next to his claim, and I got no issue.
![alt text](https://i.ibb.co/p67hQT8/2021-02-13-08-39-32.png)

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
GriefPrevention version 16.17.1-2b69191
Paper version git-Paper-467 (MC: 1.16.5)

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    survival: -1
    survival_nether: -1
    survival_the_end: -1
    fantasy: -1
    tutorial: -1
    creative: -1
    evenet: -1
  Claims:
    Mode:
      survival: Survival
      fantasy: Survival
      evenet: Disabled
      survival_nether: Survival
      creative: Disabled
      survival_the_end: Survival
      tutorial: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 20000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 0
    MinimumWidth: 3
    MinimumArea: 0
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 60
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 100000000
        ExceptWhenOwnerHasBonusClaimBlocks: 100000000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: false
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 1
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      survival: true
      survival_nether: true
      survival_the_end: true
      fantasy: true
      tutorial: false
      creative: false
      evenet: false
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /vanish
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 2.0
    ClaimBlocksSellValue: 1.5
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: false
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 2
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: jdbc:mysql://mysql.apexhosting.gdn:3306/apexMC321871?allowReconnect=true&?verifyServerCertificate=false&useSSL=false
    UserName: apexMC321871
    Password: e09573062b
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 300
    OfflinePlayer_cache_days: 9000
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Plugin list (if applicable):
AdvancedAchievements, AdvancedRegionMarket, AdvancedTabOverlay, ArmorStandEditor, Autorank, BetterBees, BetterShulkerBoxes*, BlockParticles, BookShelf, BuycraftX, ChatManager, Citizens, ClueScrolls, CoreProtect, CraftEnhance, CrazyCrates, DiscordSRV, dynmap*, EpicWorldGenerator, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, floodgate-bukkit, Floodgate-Skript, Geyser-Spigot, GriefPrevention, GriefPreventionDynmapLite*, HolographicDisplays, HomeGUI, HubParkour, IllegalStack, InteractiveChat, InteractiveChatDiscordSRVAddon, InventoryRollback, InvisibleItemFrame, ItemEdit, LibsDisguises, LuckPerms, MarriageMaster, mcMMO, MobFarmManager, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyPet, MyPetGUI*, NBTAPI, OpenInv, PlaceholderAPI, PlayerWarps, PlotSquared, PluginConstructorAPI, PosePlugin, PosePluginAPI, ProtocolLib, PvPManager, QuickFarm, SAML, Shop, SignEdit, SkBee, Skellett, skRayFall, Skript, skript-placeholders*, Spartan, SQLibrary*, TuSKe*, UltimateTimber, uShop, Vault, ViaBackwards, ViaVersion, VoidGenerator, VoidSpawn, Votifier, VotingPlugin, Wild, WorldBorder, WorldEdit, WorldGuard

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client
