### ISSUE TITLE
TNT minecarts will destroy other players's claims, regardless of Trust and ClaimExplosions

### ISSUE THREAD

**Issue by Antivalent** [GriefPrevention/GriefPrevention#137]
What behaviour is expected:
TNT minecarts only do block damage when the player placing the minecart has /Trust for the claim on which the explosion occurs and /ClaimExplosions on that claim allows it.

What behaviour is observed:
TNT minecarts can be placed on your claim and pushed onto someone else's, triggering the explosion will do block damage regardless of /Trust permissions given and the /ClaimExplosions setting.

Steps/models to reproduce:
1. Create an own claim next to someone else's
2. Place some rails and a TNT minecart
3. Push the TNT minecart off the rails, onto the other player's claim
4. Trigger the explosion (I used a flame enchanted bow)
5. You just griefed that poor guy

Spigot/Craftbukkit/Paper and GriefPrevention version:
Paper (git-Paper-1104, 1.11.2-R0.1-SNAPSHOT)
GriefPrevention 16.7.1

GriefPrevention config.yml:
```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Build: -1
  Claims:
    Mode:
      Build: SurvivalRequiringClaims
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 1024
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 1024
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 64
    MinimumWidth: 8
    MinimumArea: 256
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 30
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 365
        ExceptWhenOwnerHasTotalClaimBlocks: 4096
        ExceptWhenOwnerHasBonusClaimBlocks: 4096
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome;/esethome;/createhome;/ecreatehome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 60
  Spam:
    Enabled: false
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 60
    ChatSlashCommands: /afk;/eafk;/away;/eaway;/me;/eme;/action;/eaction;/describe;/edescribe;/tpa;/etpa;/tpask;/etpask;/call;/ecall;/tpahere;/etpahere
    WhisperSlashCommands: /msg;/emsg;/m;/pm;/epm;/tell;/etell;/t;/whisper;/ewhisper;/w;/reply;/ereply;/r;/er;/mail;/email;/eemail;/memo;/ememo
    WarningMessage: Bitte spamme nicht im Chat. Spammer werden automatisch gebannt.
    BanOffenders: false
    BanMessage: Automatisch gebannt wegen Spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Build: false
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 12
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers: false
    AllowFlintAndSteelNearOtherPlayers: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 2.0
    ClaimBlocksSellValue: 2.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: false
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: true
  Database:
    URL: jdbc:mysql://localhost/almost_forgot
    UserName: to_obfuscate
    Password: this_stuff
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```
