### ISSUE TITLE
Only deactivate the /claim Command

### ISSUE THREAD

**Issue by b0ykoe** [GriefPrevention/GriefPrevention#140]
Hey,

is there any way to just deactivate the /claim command?
I saw the way over the griefprevention.claims permission but that deactivates /trust etc. also.

The reason behind is Iam using GPRealEstate to sell Claims and I dont want the players to create Claims, i deactivated the Goldshovel b ut they still can use /claim..

Would be nice if you gimme some help

Friendly Regards

**Comment by bigpresh** [comment]
I don't believe there's any built-in support for that.  It might not be a bad thing for there to be a separate "can modify own claims, but can't create them yourself" permission, but I'm not sure how popular a use-case that would be, whether it would warrant being something in the GP core, or should be handled as a plugin - I imagine the latter would make sense.

In the meantime, you could probably handle it outside of GP using a filter plugin, e.g. PwnFilter, which listens at a higher priority, and catches and blocks `/claim` commands.

**Comment by b0ykoe** [comment]
Oh yeah, alright. 

I still wish you a nice day!

**Comment by Antivalent** [comment]
Open your GriefPrevention.jar, extract the plugin.yml file, open it, find "claim" in the list of commands and then modify it like this:
```yml
    claim:
      description: Creates a land claim centered at your current location.
      usage: /Claim [optional radius]
      aliases: [createclaim, makeclaim, newclaim]
      permission: griefprevention.claimcommand
      permission-message: 'You cannot create your own claim in this world, but you may buy one instead.'
```
You can then put the extracted plugin.yml file back into your GriefPrevention.jar, just be sure to overwrite the old one. Players will now need to have 'griefprevention.claims' and your custom 'griefprevention.claimcommand' permission in order to create their own land claims.

This is probably the most ghetto fix possible, but it should work nonetheless.
