### ISSUE TITLE
GriefPrevention Subdivisions don't work in the latest version

### ISSUE THREAD

**Issue by jackysacki** [GriefPrevention/GriefPrevention#1447]
### What happened:
Griefprevention Subdivisions don't work in 1.17 - 
I have a big claim that I trusted multiple friends in and then I have a small subdivision inside that claim that I only trusted one friend in. One of the friends who wasn't supposed to be able to access shulker boxes and chests in a subdivision was able to open them. I managed to sort the issue out for now, I used the plugin BlockLocker to lock his boxes instead, 

### What was expected:
The chests and shulker boxes shouldn't have been accessible to someone who is only trusted in the big claim and not the subdivision

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Subdivide a claim.
2. Get someone who isn't trusted in said subdivision to try to open a chest.
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 89c9c90 on HEAD)
You are running the latest version
Previous version: git-Purpur-1254 (MC: 1.17)
Paste of `/version GriefPrevention`: 
GriefPrevention version 16.17.1-2b69191

### Stack trace/error or server log
It doesn't put anything in the console. Literally Nothing happens
Also nothing in the logs, it doesn't notice that it's happening
```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml
https://panel.birdflop.com/server/b4b32918/files/edit#/plugins/GriefPreventionData/config.yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    build: -1
    minigames: -1
    carnival: -1
    xrun: -1
  Claims:
    Mode:
      build: Survival
      world_nether: Survival
      xrun: Survival
      world_the_end: Survival
      carnival: Survival
      minigames: Survival
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 3000
    Claim Blocks Accrued Per Hour:
      Default: 300
    Max Accrued Claim Blocks:
      Default: 8000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 300
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 100
      UnusedClaimDays: 100
      AllClaims:
        DaysInactive: 100
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: false
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      build: true
      minigames: true
      carnival: true
      xrun: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: true
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 3.0
    ClaimBlocksSellValue: 1.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
Plugins (112): AdvancedDiscordLogger*, AdvancedPortals, AdvancedRegionMarket, AlonsoTags, ArmorStandEditor, ArmorStandTools, AuctionHouse, AutoRestart*, BanFromClaim, BeastWithdraw, BetterConcrete, BetterRTP, BetterTridents, BlockLocker, ChatColor2, ChatFeelings, ChatItemDisplay, ChatReaction, Citizens, CMILib, ColoredSigns, CoreProtect, CraftingStore, CustomCrafting, DailyRewards, DeluxeTags*, DiscordDeathMessages, DiscordSRV, DualWield*, EffectBoots, eGlow, Essentials, EssentialsChat, EssentialsSpawn, GesturePlus*, GLight, GMusic, GriefPrevention, GriefPreventionFlags, GSit, HeadDatabase, HiveChecker, HolographicDisplays, HyperPortalBreaking, ImageMaps, ImageOnMap, Interactions, InteractiveChat, InvisibleItemFrames, Jobs, JukeBoxPlus, KickFromClaim, LavaSponge, LibsDisguises, LiteBans, LuckPerms, LunarFreeCam*, MarriageMaster, mcMMO, MineableSpawners, MiniMOTD, MMOItems, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, MyCommand, MythicLib, MythicMobs, NBTAPI, NetherWater, OpenInv, PetBlocks*, PlaceholderAPI, PlayerHeads, PlayerParticles, PlayerVaults, ProCosmetics, ProtocolLib, PureEssentials, PvPToggle, PWarp, QuickShop, QuickShopList, ServerTips, ShopGUIPlus, ShopGUIPlus-SellGUI, Shopkeepers, ShulkerPacks, SimpleHorseInfo, SimpleRename, SinglePlayerSleep, spark, SpecializedCrates, SuperVanish, SurvivalInvisiframes, TAB, TCPShield, TitleManager, TradeSystem, Tweakin, Vault, VeinMiner, ViaBackwards, ViaVersion, VoidGenerator, WolfyUtilities, WorldEdit, WorldGuard, YamipaPlugin

(GPFlags is a plugin made by a person called ShaneBee, weirdly this plugin still works perfectly fine)
https://www.spigotmc.org/resources/griefprevention-flags.55773/

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

Sorry, we're all new to this - we only started running the server a couple months ago and I'm not really a coding guy, just a risk taking idiot, so I don't understand a lot of this stuff - I've tried, there are things I don't understand though

FYI this is my first time ever even reporting something on github - I made my account a few hours ago so I would be able to report this

Also sorry about my sarcastic review I made and then deleted (if you saw that) on Spigot, I couldn't find the page to add a bug report but I found it now and it's easy. I assumed u guys have a discord like everyone does then noticed it's an IRC

The weird thing is literally NOTHING happens. Nothing, Zero, Zilch, Nada, whatever weird words people use. I just found out how to find the server logs and stuff and nothing happened. Anything. Yet the logs  still point out if someone places a water bucket suspiciously... and people like to "MLG bucket" so it happens a lot

With the banned word list btw messages you say that get blocked still show to the person who said them even though they don't to anyone else

Also lastly we use a custom server type .jar file thing that's not widely used, recommended to us by a developer who helped us switch from our old host to this one (Birdflop)
You can download it here if you want to try reproducing this yourself
https://purpur.pl3x.net/downloads/#1.17
