### ISSUE TITLE
Claims don't load

### ISSUE THREAD

**Issue by TheSonicProf** [GriefPrevention/GriefPrevention#1592]
### What happened:
Claims do not load.

### What was expected:
I expected the claims to load.

### Steps to reproduce:
This just happens every time I boot up the server.

### Server and GriefPrevention version:
This server is running CraftBukkit version 3238-Spigot-6c1c1b2-9217b52 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
GriefPrevention version 16.17.1-2b69191

### Stack trace/error or server log

```
[20:14:06 INFO]: [GriefPrevention] 9.yml java.lang.Exception: Expected four distinct parts to the location string: "[B@7d98a30a"
	at me.ryanhamshire.GriefPrevention.DataStore.locationFromString(DataStore.java:542)
	at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:493)
	at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaim(FlatFileDataStore.java:483)
	at me.ryanhamshire.GriefPrevention.FlatFileDataStore.loadClaimData(FlatFileDataStore.java:434)
	at me.ryanhamshire.GriefPrevention.FlatFileDataStore.initialize(FlatFileDataStore.java:212)
	at me.ryanhamshire.GriefPrevention.FlatFileDataStore.<init>(FlatFileDataStore.java:64)
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:318)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:511)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:425)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619)
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010)
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
	at java.base/java.lang.Thread.run(Thread.java:831)

[20:14:06 INFO]: [GriefPrevention] 0 total claims loaded.
[20:14:06 INFO]: [GriefPrevention] Customizable messages loaded.
[20:14:06 INFO]: [GriefPrevention] Finished loading data (File Mode).
[20:14:06 INFO]: [GriefPrevention] Boot finished.
[20:14:06 INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:14:06 INFO]: Done (6.669s)! For help, type "help"

```

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01Q": -1
    !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01QX25ldGhlcg==": -1
    !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01QX3RoZV9lbmQ=": -1
  Claims:
    Mode:
      !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01Q": Survival
      !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01QX3RoZV9lbmQ=": Disabled
      !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01QX25ldGhlcg==": Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01Q": true
      !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01QX25ldGhlcg==": true
      !!binary "w6TCvcKVw6PCgcKqw6PCgsKKU01QX3RoZV9lbmQ=": true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Debugging steps attempted

- [x] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client
