### ISSUE TITLE
Claim expiration bug

### ISSUE THREAD

**Issue by Bobcat00** [GriefPrevention/GriefPrevention#1597]
### What happened:
A player's claims were not expired even though he has been inactive for longer than the Expiration.AllClaims.DaysInactive time.

### What was expected:
All claims to be deleted shortly after the time expired.

### Steps to reproduce:
Player needs at least two claims, but the _first_ claim has to be the size of the automatic chest claim _and_ Expiration.ChestClaimDays must be greater than 0. Then this if statement is executed https://github.com/TechFortress/GriefPrevention/blob/746f10449d527410ae8af7815bdbd57671d449a4/src/main/java/me/ryanhamshire/GriefPrevention/CleanupUnusedClaimTask.java#L55 and entered. But when this if statement is checked https://github.com/TechFortress/GriefPrevention/blob/746f10449d527410ae8af7815bdbd57671d449a4/src/main/java/me/ryanhamshire/GriefPrevention/CleanupUnusedClaimTask.java#L61 it fails because the owner has more than one claim.

Then the rest of the if statement is skipped, **but the next check (which is where the claim deletion should happen) is skipped because it's an 'else if'.**

The logic needs to be modified so that if the chest claim check is skipped for any reason, the regular expiration check is still executed.

### Server and GriefPrevention version:
3096-Spigot-9fb885e-296df56 (MC: 1.16.5)
GriefPrevention version 16.17.1-2b69191

### Stack trace/error or server log
N/A

### GriefPrevention config.yml

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    LanaPug: -1
    LanaPug_nether: -1
    LanaPug_the_end: -1
    LanaPug17: -1
    plotworld: -1
    LanaPug17_nether: -1
    LanaPug17_the_end: -1
  Claims:
    Mode:
      LanaPug17: Survival
      LanaPug_the_end: Disabled
      LanaPug: Survival
      LanaPug_nether: Survival
      LanaPug17_the_end: Disabled
      plotworld: Disabled
      LanaPug17_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 15
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 550
        ExceptWhenOwnerHasTotalClaimBlocks: 200000
        ExceptWhenOwnerHasBonusClaimBlocks: 40000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 3
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 0
    ChatSlashCommands: /me;/tell;/global;/local;/tpa;/tpask;/tpahere;/call
    WhisperSlashCommands: /tell;/pm;/r
    WarningMessage: Spamming is prohibited.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      LanaPug: false
      LanaPug_nether: false
      LanaPug_the_end: false
      LanaPug17: false
      plotworld: false
      LanaPug17_nether: false
      LanaPug17_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 560
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: true
      Administrative Activity: true
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
ActionBarAPI 1.5.4a
AltDetector 1.1
AsyncWorldEdit-ActionBarAPI 3.8.3
AsyncWorldEdit 3.8.4
AutoBot 1.01
BetterSeen 1.0
Essentials 2.19.0-dev+83-a07b277
EssentialsChat 2.19.0-dev+83-a07b277
EssentialsGeoIP 2.19.0-dev+83-a07b277
EssentialsSpawn 2.19.0-dev+83-a07b277
FarmLimiter 1.5.1
GriefPrevention 16.17.1-2b69191
GriefPreventionBlockedCommands 1.0
ImageMaps 1.0.6
IronDoors 1.6a
LuckPerms 5.3.0
MemCheck 1.01
MinecartCollisions 2.02
MobArena 0.105
Multiverse-Core 4.2.2-b812
Multiverse-NetherPortals 4.2.1-b786
Multiverse-Portals 4.2.1-b834
NoCheatPlus 3.17-SNAPSHOT-Updated-b92
Orebfuscator 5.1.4
PlotSquared 5.13.10
Prism 2.1.8-SNAPSHOT-224
ProtocolLib 4.6.0
PwnFilter 3.1.2b
SignURLs 1.0.5
SilkSpawners 7.0.0
SilkSpawnersShopAddon 3.0.3
TabListPing 1.02
Vault 1.7.3-b131
ViaBackwards 4.0.1
ViaRewind 2.0.1
ViaVersion 4.0.1
ViaVersionStatus 3.10-SNAPSHOT
WallClock 0.2.2e
WhoWas 1.1.0
WorldEdit 7.2.5+57d5ac9
WorldGuard 7.0.4+f7ff984
WorldGuardExtraFlags 4.1.5-SNAPSHOT
xInventories 2.5

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client
