### ISSUE TITLE
In 1.12 you cannot create claims.

### ISSUE THREAD

**Issue by DavidxRussell** [GriefPrevention/GriefPrevention#164]
### What behaviour is expected: Claim creation
_What you expected to see_
### What behaviour is observed: No claim creation, along with a message saying that an internal error has occurred.
_What you actually saw_
### Steps/models to reproduce:
Step 1: Do /claim in Minecraft 1.12
Step 2: Read the chat. It should say an internal error has occurred.
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version: 16.7.1
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error (if applicable)
19:49:53  [Info] DavidxRussell issued server command: /clai
19:49:53  [Error] nullorg.bukkit.command.CommandException: Unhandled exception executing command 'claim' in plugin GriefPrevention v16.7.1	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]Caused by: java.lang.NullPointerException	at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:219) ~[?:?]	at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:344) ~[?:?]	at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:211) ~[?:?]	at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:228) ~[?:?]	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:508) ~[?:?]	at com.sk89q.worldguard.bukkit.permission.AbstractPermissionModel.hasPluginPermission(AbstractPermissionModel.java:45) ~[?:?]	at com.sk89q.worldguard.bukkit.permission.RegionPermissionModel.mayIgnoreRegionProtection(RegionPermissionModel.java:42) ~[?:?]	at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:29) ~[?:?]	at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:845) ~[?:?]	at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1071) ~[?:?]	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-cd6ba67-f7d14f1]	... 15 more
```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world: Survival
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 6250000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 14
        ExceptWhenOwnerHasTotalClaimBlocks: 1000000000
        ExceptWhenOwnerHasBonusClaimBlocks: 705032704
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: true
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 0
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: false
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: world
    BreakableBlocks:
    - DOOR
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```
