### ISSUE TITLE
Players can click powder snow bucket on grass blocks inside claims to turn them snowy

### ISSUE THREAD

**Issue by lerokko** [GriefPrevention/GriefPrevention#1684]
### Observed Behavior

Protected grass blocks can be turned snowy by clicking them with a powder snow bucket. The "You can not..." fires and the bucket is not consumed, but this just makes it easier to grief with this since you can spam entire landscapes and it needs a block on top to return to normal. The issue is not client side.

### Expected Behavior

The grass_block should not change its state to snow at all.

### Reproduction steps

1.Make claim
2. Make untrusted player click with a powder snow bucket on a grass_block in said claim
3. Grass turns into snowy variant without a block being placed.

### Server version

```shell
This server is running Paper version git-Paper-"0fe0613" (MC: 1.18 Release Candidate 3) (Implementing API version 1.18-rc3-R0.1-SNAPSHOT) (Git: 0fe0613 on dev/1.18)
Error obtaining version information
```

### GriefPrevention version

```shell
GriefPrevention version 16.17.1-2b69191
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world_test: -1
    world_test_nether: -1
    world_test_the_end: -1
  Claims:
    Mode:
      world_test_the_end: Disabled
      world_test_nether: Disabled
      world_test: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: false
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1024
    Claim Blocks Accrued Per Hour:
      Default: 256
    Max Accrued Claim Blocks:
      Default: 10000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 7
    MinimumWidth: 4
    MinimumArea: 25
    MaximumDepth: 0
    InvestigationTool: GOLDEN_AXE
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 180
      UnusedClaimDays: 180
      AllClaims:
        DaysInactive: 730
        ExceptWhenOwnerHasTotalClaimBlocks: 4096
        ExceptWhenOwnerHasBonusClaimBlocks: 4096
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: true
    MaximumNumberOfClaimsPerPlayer: 200
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: true
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 4
    LoginLogoutNotificationsPerMinute: 10
    ChatSlashCommands: /me;/global;/local;/afk
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 90
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world_test: true
      world_test_nether: true
      world_test_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/spec
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  PistonMovement: IGNORED
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 4
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS     <-- can't understand this entry, see BukkitDev documentation
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS     <-- can't understand this entry, see BukkitDev documentation
    - WOOD     <-- can't understand this entry, see BukkitDev documentation
    - WOOL     <-- can't understand this entry, see BukkitDev documentation
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 30
    OfflinePlayer_cache_days: 1825
  Abridged Logs:
    Days To Keep: 30
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Running without GriefPrevention

- [x] I attempted running the server without GriefPrevention installed.
- [x] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [x] I attempted running only GriefPrevention on the server.
- [x] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
