### ISSUE TITLE
GriefPrevention crashing Paper server

### ISSUE THREAD

**Issue by weihao** [GriefPrevention/GriefPrevention#1737]
### Observed Behavior

GriefPrevention crashing Paper server

### Expected Behavior

N/A

### Reproduction steps

- MySQL
```
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--interactive-timeout=2147483",
        "--wait_timeout=2147483",
```

- GriefPrevention

### Stack trace or error log

```shell
Dec 31, 2021 @ 00:29:30.452	[05:29:29 ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)

Dec 31, 2021 @ 00:29:30.452	[05:29:29 ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$3931/0x000000080142f298.run(Unknown Source)

Dec 31, 2021 @ 00:29:30.452	[05:29:29 ERROR]: 		java.base@17.0.1/java.lang.Thread.run(Thread.java:833)

Dec 31, 2021 @ 00:29:30.451	[05:29:29 ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)

Dec 31, 2021 @ 00:29:30.451	[05:29:29 ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)

Dec 31, 2021 @ 00:29:30.451	[05:29:29 ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)

Dec 31, 2021 @ 00:29:30.450	[05:29:29 ERROR]: 		net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221)

Dec 31, 2021 @ 00:29:30.450	[05:29:29 ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636)

Dec 31, 2021 @ 00:29:30.448	[05:29:29 ERROR]: 		net.minecraft.network.Connection.handleDisconnection(Connection.java:714)

Dec 31, 2021 @ 00:29:30.446	[05:29:29 ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1956)

Dec 31, 2021 @ 00:29:30.420	[05:29:29 ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1976)

Dec 31, 2021 @ 00:29:30.419	[05:29:29 ERROR]: 		net.minecraft.server.players.PlayerList.remove(PlayerList.java:591)

Dec 31, 2021 @ 00:29:30.419	[05:29:29 ERROR]: 		net.minecraft.server.players.PlayerList.remove(PlayerList.java:606)

Dec 31, 2021 @ 00:29:30.418	[05:29:29 ERROR]: 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)

Dec 31, 2021 @ 00:29:30.418	[05:29:29 ERROR]: 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)

Dec 31, 2021 @ 00:29:30.418	[05:29:29 ERROR]: 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)

Dec 31, 2021 @ 00:29:30.417	[05:29:29 ERROR]: 		java.base@17.0.1/java.lang.invoke.LambdaForm$MH/0x0000000801ca1800.invoke_MT(LambdaForm$MH)

Dec 31, 2021 @ 00:29:30.417	[05:29:29 ERROR]: 		com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)

Dec 31, 2021 @ 00:29:30.417	[05:29:29 ERROR]: 		java.base@17.0.1/java.lang.invoke.LambdaForm$MH/0x0000000801c88000.invoke(LambdaForm$MH)

Dec 31, 2021 @ 00:29:30.416	[05:29:29 ERROR]: 		java.base@17.0.1/java.lang.invoke.DirectMethodHandle$Holder.invokeVirtual(DirectMethodHandle$Holder)

Dec 31, 2021 @ 00:29:29.078	[05:29:29 ERROR]: 		GriefPrevention.jar//me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerQuit(PlayerEventHandler.java:963)

Dec 31, 2021 @ 00:29:29.076	[05:29:29 ERROR]: 		GriefPrevention.jar//me.ryanhamshire.GriefPrevention.DataStore.savePlayerData(DataStore.java:1022)

Dec 31, 2021 @ 00:29:29.060	[05:29:29 ERROR]: 		java.base@17.0.1/java.lang.Thread.start(Thread.java:802)

Dec 31, 2021 @ 00:29:29.011	[05:29:29 ERROR]: 		java.base@17.0.1/java.lang.Thread.start0(Native Method)

Dec 31, 2021 @ 00:29:29.009	[05:29:29 ERROR]: 	Stack:

Dec 31, 2021 @ 00:29:29.008	[05:29:29 ERROR]: 	PID: 23 | Suspended: false | Native: false | State: RUNNABLE
```
```


### Server version

```shell
This server is running Paper version git-Paper-112 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 329912b)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-111 (MC: 1.18.1)
```

### GriefPrevention version

```shell
GriefPrevention version 16.17.1-42-g3562a23
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: 320
    world_nether: 320
    world_the_end: 320
  Claims:
    Mode:
      world_nether: Survival
      world: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 1000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 320
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 3
      UnusedClaimDays: 7
      AllClaims:
        DaysInactive: 14
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: ''
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: true
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: jdbc:mysql://db:3306/<filtered>
    UserName: <filtered>
    Password: <filtered>
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
