### ISSUE TITLE
Server Timout in particular Biomes when commands are issued.

### ISSUE THREAD

**Issue by DaddyHunger** [GriefPrevention/GriefPrevention#1797]
### Observed Behavior

[05:01:46] [Server thread/INFO]: SaegusaMayumi issued server command: /abandonallclaims confirm
[05:01:49] [Craft Scheduler Thread - 507 - GriefPrevention/WARN]: [GriefPrevention] Plugin GriefPrevention v16.17.1-2b69191 generated an exception while executing task 310801
java.lang.NoSuchFieldError: DESERT_HILLS
	at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.getPlayerBlocks(RestoreNatureProcessingTask.java:835) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.lambda$getBiomeBlocks$0(AutoExtendClaimTask.java:78) ~[GriefPrevention.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getBiomeBlocks(AutoExtendClaimTask.java:78) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getLowestBuiltY(AutoExtendClaimTask.java:57) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.run(AutoExtendClaimTask.java:32) ~[GriefPrevention.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1456]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1456]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1456]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:03:38] [Craft Scheduler Thread - 508 - BuycraftX/INFO]: [BuycraftX] Fetching all due players...
[05:03:39] [Craft Scheduler Thread - 508 - BuycraftX/INFO]: [BuycraftX] Fetched due players (1 found).
[05:03:44] [Server thread/INFO]: com.mojang.authlib.GameProfile@36ae90ad[id=<null>,name=MiLKy563,properties={},legacy=false] (/112.198.172.246:15003) lost connection: Timed out

### Expected Behavior

the players claims to all be abandoned

### Reproduction steps

I cant find the initial server time out, however this has happened before with the same biome.

### Stack trace or error log

```shell
[05:01:46] [Server thread/INFO]: SaegusaMayumi issued server command: /abandonallclaims confirm
[05:01:49] [Craft Scheduler Thread - 507 - GriefPrevention/WARN]: [GriefPrevention] Plugin GriefPrevention v16.17.1-2b69191 generated an exception while executing task 310801
java.lang.NoSuchFieldError: DESERT_HILLS
	at me.ryanhamshire.GriefPrevention.RestoreNatureProcessingTask.getPlayerBlocks(RestoreNatureProcessingTask.java:835) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.lambda$getBiomeBlocks$0(AutoExtendClaimTask.java:78) ~[GriefPrevention.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getBiomeBlocks(AutoExtendClaimTask.java:78) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.getLowestBuiltY(AutoExtendClaimTask.java:57) ~[GriefPrevention.jar:?]
	at me.ryanhamshire.GriefPrevention.AutoExtendClaimTask.run(AutoExtendClaimTask.java:32) ~[GriefPrevention.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1456]
	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1456]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1456]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:03:38] [Craft Scheduler Thread - 508 - BuycraftX/INFO]: [BuycraftX] Fetching all due players...
[05:03:39] [Craft Scheduler Thread - 508 - BuycraftX/INFO]: [BuycraftX] Fetched due players (1 found).
[05:03:44] [Server thread/INFO]: com.mojang.authlib.GameProfile@36ae90ad[id=<null>,name=MiLKy563,properties={},legacy=false] (/112.198.172.246:15003) lost connection: Timed out
```

### Server version

```shell
[00:57:46 INFO]: Checking version, please wait...
[00:57:46 INFO]: This server is running Purpur version git-Purpur-1456 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7551c72 on HEAD)
[00:57:46 INFO]: You are 95 version(s) behind
Download the new version at: https://purpurmc.org/downloads
[00:57:46 INFO]: Previous version: git-Purpur-1445 (MC: 1.18.1)
```

### GriefPrevention version

```shell
[00:58:20 INFO]: GriefPrevention version 16.17.1-2b69191
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world_the_end: Disabled
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 50
    Max Accrued Claim Blocks:
      Default: 3000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 1
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8;
    DeathMessageCooldownSeconds: 10
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 10
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: true
```

### Plugin list

```shell
[00:59:31 INFO]: Plugins (47): AdvancedBan, AntiCheatReloaded, ArmorStandEditor, BetterRTP, BuycraftX, ChestShop, CMILib, CoreProtect, CrazyCrates, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExtraContexts, FarmControl, GameModeInventories, GriefPrevention, GSit, HeadDatabase, HolographicDisplays, HomeGUI, InventoryRollbackPlus, IPortal, ItemFilter*, Jobs, LuckPerms, mcMMO, MessageAnnouncer, MyCommand, NitroCommandBlocker*, NoNetherRoof, PlayerWarps, PlugManX (PlugMan), ProCosmetics, ProtocolLib, ServerListPlus*, SkQuery, Skript, StaffChatReloaded, SuperVanish, TAB, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
