### ISSUE TITLE
anyone in the server able to resize claims

### ISSUE THREAD

**Issue by Devansh120** [GriefPrevention/GriefPrevention#1840]
### Observed Behavior

untrusted players and anyone in the server able to resize anyone's claims and open chests and grief their items.

### Expected Behavior

no one should able to resize other players claims and no one can open chest and grief them

### Reproduction steps

1. take the shovel 
2. anyone could resize the claim
3. able to open chest inside the claim

### Server version

```shell
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-66 (MC: 1.17)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    small: -1
    shop: -1
    arena: -1
    manali: -1
    survivalhub: -1
    houses: -1
    Max-Mini_Games: -1
    hardcore: -1
    tntrunmap: -1
    mcplay: -1
    Maxworld: -1
    minigames: -1
    goa: -1
    nepal: -1
    tnt: -1
    delhi: -1
  Claims:
    Mode:
      minigames: Survival
      delhi: Survival
      arena: Survival
      tnt: Survival
      world: Survival
      Maxworld: Survival
      manali: Survival
      world_nether: Survival
      tntrunmap: Survival
      small: Survival
      shop: Survival
      houses: Survival
      world_the_end: Disabled
      nepal: Survival
      survivalhub: Survival
      Max-Mini_Games: Survival
      goa: Survival
      hardcore: Survival
      mcplay: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 150
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: WOODEN_SHOVEL
    Expiration:
      ChestClaimDays: 60
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: true
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 5
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please repeat again & again. Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: true
      world_the_end: true
      small: false
      shop: false
      arena: true
      manali: true
      survivalhub: false
      houses: true
      Max-Mini_Games: true
      hardcore: true
      tntrunmap: true
      mcplay: false
      Maxworld: true
      minigames: false
      goa: true
      nepal: true
      tnt: false
      delhi: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 5
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: true
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: true
      Debug: false
      Muted Chat Messages: false
```

### Plugin list

```shell
plugins: AdvancedBan, AntiXRay, AuthMe, Citizens, CleanroomGenerator, CoreProtect, DeluxeHub, Essentials, ExcellentShop, FarmProtect*, floodgate, GriefPrevention, GSit, HolographicDisplays, HolographicExtension, HubThat, ILibrary, Images, InventoryFullPlus, InvSeePlusPlus, KitPvP, Legacy, LuckPerms, Multiverse-Core, Multiverse-Inventories, MultiverseHardcore*, NBTAPI, NexEngine, NoPortals, Orebfuscator, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, RotatingHeads, ServersNPC, SheepQuest, SimpleHomes, SimplePolice, SimplePortals, SimpleTpa*, TAB, TabLock*, TDRPlaytime*, TNTRun_reloaded, ToolStats, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, Vulcan, WorldEdit, WorldGuard
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
