### ISSUE TITLE
LavaDumpingNearOtherPlayers not working

### ISSUE THREAD

**Issue by FrankHeijden** [GriefPrevention/GriefPrevention#188]
```
    AllowLavaDumpingNearOtherPlayers: false
```
Does not work, players can still use lava next to players who are in creative mode. Flint and steel is blocked, though.

GP 16.7.1
Spigot CraftBukkit version git-Spigot-5340a52-963b19c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by RoboMWM** [comment]
> Does not work, players can still use lava next to players who are in creative mode.

Interestingly, I have the opposite issue. This is always enabled on my creative server (where I disabled PvP rules). So... probably would be best to paste the rest of the config and perhaps any other test cases (and the world it is in).

**Comment by FrankHeijden** [comment]
I disabled every world for PvP, using it on a survival server.

```
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: false
    AllowFlintAndSteelNearOtherPlayers: false
    ProtectPetsOutsideLandClaims: true
```
