### ISSUE TITLE
Glass Not Connecting / Players get kicked for fly when being attacked in claims

### ISSUE THREAD

**Issue by Porzchee** [GriefPrevention/GriefPrevention#1881]
### Observed Behavior

https://medal.tv/games/minecraft/clips/m43UNRQIPYlWu/d1337ZvWT0gf?invite=cr-MSwxQU8sNTAyMTQwMDQs

When you punch someone in a claim it does this, which sometimes kicks them and then they die to combat log. 

The other issue is that glass won't connect in the claims either. 

### Expected Behavior

Players should be sent into combat but should not move like that when attacking.

Glass panes should connect. 

### Reproduction steps

?

### Server version

```shell
[22:11:26 INFO]: Current: git-Purpur-1551 (MC: 1.18.1)*
```

### GriefPrevention version

```shell
[22:09:22 INFO]: GriefPrevention version 16.18
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    Porzche: -1
    spawn: -1
    MobArenas1: -1
    MobArena: -1
    pvp: -1
  Claims:
    Mode:
      MobArenas1: Disabled
      pvp: Disabled
      world_nether: Disabled
      MobArena: Disabled
      world_the_end: Disabled
      world: Survival
      spawn: Disabled
      Porzche: Disabled
    PreventGlobalMonsterEggs: false
    PreventTheft: false
    ProtectCreatures: true
    PreventButtonsSwitches: false
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: false
    RaidTriggersRequireBuildTrust: false
    ProtectHorses: false
    ProtectDonkeys: false
    ProtectLlamas: false
    InitialBlocks: 500
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 50000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 0
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 50
    MinimumWidth: 10
    MinimumArea: 10
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 0
      UnusedClaimDays: 0
      AllClaims:
        DaysInactive: 14
        ExceptWhenOwnerHasTotalClaimBlocks: 0
        ExceptWhenOwnerHasBonusClaimBlocks: 0
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 2
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: false
  Spam:
    Enabled: true
    LoginCooldownSeconds: 10
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Shut the fuck up.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      Porzche: false
      spawn: true
      MobArenas1: false
      MobArena: false
      pvp: true
    ProtectFreshSpawns: false
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa /back /duel; /ec /enderchest /eec
      /eechest /eenderchest /espawn /eback /ehome;
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: false
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list

```shell
[22:10:23 INFO]: Plugins (67): AdvancedPortals, AntiBow, AuctionMaster, BeastWithdraw, BountyHunters, BungeeGuard, ChatItem, ChatReaction, Citizens, ClearLag, CoinFlipper*, CombatLogX, CoreProtect, CraftingStore, CustomHeads*, CustomItems, CustomUniverse, DrSleep, dtlTraders, Duels, EconomyShopGUI, EliteBosses, Essentials, EssentialsChat, EssentialsSpawn, EvenMoreFish, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, Graves, GriefPrevention, GSit, HarvesterPlus, HolographicDisplays, InventoryRollback, InvSeePlusPlus, LagAssist, LegacyKB*, LuckPerms, mcMMO, Multiverse-Core, Multiverse-Inventories, MyDog, PlayerKits, ProtocolLib, Quests, QuestsGUI, Sellwand, ServerlistMOTD*, ShulkerPacks, SilkSpawners, SirBlobmanCore (SirBlobmanAPI, XSeries), SkinsRestorer, Skript, SmallPets, StackMob, SuperVanish, TAB, TradeShop, Vault, Vehicles, VeinMiner, ViaVersion, VoidSpawn, VoidWorld*, Vulcan, WorldGuard, WorldGuardExtraFlags
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
