### ISSUE TITLE
Crystal Death 

### ISSUE THREAD

**Issue by M3rcena** [GriefPrevention/GriefPrevention#1934]
### Observed Behavior

Untrusted players go at the borders of the claims and when the claim owner comes close to the border of the claim they kill him with crystals.

### Expected Behavior

Claims should stop crystal damage to the player inside the claim.

### Reproduction steps

1. Someone is waiting right outside the claim with crystals
2. The Claim owner go closer but he is inside the claim
3. The untrusted user start blowing up crystals
4. The Claim owner dies from the crystals.

### Server version

```shell
[Thu 23:04:23 INFO ] This server is running Paper version git-Paper-33 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 147a2b7)
You are 48 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-29 (MC: 1.19)
```

### GriefPrevention version

```shell
[Thu 23:05:12 INFO ] GriefPrevention version 16.18
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    glads: -1
    update: -1
    newspawn: -1
    wars: -1
    map: -1
    Portals: -1
  Claims:
    Mode:
      newspawn: Survival
      map: Survival
      world_nether: Survival
      wars: Survival
      Portals: Survival
      world: Survival
      glads: Survival
      update: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 40
    Max Accrued Claim Blocks:
      Default: 100000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 40
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 30
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      glads: true
      update: true
      newspawn: true
      wars: true
      map: true
      Portals: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.5
    ClaimBlocksSellValue: 0.2
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list

```shell
[Thu 23:12:12 INFO ] ------------=[ ServerUtils Plugins ]=-------------
  [Thu 23:12:12 INFO ]  Plugins (90): AdvancedAchievements, AlonsoTags, AnimatedScoreboard, AntiDyeUse, ArmorStandTools, AuthMe, AutomaticBroadcast, BetterBackpacks, BetterRTP, Builders-Utilities, BungeeGuard, BungeeTabListPlus, BuycraftX, CMILib, ChangeSlots, Chunky, Citizens, ClearLag, CoreProtect, CustomCrafting, DeathMessages, DecentHolograms, DeluxeCoinflip, DeluxeMenus, DiscordSRV, EasyClearChat, EconomyShopGUI, EliteArmor, EliteLootbox, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ExcellentEnchants, ExecutableItems, FastAsyncWorldEdit, GSit, GriefPrevention, Harbor, HeadDatabase, InventoryRollbackPlus, Jobs, LibsDisguises, LuckPerms, MPChestRestock, MPUtils, MasterCooldowns, Multiverse-Core, NBTAPI, NametagEdit, NexEngine, NoEncryption, PL-Hide, PiggyAPI, PlaceholderAPI, PlayTime, PlayerBounties, PlayerWarps, ProtocolLib, PvPManager, Quests, QuickShop, RoseStacker, SCore, ServerUtils, Shopkeepers, SpigotHelpMe, StaffChat, SuperMobCoins, SuperVanish, TabTPS, TradeSystem, UltimateAutoRestart, UltimateClans, Vault, ViaBackwards, ViaVersion, VoidGen, Votifier, VotingPlugin, Vulcan, WolfyUtilities, WorldGuard, WorldGuardExtraFlags, ajLeaderboards, floodgate, mcMMO, spark, zAuctionHouse-Discord and zAuctionHouseV3
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [x] I attempted testing for the issue on a new server.
- [x] The issue still occurs on a new server.

### Using unmodified client

- [x] I attempted testing for the issue with the vanilla client.
- [x] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
