### ISSUE TITLE
Claim visualization doesn't work beyond 75 blocks

### ISSUE THREAD

**Issue by Bobcat00** [GriefPrevention/GriefPrevention#2023]
### Observed Behavior

This is likely a side effect of #1987 and possibly #2008 

If you click on a claim with a stick from a distance of more than 75 blocks, the visualization is not shown. OK, it's probably always been like that. But now if you move closer to the claim, even inside the claim, and click again, the visualization isn't shown. You need to click somewhere else, then click back inside the claim to see the visualization.

This also occurs with large claims, where only part of the boundary is shown. If you move to the end of the visualization and click again, the visualization is not extended. Again, you need to click somewhere else and then back inside the claim to see the visualization.

### Expected Behavior

It would be nice if clicking inside a claim would show the additional claim boundary visualization if it was not already shown.

But I'm not sure if it's worthwhile to change this. Once you realize what's happening, it's not too bad to click outside the claim and then inside again.

### Reproduction steps

Click on distant claims or large claims as described in _Observed Behavior_.

### Stack trace or error log

```shell
N/A
```

### Server version

```shell
Paper version git-Paper-466 (MC: 1.19.4)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.1
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    LanaPug: -1
    LanaPug_nether: -1
    LanaPug_the_end: -1
    LanaPug17: -1
    plotworld: -1
    LanaPug17_nether: -1
    LanaPug17_the_end: -1
  Claims:
    Mode:
      LanaPug17: Survival
      LanaPug_the_end: Disabled
      LanaPug: Survival
      LanaPug_nether: Survival
      LanaPug17_the_end: Disabled
      plotworld: Disabled
      LanaPug17_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 15
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 550
        ExceptWhenOwnerHasTotalClaimBlocks: 200000
        ExceptWhenOwnerHasBonusClaimBlocks: 40000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 3
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 0
    ChatSlashCommands: /me;/tell;/global;/local;/tpa;/tpask;/tpahere;/call
    WhisperSlashCommands: /tell;/pm;/r
    WarningMessage: Spamming is prohibited.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      LanaPug: false
      LanaPug_nether: false
      LanaPug_the_end: false
      LanaPug17: false
      plotworld: false
      LanaPug17_nether: false
      LanaPug17_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 560
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: true
      Administrative Activity: true
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
AltDetector 2.01
AutoBot 1.01
BetterSeen 1.02
Essentials 2.20.0-dev+45-bf14b88
EssentialsChat 2.20.0-dev+45-bf14b88
EssentialsGeoIP 2.20.0-dev+45-bf14b88
EssentialsSpawn 2.20.0-dev+45-bf14b88
FarmLimiter 1.5.3
FastAsyncWorldEdit 2.6.1-SNAPSHOT
FreedomChat 1.4.1
GriefPrevention 16.18.1
GriefPreventionBlockedCommands 1.0
ImageMaps 1.0.10
IronDoors 1.8b
LimitDrops 1.02
LuckPerms 5.4.40
MemCheck 1.03
MinecartCollisions 2.03
MobArena 0.107
Multiverse-Core 4.3.1-b861
Multiverse-NetherPortals 4.2.1-b786
Multiverse-Portals 4.2.1-b834
NoCheatPlus 3.17.1-SNAPSHOT-Updated-b153
Orebfuscator 5.3.3
PlotSquared 6.11.1
PlotWelcome 0.01
Prism 3.7.0-SNAPSHOT
ProtocolLib 5.0.0-SNAPSHOT-b616
PwnFilter 3.1.2b
SignURLs 1.0.5a
SilkSpawners 7.3.1-SNAPSHOT-b${BUILD_NUMBER}
SilkSpawnersShopAddon 3.0.3
TabListPing 2.00-SNAPSHOT
Vault 1.7.3-b131
ViaBackwards 4.6.1
ViaRewind 2.0.3
ViaVersion 4.6.1
ViaVersionStatus 3.14-SNAPSHOT
WallClock 0.2.2f
WorldGuard 7.0.7+216b061
xInventories 2.5a
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
