### ISSUE TITLE
API lagging and crashing out my server

### ISSUE THREAD

**Issue by matipoirierg** [GriefPrevention/GriefPrevention#2061]
### Observed Behavior

I'm using a pl3xmap claim addon to show claims on the map, the server starts lagging and eventually get a crash.

### Expected Behavior

Server should run without performance issues.

### Reproduction steps

git-Purpur-1990 (MC: 1.20)*
Pl3xMap version 1.20-441
Pl3xMap Claims 1.20-23
https://spark.lucko.me/ckTP2GUleG
I uninstalled the add-on and the server goes back to normal behavior.

### Stack trace or error log

```shell
Crash error: https://mclo.gs/uMkV8U5
```

### Server version

```shell
git-Purpur-1990 (MC: 1.20)*
Pl3xMap version 1.20-441
Pl3xMap Claims 1.20-23
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.1
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: 256
    world_nether: -1
    world_the_end: -1
    Hub: -1
    Arena: -1
    Farming: -1
  Claims:
    Mode:
      world_the_end: Disabled
      Arena: Disabled
      world: Survival
      Hub: Disabled
      world_nether: Disabled
      Farming: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1024
    Claim Blocks Accrued Per Hour:
      Default: 64
    Max Accrued Claim Blocks:
      Default: 51200
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 90
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 99999
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      Hub: true
      Arena: true
      Farming: true
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: true
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 12.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
Paper Plugins: (1):
[14:15:01 INFO]:  - Minepacks
[14:15:01 INFO]: Bukkit Plugins: (85):
[14:15:01 INFO]:  - AdvancedPortals, AdvancedRegionMarket, AngelChest, AnnouncerPlus, AntiRaidFarm, ArmorStandTools, Astro, BeastCore, BeastWithdraw, BetterRTP
[14:15:01 INFO]:  BlockParticles, ChatSentry, ChestSort, Chunky, ClaimFly, CMILib, *CommandPerWorldBlocker, CoreProtect, CrazyCrates, CustomFishing
[14:15:01 INFO]:  CyberWorldReset, DecentHolograms, DeluxeCombat, DeluxeMenus, DiscordSRV, EasyCommandBlocker, eGlow, Essentials, EssentialsProtect, EssentialsSpawn
[14:15:01 INFO]:  EZRanksPro, FarmLimiter, FastAsyncWorldEdit, FreedomChat, GlobalGamerules, GriefPrevention, GSit, Harbor, HeadDatabase, HexNicks
[14:15:01 INFO]:  InteractiveBooks, InteractiveChat, InventoryRollbackPlus, InvisibleItemFrames, ItemsAdder, JetsAntiAFKPro, Jobs, LiteBans, LoneLibs, LPC
[14:15:01 INFO]:  LuckPerms, mcMMO, MineStore, Multiverse-Core, Multiverse-NetherPortals, MyCommand, OpenInv, PetNameFix, PetTeleport, PhantomSMP
[14:15:01 INFO]:  PinataParty, Pl3xMap, PlaceholderAPI, PlayerWarps, ProtocolLib, qscompat-advancedregionmarket, Quests, QuickShop-Hikari, Shopkeepers, spark
[14:15:01 INFO]:  StoreStats, SuperLuckyBlock, TAB, TradeSystem, UltimateAutoRestart, VanishNoPacket, Vault, ViaBackwards, ViaVersion, VoidGen
  Votifier, WorldGuard, WorldGuardExtraFlags, XCatch, zAuctionHouseV3
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
