### ISSUE TITLE
Giving Claim Blocks To Users Who Vote With GAlistener

### ISSUE THREAD

**Issue by ArhamR** [GriefPrevention/GriefPrevention#217]
Hi, i am setting up GAlistener and was wondering if there was a a way to get GAlistener to give the user who voted 100 claim blocks, if so what would the command be??

Thank You

**Comment by bigpresh** [comment]
The command you'd want to run is `/AdjustBonusClaimBlocks playername +100`

Skimming GAListener's docs, it looks like you can use `{username}` which will be replaced with their username, so you should be able to say:
```yml
    commands: 
    - '/AdjustBonusClaimBlocks {username} +100'
```

For reference (and anyone who finds this issue by Googling for ways to give claim blocks as rewards for voting), I use VoteRoulette to give randomised rewards, and the claim-block-providing rewards in my awards.yml look like:

```yml
    250 Claim Blocks:
        commands:
        - /AdjustBonusClaimBlocks %player% +250
        message: "Expand your empire by 250 blocks thanks to your vote!"
```
