### ISSUE TITLE
Player unable to expand claim

### ISSUE THREAD

**Issue by Bluzbur** [GriefPrevention/GriefPrevention#2215]
### Observed Behavior

When a player tries to expand their claim, it gives the obstruction issue - We have gone around the area and able to make claims where there's supposedly to be obstruction. - this issue has only been happening with one player afaik.

### Expected Behavior

They should be able to use the command /expandclaim 1 and the claim should expand in the direction they're looking.

### Reproduction steps

We actually converted from GD to GP so the steps would be
1. Convert data back to GP
2. Stand on the border of claim
3. try expandclaim 1 and recieve overlap error

### Stack trace or error log

```shell
No error logs
```

### Server version

```shell
Current: git-Purpur-2124 (MC: 1.20.4)*
Previous: git-Pufferfish-3 (MC: 1.20.1)
* You are 17 version(s) behind
Download the new version at: https://purpurmc.org/downloads
```

### GriefPrevention version

```shell
Version da38fbd
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    resources_nether: -1
    Envoy: -1
    surv-build: -1
    resources: -1
    Spawn: -1
  Claims:
    Mode:
      Spawn: Survival
      world_nether: Disabled
      resources: Survival
      Envoy: Survival
      resources_nether: Disabled
      world: Survival
      surv-build: Survival
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be Muted.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      resources_nether: true
      Envoy: true
      surv-build: true
      resources: true
      Spawn: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GLASS_PANE
    - LIME_WOOL
    - GRAVEL
    - BLUE_WOOL
    - CYAN_WOOL
    - RED_WOOL
    - BIRCH_PLANKS
    - DEAD_BUSH
    - GREEN_WOOL
    - ACACIA_PLANKS
    - COBBLESTONE
    - DIRT
    - SAND
    - LIGHT_BLUE_WOOL
    - ORANGE_WOOL
    - FERN
    - PINK_WOOL
    - BLACK_WOOL
    - BROWN_WOOL
    - JUNGLE_PLANKS
    - SHORT_GRASS
    - PURPLE_WOOL
    - WHITE_WOOL
    - YELLOW_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - GRASS_BLOCK
    - OAK_PLANKS
    - SNOW
    - MAGENTA_WOOL
    - GLASS
    - SPRUCE_PLANKS
    - DARK_OAK_PLANKS
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: true
  BanCommandPattern: litebans:ban %name% AutoBan
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
Plugins (86): AdvancedChests, AdvancedEnchantments, AntiPopup, BCommons, BattlePass, BetterPing, BetterRTP, BlockLocker, BlurCraftStore, BungeeGuard, CMILib, Chunky, Citizens, CommandWhitelist, CoreProtect, CrazyEnvoys, DecentHolograms, DeluxeTags, DiscordSRV, EZColors, EconomyShopGUI, EliteArmor, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ExecutableBlocks, ExecutableEvents, ExecutableItems, FarmLimiter, FastAsyncWorldEdit, GDConverter, GPFlags, GSit, GUIPlus, GriefPrevention, Harbor, HeadDatabase, HeadsPlus, Infiniteannouncements, Insights, Jobs, KixsChatGames, LibsDisguises, LiteBans, LuckPerms, Minepacks, Multiverse-Core, NBTAPI, NexEngine, Oraxen, PinataParty, Pl3xMap, PlaceholderAPI, Plan, PlayerParticles, PlayerStats, PlayerWarps, ProtocolLib, QuickShop, RewardsLite, SCore, Sellwand, ServerUtils, Shopkeepers, SignedVelocity, SimpleClans, StackMob, TAB, TempFly, TimedRewards, TogglePvp, UpgradeableHoppers, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, Votifier, WildStacker, WorldGuard, WorldGuardExtraFlags, floodgate, mcMMO, spark and zAuctionHouseV3
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
