### ISSUE TITLE
Latest update causing severe performance issues with wildstacker/GPflags installed

### ISSUE THREAD

**Issue by alek4032** [GriefPrevention/GriefPrevention#2249]
### Observed Behavior

Hey.

We're experiencing severe tps issues after installing the latest version of Griefprevention. I'll attach 2 different spark reports and they'll both show how Wildstacker and Gpflags is using a lot more server thread for me.ryanhamshire.GriefPrevention.DataStore.getClaim()

We haven't modified anything else for the plugin other than the update, and there also has not been any kind of spike in claimflags used or something like that from what we can tell. 

We've never had this issue previously before we did the update and would really appreciate if there's a way we can resolve it.

### Expected Behavior

All plugins going back to using the normal of server thread (which has never been anywhere near this before)

### Reproduction steps

1: Install Griefprevention
2: Install Wildstacker (Build 2023.3-b34)
3: Install latest version of GPflags (5.12.10)
4: Have them fun for a while with a lot of players on interacting with the claims as they usually do.

### Stack trace or error log

```shell
There is no stack trace or error log but here's 2 different spark reports showing the issue appearing:


https://spark.lucko.me/k7fkPwkde2

and another one that was made later

https://spark.lucko.me/IUf9oBevg9
```

### Server version

```shell
[21:29:33 INFO]: This server is running Pufferfish+ version git-PufferfishPlus-"a9f972b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a9f972b on HEAD)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.2
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: 256
    world_the_end: -1
    resources: -1
    newspawn: -1
  Claims:
    Mode:
      resources: Disabled
      world_the_end: Disabled
      world_nether: Survival
      newspawn: Survival
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 2000
    Claim Blocks Accrued Per Hour:
      Default: 75
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -64
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome;/pw set;/sign edit;/sign clear;/sign paste;/sign
      set;/editsign;/editsign set;/editsign clear;/editsign copy;/editsign paste
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level. Check /rules for further details
    BanOffenders: false
    BanMessage: Kicked for spam. Please refer to the rules in our discord https://discord.gg/pixelblock
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      resources: true
      newspawn: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: true
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
[21:27:21 INFO]: Paper Plugins:
[21:27:21 INFO]:  - EconomyShopGUI, Minepacks
[21:27:21 INFO]: Bukkit Plugins:
[21:27:21 INFO]:  - AdvancedChests, AdvancedEnchantments, AlexManager, ArmorStandEditor, BattlePass, *BCommons, BetterRTP, BungeeGuard, BuycraftX, ClueScrolls
[21:27:21 INFO]:  CommandWhitelist, CoreProtect, CrazyEnvoys, CustomDecentHolograms, DailyRewardsPlus, DecentHolograms, DeluxeCoinflip, DiscordSRV, Duels, EliteArmor
[21:27:21 INFO]:  EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ExecutableBlocks, ExecutableItems, FancyNpcs, FarmLimiter, GriefPrevention
[21:27:21 INFO]:  GSit, GUIPlus, Harbor, HeadDatabase, Insights, InteractiveChat, InventoryRollbackPlus, InvSeePlusPlus, LibsDisguises, LiteBans
[21:27:21 INFO]:  LuckPerms, mcMMO, MCPets, MobLimit, ModelEngine, Multiverse-Core, MythicCrucible, MythicMobs, NexEngine, PBBlockLocker
[21:27:21 INFO]:  PBGPFlagManager, PBManager, PBNotifier, PBPackLoader, PinataParty, PlaceholderAPI, Plan, PlayerVaults, PlayerWarps, PlugManX
[21:27:21 INFO]:  ProCosmetics, ProtocolLib, PyroFishingPro, PyroLib, Quests, QuickShop, SCore, Shopkeepers, SimpleClans, SimplePortals
[21:27:21 INFO]:  spark, TAB, TempFly, TogglePvp, TradeSystem, UpgradeableHoppers, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks
[21:27:21 INFO]:  VoidGen, Votifier, WildBuster, WildChests, WildStacker, WildTools, WordFilter, WorldEdit, WorldGuard, WorldGuardExtraFlags
[21:27:21 INFO]:  zAuctionHouseV3
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
