### ISSUE TITLE
Can't Enable main world to claim

### ISSUE THREAD

**Issue by projectctjerqo** [GriefPrevention/GriefPrevention#2274]
### Observed Behavior

![601b141df71d426a362f5ded6e10b7ff](https://github.com/GriefPrevention/GriefPrevention/assets/129528561/1b946e2c-8195-4066-9081-f7d57428f7e3)
![90b9fa4d5142f6fc4c068fe00875c275](https://github.com/GriefPrevention/GriefPrevention/assets/129528561/1d9abfd2-afac-4276-95c6-103ba16e8cae)

  Claims:
    Mode:
      world_nether: Disabled
      Island: Disabled
      LeaderBoards: Disabled
      Resource: Disabled
      ResourceEnd: Disabled
      world_the_end: Disabled
      Spawn: Disabled
      normal_flat: Survival
      Boss-Arena: Disabled
      End: Survival
      Nether: Survival
      world: Disabled
      ender_arena: Survival
      ResourceNether: Disabled
      backrooms: Disabled
      Main: Survival

### Expected Behavior

to be able to claim

### Reproduction steps

world doesn't populate in config, so I add it and then I restart server then error.

### Server version

```shell
paper-1.20.4-462.jar
```

### GriefPrevention version

```shell
version 16.18.2
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    Nether: -1
    Resource: -1
    Island: -1
    LeaderBoards: -1
    backrooms: -1
    Spawn: -1
    Boss-Arena: -1
    ResourceEnd: -1
    normal_flat: -1
    ender_arena: -1
    End: -1
    ResourceNether: -1
    Main: -1
  Claims:
    Mode:
      world_nether: Disabled
      Island: Disabled
      LeaderBoards: Disabled
      Resource: Disabled
      ResourceEnd: Disabled
      world_the_end: Disabled
      Spawn: Disabled
      normal_flat: Survival
      Boss-Arena: Disabled
      End: Survival
      Nether: Survival
      world: Disabled
      ender_arena: Survival
      ResourceNether: Disabled
      backrooms: Disabled
      Main: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      Nether: true
      Resource: true
      Island: true
      LeaderBoards: false
      backrooms: true
      Spawn: false
      Boss-Arena: true
      ResourceEnd: true
      normal_flat: true
      ender_arena: true
      End: true
      ResourceNether: true
      Main: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - SPRUCE_PLANKS
    - YELLOW_WOOL
    - LIGHT_BLUE_WOOL
    - BLACK_WOOL
    - SAND
    - DEAD_BUSH
    - FERN
    - CYAN_WOOL
    - BROWN_WOOL
    - DIRT
    - LIGHT_GRAY_WOOL
    - ORANGE_WOOL
    - BLUE_WOOL
    - GREEN_WOOL
    - GLASS_PANE
    - COBBLESTONE
    - JUNGLE_PLANKS
    - WHITE_WOOL
    - LIME_WOOL
    - BIRCH_PLANKS
    - ACACIA_PLANKS
    - GLASS
    - PURPLE_WOOL
    - SNOW
    - GRAVEL
    - RED_WOOL
    - GRASS_BLOCK
    - PINK_WOOL
    - MAGENTA_WOOL
    - GRAY_WOOL
    - SHORT_GRASS
    - OAK_PLANKS
    - DARK_OAK_PLANKS
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
