### ISSUE TITLE
Using buttons in other people's claims

### ISSUE THREAD

**Issue by Nathanman07** [GriefPrevention/GriefPrevention#2302]
### Observed Behavior

Untrusted players can shoot bows at buttons in order to trigger them in claims they aren't trusted in.

### Expected Behavior

The arrow shouldn't trigger the button, rather it should say "you cannot use this!" once.

### Reproduction steps

1. Get a bow and arrow
2. Shoot it at a button in someone else's claim
3. The button will trigger

### Server version

```shell
This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.3
```

### Configuration

```yaml
GriefPrevention:
  SeaLevelOverrides:
    Survival: -64
    Survival_nether: -1
    Survival_the_end: -1
    SurvivalShop: -1
    AFK: -1
    KitPVP: -1
    Minigames: -1
    Creative: -1
    Lobby: -1
    BuildNet: -1
  Claims:
    Mode:
      KitPVP: Disabled
      BuildNet: Disabled
      SurvivalShop: Disabled
      Creative: Disabled
      Survival: Survival
      Lobby: Disabled
      Survival_nether: Survival
      Survival_the_end: Survival
      AFK: Disabled
      Minigames: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 31250
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 25
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: WOODEN_SHOVEL
    Expiration:
      ChestClaimDays: 30
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 30
        ExceptWhenOwnerHasTotalClaimBlocks: 150000
        ExceptWhenOwnerHasBonusClaimBlocks: 150000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 10
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome;/pw set
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Spamming is not allowed on this server.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Survival: true
      Survival_nether: true
      Survival_the_end: true
      SurvivalShop: true
      AFK: false
      KitPVP: false
      Minigames: false
      Creative: true
      Lobby: false
      BuildNet: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/warp;/spawn;/fly;/god;/survivalspawn;/tp;/skyblockspawn;/creativespawn;/kitpvpspawn;/villagedefensespawn;/spawnsurvival;/spawnskyblock;/spawncreative;/spawnkitpvp;/spawn;
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 31250
    ClaimBlocksPurchaseCost: 2.0
    ClaimBlocksSellValue: 1.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: false
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS     <-- can't understand this entry, see BukkitDev documentation
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 90
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
- AntiAC, AuctionHouse, BlockLocker, BuycraftX, ChatControl, ChatFree, Citizens, ClearLag, CoreProtect, DiscordSRV, Essentials, EssentialsChat, FastAsyncWorldEdit, GadgetsMenu, GriefPrevention, GrimAC, GSit, Guilds, Harbor, HolographicDisplays, IllegalStack, KitPvP, LibsDisguises, LPC, LuckPerms, mcMMO, MinehutPlugin, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, PlaceholderAPI, PlayerVaults, PlayerWarps, PlotSquared, PlugManX, ProtocolLib, SilkSpawners, SkBee, Skellett, SkQuery, skRayFall, Skript, skript-gui, skript-placeholders, TAB, TradeSystem, Vault, VeinMiner, ViaBackwards
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
