### ISSUE TITLE
Can You disable in certain worlds?

### ISSUE THREAD

**Issue by DJChicken66** [GriefPrevention/GriefPrevention#231]
Is it possible to disable grief prevention in certain worlds? I have a survival and creative world and I dont want claiming in the creative. Can I do this?

**Comment by bigpresh** [comment]
Yes - see Claims -> Mode in the config.

e.g.:

```
Claims:
  Mode:
    world: Survival
    creative_world: Disabled
```
