### ISSUE TITLE
Item Frames can be broken, items stolen in ver 16.18.4

### ISSUE THREAD

**Issue by FourNineRugz** [GriefPrevention/GriefPrevention#2343]
### Observed Behavior

Item Frames can be broken, items stolen and rotated in ver 16.18.4. No way to toggle this anywhere?

### Expected Behavior

Item Frames should not be broken, or items stolen.

### Reproduction steps

Item Frames can be broken, items stolen in ver 16.18.4

### Server version

```shell
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-105-7e91a2c (MC: 1.21)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    New: -1
    New_nether: -1
    New_the_end: -1
    ResourceNether: -1
    TheLobby: -1
    Pinata: -1
    Resource: -1
    NewBucketry: -1
    ResourceEnd: -1
    em_adventurers_guild: -1
    Spawn: -1
    Flatworld: -1
  Claims:
    Mode:
      Flatworld: Disabled
      ResourceNether: Disabled
      em_adventurers_guild: Survival
      Spawn: Disabled
      New_nether: Survival
      Pinata: Disabled
      TheLobby: Disabled
      New: Survival
      New_the_end: Survival
      NewBucketry: Disabled
      Resource: Disabled
      ResourceEnd: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 1000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      New: true
      New_nether: true
      New_the_end: true
      ResourceNether: true
      TheLobby: true
      Pinata: true
      Resource: true
      NewBucketry: true
      ResourceEnd: true
      em_adventurers_guild: true
      Spawn: false
      Flatworld: true
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 1.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - SHORT_GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
[05:08:21 INFO]:  - AdvancedChests, AdvancedEnchantments, AfkPool, ajLeaderboards, AuraMobs, AuraSkills, AxTrade, BetterStructures, BlueBridgeCore, BlueMap
[05:08:21 INFO]:  BottledExp, BreweryX, bSoul, BuildersWand, ChatControlRed, ChatFeelings, ChestSort, Chunky, Citizens, CitizensCMD
[05:08:21 INFO]:  CMI, CMILib, CoinsEngine, CoreProtect, CraftingStore, CrazyEnvoys, DailyRewards, DarkAuctionsX, DecentHolograms, DeluxeMenus
[05:08:21 INFO]:  DeluxeTags, DiscordSRV, DiscordSRV-Staff-Chat, Elevator, EntityDetection, ExcellentCrates, ExecutableItems, floodgate, GPExtension, GPFlags
[05:08:21 INFO]:  Graves, GriefPrevention, GSit, HaoNick, HeadDatabase, ImageFrame, InteractiveChat, InventoryRollbackPlus, InvisibleItemFrames, Jobs
[05:08:21 INFO]:  JukeBox, KixsChatGames, LoneLibs, LuckPerms, Multiverse-Core, NexEngine, nightcore, NoteBlockAPI, Oraxen, PinataParty
[05:08:21 INFO]:  PlaceholderAPI, PlayerAuctions, PlayerVaults, PlayerWarps, PluginManager, ProtectionLib, ProtocolLib, PyroFarming, PyroFishingPro, PyroLib
[05:08:21 INFO]:  PyroMining, Quests, QuickShop-Hikari, Rankup, RHLeafDecay, SafariNet, SCore, ServerTutorialPlus, SimplePets, TAB
[05:08:21 INFO]:  TempFly, UpgradeableHoppers, Vault, Vegas, ViaBackwards, ViaVersion, *VoidWorld, VoteRewards, Votifier, WanderingTrades
[05:08:21 INFO]:  WorldEdit, WorldGuard, WorldGuardExtraFlags, XenoWorldReset, XLTournaments
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
