### ISSUE TITLE
Issue with claim

### ISSUE THREAD

**Issue by Reelx69** [GriefPrevention/GriefPrevention#2344]
### Observed Behavior

Some player unclaimed and reclaimed their land to resize it but now they cant trust anyone

https://github.com/user-attachments/assets/8304eaa6-0c9c-497f-89bf-8707ba60de34

![image](https://github.com/user-attachments/assets/629d1f61-4321-4364-913c-d02c679a27a7)
![image](https://github.com/user-attachments/assets/8e3a69de-0e8b-4f22-81b1-97175eefefa1)

### Expected Behavior

Here is what happened, player tried to unclaim then reclaim their land to make it bigger and now they can't trust anyone

### Reproduction steps

Check the video above

### Stack trace or error log

```shell
Could not find logs due to the server is large and i could not find anything in the logs
```

### Server version

```shell
This server is running Pufferfish version git-Pufferfish-47 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9d12215 on HEAD)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.2
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    spawn: -1
    arena: -1
  Claims:
    Mode:
      world_the_end: Disabled
      arena: Survival
      world: Survival
      world_nether: Disabled
      spawn: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 50
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 100
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -64
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      spawn: true
      arena: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  VisualizationAntiCheatCompatMode: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: -1
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS     <-- can't understand this entry, see BukkitDev documentation
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
[14:14:51 INFO]: Paper Plugins:
[14:14:51 INFO]:  - AdvancedKits, GPExtension, RoseStacker, UltimateMobCoins
[14:14:51 INFO]: Bukkit Plugins:
[14:14:51 INFO]:  - AdvancedEnchantments, AdvancedJobs, ajParkour, AlonsoTags, AxGraves, BetterRTP, BetterTeams, ChatSentry, Chunky, Citizens
[14:14:51 INFO]:  CrazyCrates, CrazyEnvoys, CrazyVouchers, *CustomRankPrefix, DecentHolograms, DeluxeAnnounce, DeluxeCoinflip, DeluxeCombat, DeluxeMenus, eco
[14:14:51 INFO]:  EcoSkills, eGlow, Essentials, EssentialsSpawn, *Everest, ExcellentCrates, EZColors, FastAsyncWorldEdit, FastClearLag, GoldShop
[14:14:51 INFO]:  GPFlags, GriefPrevention, HeadDatabase, Images, InteractiveBooks, InvisibleItemFrames, ItemsAdder, KitPreview, KixsChatGames, libreforge
[14:14:51 INFO]:  LiteBans, LoneLibs, LPC, LPX, LuckPerms, Multiverse-Core, MyCommand, NBTAPI, NexEngine, PlaceholderAPI
[14:14:51 INFO]:  PlayerPoints, PlayerVaults, PlayerWarps, ProtocolLib, Quests, QuickShop, SafariNet, Sellwand, ShopGUIPlus, ShopGUIPlus-SellGUI
[14:14:51 INFO]:  SimpleAnnounce, SimplePortals, spark, *STN-Studios-API, SuperCredits, *SuperVotes, TAB, Tebex, TitleManager, ToastedAFK
[14:14:51 INFO]:  Unpumpkin, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, Votifier, Vulcan, WorldGuard, WorldGuardExtraFlags
[14:14:51 INFO]:  XLTournaments, zAuctionHouseV3, zKoth
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
