### ISSUE TITLE
ERROR: Could not pass event AsyncPlayerChatEvent to GriefPrevention v16.18.4

### ISSUE THREAD

**Issue by luquib02** [GriefPrevention/GriefPrevention#2350]
### Observed Behavior

Sometimes console logs show this, not shure what specifically triggers this. Might be causing performance issues.
Happens when someone talks in chat

### Expected Behavior

Shouldn't say anything in console.

### Reproduction steps

1. Type something in chat
2. profit

### Stack trace or error log

```shell
https://gist.github.com/luquib02/75d4988406fa9e8cd7fb01611c4d67b4
```

### Server version

```shell
This server is running Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-123-0a1be9a (MC: 1.21)
```

### GriefPrevention version

```shell
16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    em_primis: -1
    em_primis_wormhole: -1
    em_fireworks: -1
    em_shadow_of_the_binder_of_worlds: -1
    em_beasts_sanctuary: -1
    em_invasion: -1
    em_north_pole: -1
    em_the_pirate_ship: -1
    em_diamond_arena: -1
    em_adventurers_guild: -1
    em_knight_castle: -1
    em_iron_league_arena: -1
    em_oasis: -1
    em_oasis_wormhole: -1
  Claims:
    Mode:
      em_adventurers_guild: Survival
      em_iron_league_arena: Survival
      em_primis: Survival
      em_primis_wormhole: Survival
      em_knight_castle: Survival
      world_nether: Disabled
      em_oasis_wormhole: Survival
      world_the_end: Disabled
      em_north_pole: Survival
      em_diamond_arena: Survival
      em_beasts_sanctuary: Survival
      em_fireworks: Survival
      em_oasis: Survival
      em_the_pirate_ship: Survival
      world: Survival
      em_shadow_of_the_binder_of_worlds: Disabled
      em_invasion: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 10
    Claim Blocks Accrued Per Hour:
      Default: 5
    Max Accrued Claim Blocks:
      Default: -1530494977
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 0.8
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Estás spammeando mucho, bajale o te vas baneado.
    BanOffenders: true
    BanMessage: Baneado por spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      em_primis: true
      em_primis_wormhole: true
      em_fireworks: true
      em_shadow_of_the_binder_of_worlds: true
      em_beasts_sanctuary: true
      em_invasion: true
      em_north_pole: true
      em_the_pirate_ship: true
      em_diamond_arena: true
      em_adventurers_guild: true
      em_knight_castle: true
      em_iron_league_arena: true
      em_oasis: true
      em_oasis_wormhole: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 50.0
    ClaimBlocksSellValue: 25.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - COBBLESTONE
    - ORANGE_WOOL
    - WHITE_WOOL
    - RED_WOOL
    - SNOW
    - FERN
    - GRASS_BLOCK
    - GLASS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - MAGENTA_WOOL
    - BLUE_WOOL
    - BLACK_WOOL
    - DIRT
    - CYAN_WOOL
    - LIGHT_BLUE_WOOL
    - GRAY_WOOL
    - SAND
    - LIME_WOOL
    - BIRCH_PLANKS
    - SPRUCE_PLANKS
    - BROWN_WOOL
    - DEAD_BUSH
    - OAK_PLANKS
    - YELLOW_WOOL
    - JUNGLE_PLANKS
    - SHORT_GRASS
    - GLASS_PANE
    - GRAVEL
    - LIGHT_GRAY_WOOL
    - PURPLE_WOOL
    - GREEN_WOOL
    - PINK_WOOL
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
[14:11:06 INFO]: Server Plugins (46):
[14:11:06 INFO]: Paper Plugins:
[14:11:06 INFO]:  - EconomyShopGUI, Minepacks
[14:11:06 INFO]: Bukkit Plugins:
[14:11:06 INFO]:  - AntiPopup, ArmoredElytra, AuraSkills, BetterRTP, BetterStructures, BetterTeams, Chunky, ClaimSales, CMILib, DailyRewardsPlus
[14:11:06 INFO]:  EliteMobs, Essentials, EssentialsChat, FancyPhysics, FastAsyncWorldEdit, floodgate, FreeMinecraftModels, Geyser-Spigot, GriefPrevention, GSit
[14:11:06 INFO]:  InsaneAnnouncer, LibsDisguises, LuckPerms, nLogin, NotBounties, packetevents, PlaceholderAPI, ProtocolLib, ResourcePackManager, ServerTap
[14:11:06 INFO]:  SkinsRestorer, TAB, Tebex, TerraformGenerator, Themis, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, ViaVersionStatus
[14:11:06 INFO]:  VirtualBooks, WorldGuard, WorldGuardExtraFlags, zDiscord
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
