### ISSUE TITLE
Claims suddenly disappears

### ISSUE THREAD

**Issue by giomiracle123** [GriefPrevention/GriefPrevention#2351]
### Observed Behavior

![image](https://github.com/user-attachments/assets/7872ac81-6774-455d-bbcd-a883b3949698)
![image](https://github.com/user-attachments/assets/02dbf4dd-334c-44a2-b68e-3a0d7dd4a16f)

### Expected Behavior

Many players in my server are experincing claims suddenly disappears even if they are active players. 

### Reproduction steps

I cant make a reproduction step since this glitch are random and players are just reporting that their claims are gone and theyalready got griefed

### Server version

```shell
[02:24:12 INFO]: This server is running Paper version 1.21-81-master@ceeb8c1 (2024-07-17T00:39:18Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 45 version(s) behind
```

### GriefPrevention version

```shell
[02:24:47 INFO]: GriefPrevention version 16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    ffa: -1
    spawn: -1
    AFK: -1
    arena: -1
  Claims:
    Mode:
      spawn: Disabled
      world_nether: Disabled
      arena: Survival
      world: Survival
      AFK: Survival
      world_the_end: Disabled
      ffa: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 500
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 10000000
      UnusedClaimDays: 10000000
      AllClaims:
        DaysInactive: 1000000
        ExceptWhenOwnerHasTotalClaimBlocks: 100000
        ExceptWhenOwnerHasBonusClaimBlocks: 100000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      ffa: true
      spawn: true
      AFK: true
      arena: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - PINK_WOOL
    - GLASS
    - BLUE_WOOL
    - BIRCH_PLANKS
    - ACACIA_PLANKS
    - DEAD_BUSH
    - YELLOW_WOOL
    - ORANGE_WOOL
    - GLASS_PANE
    - GRASS_BLOCK
    - DARK_OAK_PLANKS
    - DIRT
    - LIME_WOOL
    - LIGHT_GRAY_WOOL
    - COBBLESTONE
    - BLACK_WOOL
    - SAND
    - GRAY_WOOL
    - OAK_PLANKS
    - BROWN_WOOL
    - SPRUCE_PLANKS
    - PURPLE_WOOL
    - GRASS     <-- can't understand this entry, see BukkitDev documentation
    - JUNGLE_PLANKS
    - RED_WOOL
    - MAGENTA_WOOL
    - FERN
    - GREEN_WOOL
    - CYAN_WOOL
    - WHITE_WOOL
    - LIGHT_BLUE_WOOL
    - GRAVEL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
[02:25:28 INFO]: Paper Plugins:
[02:25:28 INFO]:  - RoseStacker
[02:25:28 INFO]: Bukkit Plugins:
[02:25:28 INFO]:  - AdvancedPets, AdvancedPortals, ajLeaderboards, AlonsoTags, AngelChest, AuraSkills, AxTrade, BankPlus, BetterRTP, BetterTeams
[02:25:28 INFO]:  ChatColor2, ChatGames-Premium, ChestSort, Chunky, Citizens, CMILib, CraftingStore, CrazyEnchantments, CustomBansPlus, DailyRewards
[02:25:28 INFO]:  DeathMessages, DecentHolograms, DeluxeMenus, DiscordSRV, DriveBackupV2, eGlow, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates
[02:25:28 INFO]:  FastAsyncWorldEdit, FlareTokens, floodgate, FreeCoinFlip, Geyser-Spigot, GriefPrevention, GSit, HatCosmetics, HeadDB, Infiniteannouncements
[02:25:28 INFO]:  ItemEdit, ItemJoin, Jobs, LuckPerms, MineSpawners, MiniMOTD, MobsToEggs, Multiverse-Core, Multiverse-Inventories, NBTAPI
[02:25:28 INFO]:  NexEngine, nightcore, Nightvision, nLogin, ODailyQuests, packetevents, PerWorldPlugins, PlaceholderAPI, PlayerKits2, PlayerPoints
[02:25:28 INFO]:  *PlayTime, ProtocolLib, pvparena, SimpleGlow, SkinsRestorer, sleep-most, TAB, Themis, ToastedAFK, UltimateAutoRestart
[02:25:28 INFO]:  Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, Votifier, VotingPlugin, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3
[02:25:28 INFO]:  zMenu
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
