### ISSUE TITLE
Everyone can open doors inside claims without permissions

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#2357]
### Observed Behavior

People can use a Wind Charge to blow open a door inside someones claim without permission

### Expected Behavior

No door opening. Because they arent trusted.

### Reproduction steps

1. Make a claim
2. Lock someone inside with doors 
3. Let the non trusted person use wind charges on a door and it opens.

### Stack trace or error log

```shell
No error.
```

### Server version

```shell
18.08 12:22:07 [Server] INFO This server is running Paper version 1.21.1-33-master@64c9ee6 (2024-08-17T21:46:09Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
18.08 12:22:07 [Server] INFO You are running the latest version
```

### GriefPrevention version

```shell
16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_the_end: Survival
      world_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 10000000
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 10000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 0
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 600
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 10000
      UnusedClaimDays: 10000
      AllClaims:
        DaysInactive: 10000
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 10000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: true
    FireDamagesInClaims: true
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 30
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: false
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - ORANGE_WOOL
    - LIGHT_BLUE_WOOL
    - BROWN_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - BLUE_WOOL
    - RED_WOOL
    - GRASS_BLOCK
    - YELLOW_WOOL
    - JUNGLE_PLANKS
    - GRAVEL
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - PURPLE_WOOL
    - BIRCH_PLANKS
    - MAGENTA_WOOL
    - SHORT_GRASS
    - GRAY_WOOL
    - COBBLESTONE
    - DEAD_BUSH
    - LIME_WOOL
    - OAK_PLANKS
    - WHITE_WOOL
    - PINK_WOOL
    - FERN
    - SNOW
    - BLACK_WOOL
    - GLASS
    - SAND
    - GLASS_PANE
    - GREEN_WOOL
    - DIRT
    - SPRUCE_PLANKS
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
18.08 12:23:32 [Server] INFO - BanFromClaim, BlueBridgeCore, BlueBridgeGP, BlueMap, Chunky, Citizens, CoreProtect, DecentHolograms, *DisableSpawnerBreaking, DiscordSRV
18.08 12:23:32 [Server] INFO Essentials, EssentialsChat, ExcellentCrates, floodgate, Geyser-Spigot, GPFlags, GriefPrevention, GrimAC, GSit, HeadDatabase
18.08 12:23:32 [Server] INFO HiveChecker, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LibsDisguises, LightMaker, LiteBans, LuckPerms, MiniMOTD
18.08 12:23:32 [Server] INFO nightcore, NoteBlockAPI, packetevents, Pl-Hide-Pro, PlaceholderAPI, Plan, ProtocolLib, TabList, Vault, Vulcan
18.08 12:23:32 [Server] INFO WorldEdit, WorldGuard, WorldGuardExtraFlags
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
