### ISSUE TITLE
Claims owned by players who've not logged in for a while can't be deleted with /deleteallclaims

### ISSUE THREAD

**Issue by Cassolotl** [GriefPrevention/GriefPrevention#238]
### What behaviour is observed:
I am the admin. A player who has not logged in for a long time still had griefprevention claims. I tried to delete all of their claims with `/deleteallclaims username`. I got an error message, that said "No player by that name has logged in recently." If I stood inside that claim and typed `/abandonclaim` the claim was deleted without any problems.

Edit: I would also like to be able to do `/AdjustBonusClaimBlocks <username> 0` for players who've not logged in for a while, but that also gets me a "No player by that name has logged in recently."
### What behaviour is expected:
All of that player's claims being deleted.
### Steps/models to reproduce:
Type `/deleteallclaims (username)` for someone who's not logged in for a while, but whose claims are still active.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
[23:40:40] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-65e8124-963b19c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
[23:40:40] [Server thread/INFO]: Checking version, please wait...
[23:40:41] [Thread-218/INFO]: You are 73 version(s) behind
[23:41:36] [Server thread/INFO]: GriefPrevention version 16.7.1

### Stack trace/error

```
Paste entire stack trace inside here (don't remove the backticks!)
If not applicable, paste server.log at gist.github.com and paste the link here
```

I'm not sure what that is, but this is what shows in the console when I type `/deleteallclaims (username)`:

```
[23:42:09] [Server thread/INFO]: [GriefPrevention] §cNo player by that name has logged in recently.
```

### GriefPrevention config.yml (if applicable)

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    world_creative: -1
  Claims:
    Mode:
      world: Survival
      world_nether: Survival
      world_creative: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: false
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100000
    Claim Blocks Accrued Per Hour:
      Default: 1000
    Max Accrued Claim Blocks:
      Default: 800000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 2
    MinimumArea: 4
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: WOOD_SPADE
    Expiration:
      ChestClaimDays: 365
      UnusedClaimDays: 365
      AllClaims:
        DaysInactive: 365
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/t;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 10
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      world_creative: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 227:*:Battery Box
    - 130:*:Transmutation Tablet
    - 128:*:Alchemical Chest and Energy Condenser
    - 181:*:Various Chests
    - 178:*:Ender Chest
    - 150:*:Various BuildCraft Gadgets
    - 155:*:Filler
    - 157:*:Builder
    - 158:*:Template Drawing Table
    - 126:*:Various EE Gadgets
    - 138:*:Various RedPower Gadgets
    - 137:*:BuildCraft Project Table and Furnaces
    - 250:*:Various IC2 Machines
    - 161:*:BuildCraft Engines
    - 169:*:Automatic Crafting Table
    - 177:*:Wireless Components
    - 183:*:Solar Arrays
    - 187:*:Charging Benches
    - 188:*:More IC2 Machines
    - 190:*:Generators, Fabricators, Strainers
    - 207:*:Computer
    - 208:*:Computer Peripherals
    - 246:*:IC2 Generators
    - 24303:*:Teleport Pipe
    - 24304:*:Waterproof Teleport Pipe
    - 24305:*:Power Teleport Pipe
    - 4311:*:Diamond Sorting Pipe
    - 216:*:Turtle
    BlockIdsExplodable:
    - 161:*:BuildCraft Engines
    - 246:5:Nuclear Reactor
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Plugin list (if applicable):

[23:44:19] [Server thread/INFO]: Plugins (9): CoreProtect, PermissionsEx, dynmap, MultiWorld, AutismChat3, Seen, GriefPrevention, PvPManager, Floristics

**Comment by RoboMWM** [comment]
Yea, that's because GP doesn't load playerdata for players that haven't logged in for over 90 days. Not sure of an easy way to fix this other than just loading every player that has ever played on the server/is in the usercache. I could also try seeing if UUID input could work as well (then it'd just do a direct check for the file in the data folder).

**Comment by Cassolotl** [comment]
It's kind of a pain because it means claims don't automatically expire, I think! We have a player who's not logged in for over 2 years whose claims still have to be admin-deleted when someone finds one, and that's just started happening with a more recently banned player too.

**Comment by RoboMWM** [comment]
> because it means claims don't automatically expire, I think!

Nope - the claim expiry check iterates through all claims (slowly over time). Which makes sense - no need to iterate through every single player that has ever logged in (as there's no guarantee that they own any claims).

**Comment by Cassolotl** [comment]
Ohhh, huh, okay - then there is a separate bug preventing claims expiring. But I don't know how to reproduce that so we can ignore it for now. :)

**Comment by Jikoo** [comment]
They likely have over 10k blocks available or 5k bonus blocks. From your config:
```YAML
GriefPrevention:
  Claims:
    Expiration:
      AllClaims:
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
```
