### ISSUE TITLE
disappearing dropped items in claims

### ISSUE THREAD

**Issue by sennby** [GriefPrevention/GriefPrevention#2381]
### Observed Behavior

I have been on a ghost hunt since 1.21.1 update. finally after binary testing, i have determined it is griefprevention. (disabling plugins until it stopped then narrowing it down one by one) which led to grief prevention

I have been receiving reports of disappearing items, we have no entity clearers or anything like that like clearlag, so i didnt really believe them. 

BEFORE GP WAS DISABLED:
I tp to a really populated claim, lots of redstone running, lots of spawners farms etc.
I have 64 items in my inventory.
at random dropping will not work and poof the item.
drop 10 > pick up > i have 55 spawners now. most poofed
another test 2 disappeared of the 10, etc etc.

DISABLE GP:
Test multiple times dropping multiple items in multiple areas, I am always getting what i dropped back and the correct amount. Nothing is poofing.
64/64 after multiple tests of dropping and moving etc.

### Expected Behavior

Things should not disappear when you drop them.

### Reproduction steps

BEFORE GP WAS DISABLED:
I tp to a really populated claim, lots of redstone running, lots of spawners farms etc.
I have 64 items in my inventory.
at random dropping will not work and poof the item.
drop 10 > pick up > i have 55 spawners now. most poofed
another test 2 disappeared of the 10, etc etc.

DISABLE GP:
Test multiple times dropping multiple items in multiple areas, I am always getting what i dropped back and the correct amount. Nothing is poofing.
64/64 after multiple tests of dropping and moving etc.

### Server version

```shell
Paper version 1.21.1-57-master@b483da4
```

### GriefPrevention version

```shell
GriefPrevention v16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    resource_world: -1
    spawn: -1
  Claims:
    Mode:
      world: Survival
      spawn: Survival
      resource_world: Survival
      world_nether: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 500
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 25000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 15
      UnusedClaimDays: 90
      AllClaims:
        DaysInactive: 90
        ExceptWhenOwnerHasTotalClaimBlocks: 25000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 30
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      resource_world: false
      spawn: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 5000
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS     <-- can't understand this entry, see BukkitDev documentation
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 150
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
[17:41:16 INFO]:  - EconomyShopGUI, Minepacks
[17:41:16 INFO]: Bukkit Plugins:
[17:41:16 INFO]:  - AdvancedEnchantments, ArtMap, AuctionHouse, AuctionHouse, AuraSkills, AxEnvoy, BanItem, BattlePass, BetterRTP, BlockParticles
[17:41:16 INFO]:  BlueSlimeCore, Boss, ChatControlRed, ChatGames-Premium, ChestShop, Chunky, CMILib, CoinsEngine, CombatLogX, CoreArena
[17:41:16 INFO]:  CoreProtect, CrazyVouchers, CyberLevels, DecentHolograms, DeluxeMenus, DeluxeTags, DeluxeWithdraw, DomainStats, dynmap, eco
[17:41:16 INFO]:  eco, EcoArmor, EcoArmor, eGlow, EpicRename, Essentials, Essentials, EssentialsSpawn, EssentialsSpawn, EvenMoreFish
[17:41:16 INFO]:  ExcellentCrates, ExcellentCrates, EZColors, FastAsyncWorldEdit, GSit, InteractiveChat, InventoryRollbackPlus, ItemsAdder, Jobs, JShader
[17:41:16 INFO]:  Lib1711, libreforge, LibsDisguises, LiteBans, LoneLibs, LuckPerms, Mclogs, MCPets, MiniMOTD, Minions
[17:41:16 INFO]:  ModelEngine, Multiverse-Core, MythicCrucible, MythicMobs, NBTAPI, NekoTraps, nightcore, NightMarket, OpenInv, packetevents
[17:41:16 INFO]:  PermSk, PinataParty, PlaceholderAPI, PlayerPoints, PlayerWarps, PlugManX, ProtocolLib, ProtocolLib, RealEstate, ResourceWorld
[17:41:16 INFO]:  RocketPlaceholders, RoseLoot, Sellwand, Skript, SpawnerMeta, SpawnerMeta, StaffChat, SuperVanish, TAB, TempFly
[17:41:16 INFO]:  TerraformGenerator, UltimateClans, UltimateKoth, UltraCosmetics, VariableEnderChests, Vault, ViaBackwards, ViaVersion, VoidGen, Vulcan
[17:41:16 INFO]:  WitherSound, WorldGuard, ZNPCsPlus
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
