### ISSUE TITLE
cant build here unless claim 

### ISSUE THREAD

**Issue by mc3-ux** [GriefPrevention/GriefPrevention#2394]
### Observed Behavior

players cant build/destroy widouth making a claim

### Expected Behavior

pls help i tink is from config

### Reproduction steps

try to break
![image_2024-11-01_105229619](https://github.com/user-attachments/assets/46923052-f753-48e9-883f-b25342dfd57f)
![image_2024-11-01_105235852](https://github.com/user-attachments/assets/e7e68ccb-57fc-4bc9-b51d-499b62b878a9)

### Server version

```shell
1.19.3
```

### GriefPrevention version

```shell
16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    creative_nether: -1
    creative: -1
  Claims:
    Mode:
      world_the_end: Disabled
      creative: Creative
      creative_nether: Creative
      world_nether: Disabled
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      creative_nether: true
      creative: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRAY_WOOL
    - BROWN_WOOL
    - DEAD_BUSH
    - DARK_OAK_PLANKS
    - GRASS
    - BLUE_WOOL
    - GREEN_WOOL
    - YELLOW_WOOL
    - LIGHT_BLUE_WOOL
    - GRASS_BLOCK
    - SAND
    - PINK_WOOL
    - DIRT
    - GRAVEL
    - LIGHT_GRAY_WOOL
    - OAK_PLANKS
    - RED_WOOL
    - COBBLESTONE
    - LIME_WOOL
    - CYAN_WOOL
    - ACACIA_PLANKS
    - BLACK_WOOL
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - GLASS
    - GLASS_PANE
    - PURPLE_WOOL
    - SNOW
    - WHITE_WOOL
    - FERN
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - JUNGLE_PLANKS
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
AdvancedBan


AdvancedBan-Bundle-2.3.0-RELEASE.jar

BeautyQuests


beautyquests-1.0.4.jar

BedWars1058


BedWars1058.jar

BetterRTP


BetterRTP-3.6.13.jar

BetterStructures


BetterStructures.jar

bStats


CataMines


CataMines-2.5.11.jar

Chunky


Chunky-1.3.146.jar

Citizens


Citizens-2.0.36-b3611.jar

CMILib


CMILib1.5.2.1.jar

DecentHolograms


DecentHolograms-2.8.11.jar

DropHeads


DropHeads.jar

EconomyShopGUI-6.1.4.jar

Essentials


EssentialsX-2.20.1.jar

Graves


Graves-4.9.jar

GriefPrevention.jar

GriefPreventionData


GUIPlusDemo


GUIPlusDemo-2.86.jar

ItemsAdderUploadPlus-0.1.5.jar

LuckPerms


LuckPerms-bukkit-5.4.145.jar

Minepacks


Minepacks.jar

Multiverse-Core


multiverse-core-4.3.11.jar

Multiverse-Inventories


multiverse-inventories-4.2.7-pre.jar

Multiverse-NetherPortals


Multiverse-NetherPortals-4.2.2.jar

Multiverse-Portals


Multiverse-Portals-4.2.1.jar

PlaceholderAPI


PlaceholderAPI-2.11.6.jar

PlayerKits2


PlayerKits2.jar

PluginHider+ 5.2.jar

QualityArmory


QualityArmory.jar

Quests


Quests-5.1.4.jar

ServersNPC


SimpleScore


SimpleScore-3.12.5.jar

Skywars


SkyWarsReloaded 5.6.33.jar

SpigotUpdates


update


Updater


Vault


Vault.jar

ViaBackwards


ViaBackwards-5.1.1-SNAPSHOT.jar

ViaVersion


ViaVersion-5.1.0.jar

VillageDefense


villagedefense-4.7.1.jar

WorldEdit


worldedit-bukkit-7.3.0-beta-02.jar

WorldGuard


worldguard-bukkit-7.0.8-dist.jar

znpcs-4.8.jar
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by bigpresh** [comment]
That'll be the [Claims.Mode](https://docs.griefprevention.com/configuration/#limiting-which-worlds-griefprevention-runs-on) setting.

You have:

```
  Claims:
    Mode:
      world_the_end: Disabled
      creative: Creative
      creative_nether: Creative
      world_nether: Disabled
      world: Survival
```

`Creative` mode means you must claim before you can build, `Survival` doesn't - so if you want people to be able to build anywhere on the `creative` / `creative_nether` worlds, then set it to `Survival` instead of `Creative` for them.  I'd not recommend it, though if it's a publicly accessible server - as that provides griefers with unlimited blocks to grief the world in creative mode as much as they want over as wide an area as they'd like, and you probably don't really want that.
