### ISSUE TITLE
Opening chests in claimed areas bug

### ISSUE THREAD

**Issue by sennby** [GriefPrevention/GriefPrevention#2406]
### Observed Behavior

Put a chestplate in your hand
go to a chest in a claimed area
open the chest

### Expected Behavior

the chest should not open

### Reproduction steps

Put a chestplate in your hand
go to a chest in a claimed area
open the chest

### Server version

```shell
This server is running UniverseSpigot version 1.21.1-ver/1.21.1-plus@20fe67a (2024-12-12T22:36:45Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Universe-1.21.1-20fe67a (MC: 1.21.1)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    swpack2: -1
    PrestigeIsland: -1
    superhero: -1
    glasswalk: -1
    arena: -1
    medievalskywars: -1
    topkill1: -1
    Boss: -1
    skywpack3: -1
    skywpack4: -1
    skywpack1: -1
    splatoon: -1
    sgisland: -1
    MobArena: -1
    gameroom: -1
    resource_world: -1
    DeathSpleef: -1
    tntrun1: -1
    battleroyale5: -1
    teamskywars: -1
    AmberOakState: -1
    HideSeek: -1
    splatoonthemepark: -1
    newspawn: -1
    California: -1
    paintball: -1
    boatwars: -1
    gemcrawler4: -1
    kbduel2: -1
    dungeon: -1
    blockparty: -1
    fishslap: -1
    spawn: -1
    quake: -1
    bombardment: -1
    runbeast: -1
  Claims:
    Mode:
      world: Survival
      swpack2: Survival
      topkill1: Survival
      skywpack3: Survival
      tntrun1: Disabled
      runbeast: Survival
      skywpack4: Survival
      fishslap: Disabled
      world_nether: Survival
      arena: Disabled
      splatoonthemepark: Survival
      California: Survival
      PrestigeIsland: Survival
      gemcrawler4: Disabled
      AmberOakState: Survival
      resource_world: Disabled
      superhero: Survival
      world_the_end: Survival
      battleroyale5: Disabled
      paintball: Disabled
      blockparty: Survival
      MobArena: Disabled
      DeathSpleef: Survival
      quake: Disabled
      dungeon: Disabled
      bombardment: Disabled
      glasswalk: Survival
      spawn: Survival
      boatwars: Survival
      Boss: Disabled
      gameroom: Disabled
      HideSeek: Survival
      teamskywars: Survival
      sgisland: Survival
      skywpack1: Survival
      newspawn: Survival
      medievalskywars: Disabled
      splatoon: Survival
      kbduel2: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 500
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 25000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 15
      UnusedClaimDays: 90
      AllClaims:
        DaysInactive: 90
        ExceptWhenOwnerHasTotalClaimBlocks: 25000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 30
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      swpack2: true
      PrestigeIsland: true
      superhero: true
      glasswalk: true
      arena: true
      medievalskywars: true
      topkill1: true
      Boss: true
      skywpack3: true
      skywpack4: true
      skywpack1: true
      splatoon: true
      sgisland: false
      MobArena: true
      gameroom: true
      resource_world: true
      DeathSpleef: true
      tntrun1: true
      battleroyale5: true
      teamskywars: true
      AmberOakState: true
      HideSeek: true
      splatoonthemepark: true
      newspawn: true
      California: true
      paintball: true
      boatwars: true
      gemcrawler4: true
      kbduel2: true
      dungeon: true
      blockparty: true
      fishslap: true
      spawn: true
      quake: true
      bombardment: true
      runbeast: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 5000
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS     <-- can't understand this entry, see BukkitDev documentation
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 150
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
