### ISSUE TITLE
Admin claims denny any actions for players when OP is seted

### ISSUE THREAD

**Issue by MarcoAFSchaefer** [GriefPrevention/GriefPrevention#2415]
### Observed Behavior

Non-OP players are getting trapped in the spawn hub. I built a welcome building for new players, but only OP accounts can open the door or read the rule book.

Details:

- The building is within an admin claim.
- I used the command:
`/accesstrust public`
But it still doesn’t allow non-OP players to interact with doors or read the rule book.

### Expected Behavior

Enable all players to open the door and read the server rules without requiring OP permissions.

### Reproduction steps

1. **Create an Admin Claim**  
   Use your server’s land-claim plugin (e.g., GriefPrevention) to create an Admin Claim.
2. **Place a Door Within the Claim**  
   Make sure the door is fully contained inside the new Admin Claim.
3. **Grant Public Access**  
   ```shell
   /accesstrust public
   ```
   This command should allow all players to interact with doors, levers, buttons, etc. within the claim.
4. **Set a User as OP**  
   Give a specific player OP status:
   ```shell
   /op <username>
   ```
5. **Log in with a Non-OP User**  
   Either use a different account or have someone else join without OP privileges.
6. **Attempt to Open the Door**  
   Verify whether this non-OP user can open the door as intended—or if they’re still restricted.

### Server version

```shell
[02:05:29 INFO]: [bootstrap] Loading Paper 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) for Minecraft 1.21.3
```

### GriefPrevention version

```shell
[02:05:33 INFO]: [GriefPrevention] Loading server plugin GriefPrevention v16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_the_end: Disabled
      world_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 500
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: GOLDEN_AXE
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 365
      UnusedClaimDays: 365
      AllClaims:
        DaysInactive: 365
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - BLACK_WOOL
    - COBBLESTONE
    - GRAY_WOOL
    - BIRCH_PLANKS
    - GRASS_BLOCK
    - GREEN_WOOL
    - SHORT_GRASS
    - PINK_WOOL
    - SAND
    - ORANGE_WOOL
    - WHITE_WOOL
    - YELLOW_WOOL
    - DEAD_BUSH
    - BROWN_WOOL
    - GLASS
    - BLUE_WOOL
    - FERN
    - LIME_WOOL
    - GLASS_PANE
    - GRAVEL
    - DARK_OAK_PLANKS
    - OAK_PLANKS
    - ACACIA_PLANKS
    - LIGHT_BLUE_WOOL
    - LIGHT_GRAY_WOOL
    - MAGENTA_WOOL
    - PURPLE_WOOL
    - SNOW
    - RED_WOOL
    - JUNGLE_PLANKS
    - SPRUCE_PLANKS
    - CYAN_WOOL
    - DIRT
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
[02:05:30 INFO]: [PluginInitializerManager] Bukkit plugins (9):
 - BetterBeds (1.1-SNAPSHOT (build 30)), Essentials (2.21.0-dev+115-6157668), EssentialsChat (2.21.0-dev+115-6157668), EssentialsSpawn (2.21.0-dev+115-6157668), GriefPrevention (16.18.4), LuckPerms (5.4.151), NoxPlugin (1.1.0-SNAPSHOT), SkinsRestorer (15.5.1), Vault (1.7.3-b131)
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.
