### ISSUE TITLE
Doors can be opened in a claim owned by someone else

### ISSUE THREAD

**Issue by EndersWolf3072** [GriefPrevention/GriefPrevention#2442]
### Observed Behavior

One of the player on my server has a claim that other people can use the doors to her home. She deleted the claim and reclaimed and it didn't fix. Also made sure everyone wasn't trusted as well. Im not owner of her claim and can open the door

https://github.com/user-attachments/assets/8eaaf78d-9b17-4059-a42c-8649a9fec427

### Expected Behavior

While a home claimed, people who are untrusted can still access the claim.

### Reproduction steps

Claim land
Made sure no one but owner has access.
Other player tries door

### Stack trace or error log

```shell

```

### Server version

```shell
01.03 18:51:45 [Server] INFO You are 6 version(s) behind
01.03 18:51:45 [Server] INFO Download the new version at: https://papermc.io/downloads/paper
```

### GriefPrevention version

```shell
01.03 18:53:51 [Server] INFO GriefPrevention version 16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    TonsCatGangworld: -1
    TonsCatGangworld_nether: -1
    TonsCatGangworld_the_end: -1
    Spawn: -1
    Terra: -1
  Claims:
    Mode:
      TonsCatGangworld_nether: Survival
      Terra: Survival
      Spawn: Survival
      TonsCatGangworld_the_end: Survival
      TonsCatGangworld: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 1000
    Max Accrued Claim Blocks:
      Default: 240000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 0
      UnusedClaimDays: 0
      AllClaims:
        DaysInactive: 0
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      TonsCatGangworld: true
      TonsCatGangworld_nether: true
      TonsCatGangworld_the_end: true
      Spawn: true
      Terra: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 10.0
    ClaimBlocksSellValue: 500.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  SilenceBans: false
  Siege:
    Worlds: []
    BreakableBlocks:
    - ORANGE_WOOL
    - LIGHT_GRAY_WOOL
    - PINK_WOOL
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - FERN
    - LIME_WOOL
    - ACACIA_PLANKS
    - GLASS
    - BROWN_WOOL
    - COBBLESTONE
    - OAK_PLANKS
    - BLACK_WOOL
    - GRASS_BLOCK
    - LIGHT_BLUE_WOOL
    - DARK_OAK_PLANKS
    - GRAVEL
    - SPRUCE_PLANKS
    - CYAN_WOOL
    - GRAY_WOOL
    - BLUE_WOOL
    - DIRT
    - MAGENTA_WOOL
    - YELLOW_WOOL
    - GLASS_PANE
    - SAND
    - GREEN_WOOL
    - SNOW
    - PURPLE_WOOL
    - SHORT_GRASS
    - WHITE_WOOL
    - DEAD_BUSH
    - RED_WOOL
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 0
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 30
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: true
  ConfigVersion: 1
```

### Plugin list

```shell
01.03 18:55:29 [Server] INFO Paper Plugins:
01.03 18:55:29 [Server] INFO - ChessCraft, FancyNpcs
01.03 18:55:29 [Server] INFO Bukkit Plugins:
01.03 18:55:29 [Server] INFO - AdvancedJobs, AdvancedModels, ajLeaderboards, AuraSkills, ChatFeelings, ChatManager, Chunky, Citizens, CustomAnvil, DecentHolograms
01.03 18:55:29 [Server] INFO DragonSlayer, DragonTimer, EconomyBridge, EntityClearer, Essentials, EssentialsChat, EssentialsWarpGUI, ExcellentShop, floodgate, Geyser-Spigot
01.03 18:55:29 [Server] INFO GPExtension, GPFlags, GriefPrevention, GSit, LevelledMobs, LibsDisguises, LuckPerms, Multiverse-Core, Multiverse-Inventories, MythicMobs
01.03 18:55:29 [Server] INFO nightcore, Orebfuscator, packetevents, PlaceholderAPI, ProtocolLib, RealEstate, SetSpawn, SkipNight, Sleeper, StackMob
01.03 18:55:29 [Server] INFO Telekinesis, TradeManager, Vault, Veinminer, ViaVersion, WildRTP, WorldEdit
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [x] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [x] I searched for similar issues before submitting this bug report.
