### ISSUE TITLE
My players can open chests without permission.

### ISSUE THREAD

**Issue by Closy12** [GriefPrevention/GriefPrevention#2456]
### Observed Behavior

Untrusted players can open chests in people claims when they do it says the normal /ignoreclaim stuff but they dont have permission to do that yet they can still open the chest. Only thing that has changed on my server is i updated to essentials x

### Expected Behavior

People wouldnt be able to open chests

### Reproduction steps

1. People open chests
2. they can actually access it with no trust

### Stack trace or error log

```shell

```

### Server version

```shell
[07:32:47 INFO]: This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
```

### GriefPrevention version

```shell
[07:33:52 INFO]: GriefPrevention version 16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    Easter: -1
    Builds: -1
    Test: -1
  Claims:
    Mode:
      Easter: Survival
      world: Survival
      Builds: Survival
      world_the_end: Survival
      world_nether: Survival
      Test: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 250
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 30
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      Easter: true
      Builds: true
      Test: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: false
  Siege:
    Worlds: []
    BreakableBlocks:
    - LIGHT_GRAY_WOOL
    - GREEN_WOOL
    - BLUE_WOOL
    - BIRCH_PLANKS
    - DEAD_BUSH
    - FERN
    - SPRUCE_PLANKS
    - DIRT
    - LIGHT_BLUE_WOOL
    - RED_WOOL
    - GLASS_PANE
    - BROWN_WOOL
    - JUNGLE_PLANKS
    - GLASS
    - ORANGE_WOOL
    - COBBLESTONE
    - GRAVEL
    - PURPLE_WOOL
    - BLACK_WOOL
    - SAND
    - YELLOW_WOOL
    - DARK_OAK_PLANKS
    - MAGENTA_WOOL
    - ACACIA_PLANKS
    - GRASS_BLOCK
    - CYAN_WOOL
    - SHORT_GRASS
    - GRAY_WOOL
    - WHITE_WOOL
    - SNOW
    - LIME_WOOL
    - PINK_WOOL
    - OAK_PLANKS
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
/plugins
[07:34:55 INFO]: Server Plugins (94):
[07:34:55 INFO]: Paper Plugins:
[07:34:55 INFO]:  - MarriageMaster
[07:34:55 INFO]: Bukkit Plugins:
[07:34:55 INFO]:  - ArmorStandEditor, AxGraves, AxiomPaper, AxShulkers, AxTrade, BetonQuest, BetterMessages, BetterRTP, BetterStructures, BisectHosting
[07:34:55 INFO]:  BlepFishing, BlueMap, BreweryX, ChatFeelings, CoreProtect, CosmicCosmetics, craftableinvframes, CrazyEnchantments, CustomCommands, CustomCrafting
[07:34:55 INFO]:  CustomCrops, CustomFishingZ, DecentHolograms, DeluxeMenus, DiceFurniture, DiscordSRV, DoorsReloaded, Essentials, EssentialsChat, EssentialsSpawn
[07:34:55 INFO]:  ExcellentEnchants, FancyWaystones, FurnitureLib, GCore, GriefPrevention, GrimAC, GSit, HeadDrop, ImageFrame, InventoryRollbackPlus
[07:34:55 INFO]:  InvSeePlusPlus, ItemsAdder, LoneLibs, LuckPerms, mcMMO, MCPets, MediaPlayer, MiniBlocks, MiniGolf, MMOItems
[07:34:55 INFO]:  ModelEngine, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MurderMystery, MythicCrucible, MythicLib, MythicMobs, nightcore, NoPlugins
[07:34:55 INFO]:  Origins-Fantasy, Origins-Magic, Origins-Mobs, Origins-Monsters, Origins-Reborn, PhoenixCrates, PiggyBack, PlaceholderAPI, PlayerReport, PostOffice
[07:34:55 INFO]:  ProtectionLib, ProtocolLib, PVPToggle, RHLeafDecay, RockPaperScissors, Shopkeepers, ShopkeepersList, SimpleNicks, SimplePets, Sleeper
[07:34:55 INFO]:  SuperVanish, TAB, TabTPS, TheBridge, UltraCosmetics, Vault, ViaVersion, voicechat, Votifier, VotingPlugin
[07:34:55 INFO]:  WolfyUtilities, WorldEdit, WorldGuard
```

### Running without GriefPrevention

- [x] I attempted running the server without GriefPrevention installed.
- [x] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [x] I searched for similar issues before submitting this bug report.
