### ISSUE TITLE
/Trapped & SurvivalRequiringClaims

### ISSUE THREAD

**Issue by Unipotatoo** [GriefPrevention/GriefPrevention#2459]
### Observed Behavior

On my server I have SurvivalRequiringClaims set, although with large pitfalls, and powdered snow players can get trapped and are unable to use /trapped as it says "You can build here. Save yourself" But they cant build unless they claim.

### Expected Behavior

I would expect /trapped to move the player to a safe location.

### Reproduction steps

Step 1. Set the world to SurvivalRequiringClaims
Step 2. Get Trapped (Go into a cave, or powdered snow)
Step 3. Run /Trapped

### Stack trace or error log

```shell

```

### Server version

```shell
[00:32:22 INFO]: This server is running Paper version 1.21.4-221-main@c467df9 (2025-03-24T00:18:41Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
```

### GriefPrevention version

```shell
[00:32:39 INFO]: GriefPrevention version 16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    resource_world: -1
  Claims:
    Mode:
      resource_world: Disabled
      world_nether: Survival
      world: SurvivalRequiringClaims
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 250
    Max Accrued Claim Blocks:
      Default: 9999999
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: CHAIN_COMMAND_BLOCK
    ModificationTool: REPEATING_COMMAND_BLOCK
    Expiration:
      ChestClaimDays: 120
      UnusedClaimDays: 120
      AllClaims:
        DaysInactive: 120
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: true
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      resource_world: true
    ProtectFreshSpawns: false
    PunishLogout: true
    CombatTimeoutSeconds: 5
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  VisualizationAntiCheatCompatMode: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  SilenceBans: false
  Siege:
    Worlds: []
    BreakableBlocks:
    - GLASS_PANE
    - JUNGLE_PLANKS
    - SAND
    - MAGENTA_WOOL
    - BROWN_WOOL
    - GRASS_BLOCK
    - OAK_PLANKS
    - YELLOW_WOOL
    - ACACIA_PLANKS
    - DEAD_BUSH
    - DARK_OAK_PLANKS
    - SNOW
    - PINK_WOOL
    - CYAN_WOOL
    - GRAVEL
    - WHITE_WOOL
    - PURPLE_WOOL
    - COBBLESTONE
    - LIME_WOOL
    - LIGHT_GRAY_WOOL
    - GREEN_WOOL
    - SHORT_GRASS
    - RED_WOOL
    - DIRT
    - BLACK_WOOL
    - GRAY_WOOL
    - BIRCH_PLANKS
    - SPRUCE_PLANKS
    - ORANGE_WOOL
    - LIGHT_BLUE_WOOL
    - FERN
    - BLUE_WOOL
    - GLASS
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
[00:33:27 INFO]:  - AdvancedPlHide, ajLeaderboards, BlocksPlaced, ChatChat, Chunky, Citizens, CoreProtect, CustomJoinMessages, DeluxeMenus, Essentials
[00:33:27 INFO]:  FastAsyncWorldEdit, FurniturePainting, GPFlags, GriefPrevention, GriefPreventionBlocks, Infiniteannouncements, ItemJoin, ItemRotation, LiteBans, LuckPerms
[00:33:27 INFO]:  Lumena, MiniMOTD, ModelEngine, Multiverse-Core, MyCommand, NamelessMC, Nexo, NexoAddon, NexoLootAddon, ODailyQuests
[00:33:27 INFO]:  OpenInv, PhantomSpawnControl, PlaceholderAPI, PlaceholderNotifications, ProtocolLib, SimpleHoarder, SpectatorMode, Stars, SuperVanish, TAB
[00:33:27 INFO]:  TCPShield, Tebex, TradeSystem, UltimateAutoRestart, Vault, VirtualBooks, VotifierPlus, VotingPlugin, WorldGuard, WorldGuardExtraFlags
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [x] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [x] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [x] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [x] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [x] I searched for similar issues before submitting this bug report.
