### ISSUE TITLE
Armor Stand Can Be Moved Inside Claims Using Mace Ability (1.21.5 paper)

### ISSUE THREAD

**Issue by ProbablyYash** [GriefPrevention/GriefPrevention#2473]
### Observed Behavior

Untrusted players can exploit the mace's knockback effect to move armor stands out of claimed areas. For example, when a player is PvP-tagged and stands next to an armor stand within a claim, an attacker can hit the player and cause the mace’s knockback (e.g., Burst enchantment) to push the armor stand outside the claim boundaries.

### Expected Behavior

Claims should prevent any interaction or movement of armor stands by untrusted players, including indirect methods such as knockback from PvP or enchantments like Burst on a mace.

### Reproduction steps

1. Stand near an armor stand inside a claim.
2. Get PvP-tagged (e.g., in combat).
3. Have an untrusted player hit you with a mace that has Burst or similar knockback ability.
4. Observe the armor stand being pushed out of the claim.

### Stack trace or error log

```shell
N/A – This is a behavior issue, not a crash.
```

### Server version

```shell
Paper version git-Paper-1.21.5-69-main@c98cd65 (2025-05-03T20:38:42Z) (MC: 1.21.5)
```

### GriefPrevention version

```shell
GriefPrevention version - 16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    spawn: -1
  Claims:
    Mode:
      spawn: Survival
      world_nether: Disabled
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      spawn: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - LIME_WOOL
    - BLACK_WOOL
    - YELLOW_WOOL
    - BIRCH_PLANKS
    - GLASS
    - OAK_PLANKS
    - GRASS_BLOCK
    - FERN
    - WHITE_WOOL
    - ORANGE_WOOL
    - DARK_OAK_PLANKS
    - LIGHT_GRAY_WOOL
    - DEAD_BUSH
    - JUNGLE_PLANKS
    - MAGENTA_WOOL
    - GREEN_WOOL
    - DIRT
    - CYAN_WOOL
    - SNOW
    - SHORT_GRASS
    - BLUE_WOOL
    - BROWN_WOOL
    - SPRUCE_PLANKS
    - GRAY_WOOL
    - COBBLESTONE
    - RED_WOOL
    - SAND
    - ACACIA_PLANKS
    - PINK_WOOL
    - GRAVEL
    - PURPLE_WOOL
    - GLASS_PANE
    - LIGHT_BLUE_WOOL
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: true
  BanCommandPattern: kick %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
EconomyShopGUI, ajLeaderboards, AuthMe, BetterRTP, BoomBox, Citizens, ClearLag, DecentHolograms, DeluxeMenus, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, GriefPrevention, Infiniteannouncements, LuckPerms, MiniMOTD, Multiverse-Core, NoteBlockAPI, packetevents, PlaceholderAPI, PlayerAuctions, PlayerKits2, ProtocolLib, SkinsRestorer, TAB, Vault, ViaBackwards, ViaRewind, ViaVersion, vpn-system, Vulcan, WorldEdit, WorldGuard
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [x] I attempted running only GriefPrevention on the server.
- [x] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [x] I attempted testing for the issue on a new server.
- [x] The issue still occurs on a new server.

### Using unmodified client

- [x] I attempted testing for the issue with the vanilla client.
- [x] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [x] I searched for similar issues before submitting this bug report.
