### ISSUE TITLE
Server Crashed w/ GP Error

### ISSUE THREAD

**Issue by stifflered** [GriefPrevention/GriefPrevention#276]
### What behaviour is observed:
My server crashed and this error was thrown in the console: https://pastebin.com/NqT1ZRMr

### What behaviour is expected:
There wouldn't be a crash.

### Steps/models to reproduce:
I'm unsure. My server has been crashing a bit lately and this is the first time I've seen a crash error in the console. 

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This server is running CraftBukkit version git-Spigot-b6ecf3b-fb423b8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
GP was 16.8

### GriefPrevention config.yml (if applicable)

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    TheTreeCrafter: -1
    TheTreeCrafter_nether: -1
    TheTreeCrafter_the_end: -1
    Althing: -1
    Build: -1
    Althing_Nether: -1
    BedWarsMapOne: -1
  Claims:
    Mode:
      TheTreeCrafter: Survival
      TheTreeCrafter_the_end: Survival
      Althing: Disabled
      TheTreeCrafter_nether: Disabled
      BedWarsMapOne: Disabled
      Althing_Nether: Disabled
      Build: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 75
    Max Accrued Claim Blocks:
      Default: 800000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 70
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 14
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      TheTreeCrafter: true
      TheTreeCrafter_nether: true
      TheTreeCrafter_the_end: true
      Althing: true
      Build: true
      Althing_Nether: true
      BedWarsMapOne: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: false
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
PlaceholderAPI, PigmanAttention, RawMsg, Arconix, ChatFeelings, EpicWorldGenerator, WooMinecraft, LightAPI, dynmap, EpicNetherGenerator, WorldEdit, BeastTokens, BlockQuest, WorldBorder, RankAura, EasyBackup, ProtocolLib, SimpleGuiApi, React, More-Drops, mcMMO, Vault, UltraPermissions, PublicCrafters, ParrotAnnouncer, PlotSquared, LWC, WorldGuard, TransportPipes, SignBoard, CMIEInjector, RepairPlus, Wormholes, Statz, TitleManager, TryMe, mcMMOAction, HeadDatabase, EpicSpawners, Multiverse-Core, Citizens, DiscordSRV, Residence, Hydra, Plot2Dynmap, AuctionGUIPlus, ShopChest, ProRecipes, MCJukebox, CMI, ProtectionLib, CommandNPC, Multiverse-NetherPortals, CompatNoCheatPlus, NoCheatPlus, TradeMe, MusicalBiomes, CustomEnchants, FurnitureLib, DiceFurniture, CraftBook
