### ISSUE TITLE
claimblock accrual rates (old system)

### ISSUE THREAD

**Issue by Remski01** [GriefPrevention/GriefPrevention#28]
# What behaviour is expected:

multiple claim blocks getting amount,(other players get more with the other perm)
### What behaviour is observed:

Players did not get claim blocks more.
### Steps/models to reproduce:

Unkown.
### Spigot/Craftbukkit/Paper and GriefPrevention version:

Spigot: git-Spigot-850da7e-b5fb9a1 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
GP: GriefPrevention version 15.3
### Stack trace/error (if applicable)

Not related.

Paste entire stack trace inside here
Not related
### GriefPrevention config.yml (if applicable)

http://pastebin.com/rapkKDUb
### Paste config inside here

Not related
### Plugin list (if applicable):

Not related
### EXTRA:

Starter ranks that are free dont get the claim option. I used the negative permissions of PEX. Claims are an second way of protection. First is that only chest doors etc, are protected.

**Comment by RoboMWM** [comment]
Need to see your PEX permissions.yml. I also advise revising your permissions to avoid relying on negating permissions, especially if you're doing that to prevent "lower ranked" players access to such permissions.

**Comment by Remski01** [comment]
http://pastebin.com/fMjF0dQT

**Comment by Remski01** [comment]
So. This is not GP related? Is it PEX negative permission related?

**Comment by RoboMWM** [comment]
> Is it PEX negative permission related?

Yes.

I asked in the PEX IRC channel, and have yet to receive a response; all I can think of trying is to put the `Inheritance` key below the `Permissions` key...

However, what I do is have a "base" permission level, which everyone inherits. Then, the default group can have those extra negated permissions, while the VIP groups only inherit from the "base" permissions, avoiding having to deal with "un-negating" permissions down the inheritance tree.

**Comment by RoboMWM** [comment]
> [zml] yeah, inherited permissions have lower priority
> [zml] in pex 1.x essentially all the permissions are strung together in a list so whatever is listed first takes priority

I have nothing more to add other than my prior comment.

**Comment by RoboMWM** [comment]
FYI, from what you pasted on #37 - you did not implement my proposed solution properly. You are still inheriting from the Starter group. The idea is to make a group of "base" permissions everyone inherits from (and does **not** contain negated permissions). Then, each group inherits from this "base," and from here you can add negative permissions or w/e.

I'll paste an example soon.

**Comment by RoboMWM** [comment]
Hopefully this helps:

``` yml
groups:
  default:
    options:
      build: true
      prefix: ''
      suffix: ''
      default: true
      rank: '10000'
    permissions:
    - permission.default.gets
    - -permission.default.should.not.have
    inheritance:
    - base
  staff:
    inheritance:
    - cool
    options:
      prefix: '&9%'
    permissions:
    - staff.permission
  base:
    permissions:
    - permission.everyone.gets
  cool:
    options:
      prefix: '&b+'
    inheritance:
    - base
    permissions:
    - permissions.cool.people.get
```
