### ISSUE TITLE
Allow ridable entities (boats, horses, happy ghasts, etc.) driven by a player to be temporarily "owned" when inside another claim

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#295]
Currently if you happen to drive and exit from a boat while in an untrusted claim, you won't be able to re-enter as the entity will be considered as owned by the claim owner.

Can either:
- disable trust permission for boat entry (most players don't care about cheap boats, and if they do, they usually have a dock)
- set metadata on the boat when a passenger exits, and exempt from trust permission if he re-enters it (metadata is temporary so no storage or performance loss here).

**Comment by rjohnson98126** [comment]
adding comment to note that horses have similar behavior:  if player rides their horse into an admin claim, and gets off, then they can't get back on, or put a lead on the horse.   

invariably requiring admins to have to go "rescue" that players favorite horse which they just cant live without not even for a moment.

EDIT:  technically, i should say any untrusted claim, not specifically admin claims.

**Comment by ShaneBeee** [comment]
I agree with @rjohnson98126  here.... can't tell you the amount of times I have had to go rescue horses for players. 

On my server I use the grief prevention flags, to let players know when they are entering/exiting claims, that helps a bit since they usually know to NOT get off their horse. BUT quite often, you dont think about it, then you lose your horse to another persons claim.

**Comment by ghost** [comment]
I like the idea of these both having a temp trust, not being removed from protection. :)

**Comment by zaphod77** [comment]
If it's just you in the boat, it should drop as an item when you get off of it if you don't have permission to place a boat in the claim.

If not, it should refuse to let you exit the boat, because that would gift the villager you were carrying to the other person.

As it stans you can steal people's boats by claiming around them and trapping them.

**Comment by RainVaporeon** [comment]
Bump issue, this opens up opportunity to steal other player's vehicles as long as they are in your claim (and have no way of leaving)
Additionally this issue also caused some players to get locked (unable to leave vehicles etc)

**Comment by VulcanoSoftware** [comment]
After 7 years, this is still an issue. It also happens on happy ghasts

**Comment by VulcanoSoftware** [comment]
Can you maybe solve this with a toggleable option in the config.yml? so that if a player exits a boat, the boat is given metadata so that player can enter that again, no matter in which claim they are.

**Comment by QarthO** [comment]
I addressed this issue in #2520 which allows you to hop back on your rideable mount, and get back into your vehicle.

But in my testing BEFORE the PR, (on v16.18.4 and on v16.18.5) i was able to hop onto a horse and hop into a boat inside someones elses claim i had no permission. You currently CAN re-enter even before #2520 (except for happy ghasts which the PR addresses)

https://streamable.com/qk3hqj

using default GP Config

<details>
  <summary>GP Config</summary>

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world: Survival
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 80000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1


```
</details>
