### ISSUE TITLE
Item durability resets when interacting in a claim without permissions

### ISSUE THREAD

**Issue by kaanakduman** [GriefPrevention/GriefPrevention#355]
### What behaviour is observed:
_An axe that had 1 use left got fully repaired when right clicking a log in someone else's claim_
### What behaviour is expected:
_I expected the axe to stay at 1 durability_
### Steps/models to reproduce:
1. PlayerA places down a log.
2. PlayerA claims the log and the area around it without adding anyone to the claim
3. PlayerB has an axe with 1 durability in his hand.
4. PlayerB right clicks the log as if stripping it. PlayerB now has a fully repaired axe.

This also works with tilling grass.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This server is running CraftBukkit version git-Spigot-fe3ab0d-7c341e9 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)__
__GriefPrevention version 16.8__

### Stack trace/error

Sorry, I had to skip this step, but the console didn't spit out any warnings or errors when this happened.

### GriefPrevention config.yml (if applicable)

```yml
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    otut: -1
    resend: -1
    resworld: -1
    creative: -1
  Claims:
    Mode:
      resworld: Survival
      world: Survival
      creative: Disabled
      world_nether: Survival
      world_the_end: Survival
      otut: Disabled
      resend: Disabled
    PreventGlobalMonsterEggs: false
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 500
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 1000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 256
    MinimumWidth: 2
    MinimumArea: -1
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: -1
      UnusedClaimDays: -1
      AllClaims:
        DaysInactive: -1
        ExceptWhenOwnerHasTotalClaimBlocks: -1
        ExceptWhenOwnerHasBonusClaimBlocks: -1
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: -1
    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: -1
  Spam:
    Enabled: false
    LoginCooldownSeconds: -1
    LoginLogoutNotificationsPerMinute: -1
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      otut: true
      resend: true
      resworld: true
      creative: false
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: -1
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 0.5
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: false
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: -1
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust: []
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: -1
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: false
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
Plugins (34): CoreProtect, LuckPerms, Wild, OpenInv, PlaceholderAPI, PlugMan, NoSpawnerChange, Votifier, Multiverse-Core, VotingPlugin, FastAsyncWorldEdit, iDisguise, Vault, Essentials, MyWarps, Parties, PerWorldInventory, HeadDatabase, LWC, HolographicDisplays, WorldGuard, DiscordSRV, AdvancedAchievements, EssentialsGeoIP, EssentialsChat, EssentialsAntiBuild, ServerSigns, GriefPrevention, EssentialsSpawn, EnjinMinecraftPlugin, WorldGuardExtraFlags, ChestShop, ArmorStandTools, HorseTpWithMe
