### ISSUE TITLE
Explosions

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#42]
I have BlockLandClaimExplosions set to true as I do not want explosions in a claim. But I do want explosions outside of a claim but explosions don't happen. I have both BlockSurfaceCreeperExlposions and BlockSurfaceOtherExplosions set to false. If I set BlockLandClaimExplosions to false, explosions will work both outside and inside of claims.

### What behaviour is expected:
 Explosions in claims are not possible but are possible outside of a claim.

### What behaviour is observed:
Explosions in claims are not possible and are not possible outside of a claim.
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Craftbukkit version git-Bukkit-33d5de3 (MC:1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
GriefPrevention version 11.2.2

### GriefPrevention config.yml (if applicable)

```yml
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world_the_end: Disabled
      world: Survival
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectFires: true
    ProtectHorses: true
    InitialBlocks: 100
    BlocksAccruedPerHour: 1000
    MaxAccruedBlocks: 420000000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 0
    ExtendIntoGroundDistance: 256
    MinimumSize: 5
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 0
      UnusedClaimDays: 0
      AllClaimDays: 0
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    MonitorSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 0
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  WhisperCommands: /tell;/pm;/r;/w;/whisper;/t;/msg
  SmartBan: false
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []

```
