### ISSUE TITLE
SurvivalRequiringClaims

### ISSUE THREAD

**Issue by ResqDiver1317** [GriefPrevention/GriefPrevention#420]
I understand this is an old version, but we just launched a 1.7.10 retro pack for our community based on our first modded server pack we had. Hopefully someone can provide some insight.

### What happened:
I set our config for SurvivalRequiringClaims for the overworld, but anytime we restart the server, it reverts back to just Survival and is allowing players to break/place blocks in the wild.

### What you expected:
I expected to see it stay in the requiringclaims mode.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
Edit config to survivalrequiringlclaims, upload config, restart server.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Thermos 1.7.10-R.01-Snapshot 1614.58
GriefPrevention 9.1 (latest version that I "think" I can use for 1.7.10 as the next version says it's for 1.8

### Stack trace/error or server log

```
https://gist.github.com/ResqDiver1317/00947995f8d6a7a8cc4037b398612355#file-fml-server-latest-log
```

### GriefPrevention config.yml

```yml  (after a restart, the line for Survival changes back to just mode Survival)

GriefPrevention:
  SeaLevelOverrides:
    Survival: -1
    DIM-7: -1
    DIM-100: -1
    DIM-37: -1
    DIM-38: -1
    DIM-39: -1
    DIM-42: -1
    DIM-19: -1
    DIM-112: -1
    DIM-343: -1
    DIM-1: -1
    DIM1: -1
  Claims:
    Mode:
      DIM-7: Disabled
      DIM-19: Disabled
      DIM-112: Disabled
      DIM-1: Disabled
      DIM-38: Disabled
      DIM-100: Disabled
      DIM-37: Disabled
      DIM-343: Disabled
      DIM-39: Disabled
      DIM-42: Disabled
      Survival: SurvivalRequiringClaims
      DIM1: Disabled
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectFires: false
    ProtectHorses: true
    InitialBlocks: 0
    BlocksAccruedPerHour: 25
    MaxAccruedBlocks: 80000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 0
    ExtendIntoGroundDistance: 256
    CreationRequiresPermission: false
    MinimumSize: 10
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaimDays: 0
      AutomaticNatureRestoration:
        SurvivalWorlds: false
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    MonitorSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
  PvP:
    Worlds:
    - Survival
    - DIM-7
    - DIM-100
    - DIM-37
    - DIM-38
    - DIM-39
    - DIM-42
    - DIM-19
    - DIM-112
    - DIM-343
    - DIM-1
    - DIM1
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
  Economy:
    ClaimBlocksPurchaseCost: 10.0
    ClaimBlocksSellValue: 5.0
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  EavesdropEnabled: false
  WhisperCommands: /tell;/pm;/r;/w;/t;/msg
  SmartBan: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 227:*:Battery Box
    - 130:*:Transmutation Tablet
    - 128:*:Alchemical Chest and Energy Condenser
    - 181:*:Various Chests
    - 178:*:Ender Chest
    - 150:*:Various BuildCraft Gadgets
    - 155:*:Filler
    - 157:*:Builder
    - 158:*:Template Drawing Table
    - 126:*:Various EE Gadgets
    - 138:*:Various RedPower Gadgets
    - 137:*:BuildCraft Project Table and Furnaces
    - 250:*:Various IC2 Machines
    - 161:*:BuildCraft Engines
    - 169:*:Automatic Crafting Table
    - 177:*:Wireless Components
    - 183:*:Solar Arrays
    - 187:*:Charging Benches
    - 188:*:More IC2 Machines
    - 190:*:Generators, Fabricators, Strainers
    - 194:*:More Gadgets
    - 207:*:Computer
    - 208:*:Computer Peripherals
    - 246:*:IC2 Generators
    - 24303:*:Teleport Pipe
    - 24304:*:Waterproof Teleport Pipe
    - 24305:*:Power Teleport Pipe
    - 4311:*:Diamond Sorting Pipe
    - 216:*:Turtle
    BlockIdsExplodable:
    - 161:*:BuildCraft Engines
    - 246:5:Nuclear Reactor
    PlayersIgnoringAllClaims: []


```

### Plugin list (if applicable):
AreaShop
BetterChunkLoader
ChestShop
Clearlag
DiscrdSRV
EnjinMinecraftPlugin
EssentialsX
EssentialsXChat
EssentialsXSpawn
GriefPrevention
KaisRandomTP
LuckPerms
PlugMan
TimeIsMoney
WorldBorder
WorldEdit
worldguard
