### ISSUE TITLE
lockdrops

### ISSUE THREAD

**Issue by LogGits** [GriefPrevention/GriefPrevention#426]
I noticed there was a way to unlock drops:
```yaml
    unlockdrops:
      description: Allows other players to pick up the items you dropped when you died.
      usage: /UnlockDrops
      permission: griefprevention.unlockdrops
```
However, I cant seem to find a way to lock the drops again using a command. Is there actually a command for this? If not, it would be nice to have 👍
