### ISSUE TITLE
messages.yml will be reset everytime

### ISSUE THREAD

**Issue by Nekoret** [GriefPrevention/GriefPrevention#466]
### What happened:
_What you saw_
I change the messages.yml to Chinese in the plugin. However, after I restart server, it turn to English every time.
### What you expected:
_What you expected to see_
The Chinese version can work and show in the server
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. reload server
2. open the messages.yml is in English and paste Chinese version save.
3. reload server again
4. check in the game, and it still in English

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 1.13.2
Paste of `/version GriefPrevention`:16.11.4

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention messages.yml

```yml

# Use a YAML editor like NotepadPlusPlus to edit this file.
# After editing, back up your changes before reloading the server in case you made a syntax error.
# Use dollar signs ($) for formatting codes, which are documented here: http://minecraft.gamepedia.com/Formatting_codes
Messages:
  RespectingClaims:
    Text: '開啟領地防護(OP)'
  IgnoringClaims:
    Text: '關閉領地防護(OP)'
  SuccessfulAbandon:
    Text: '放棄了領地 現在你有 {0} 格領地'
    Notes: '0: remaining blocks'
  RestoreNatureActivate:
    Text: 'Ready to restore some nature!  Right click to restore nature, and use /BasicClaims to stop'
  RestoreNatureAggressiveActivate:
    Text: 'Aggressive mode activated.  Do NOT use this underneath anything you want to keep!  Right click to aggressively restore nature, and use/BasicClaims to stop'
  FillModeActive:
    Text: 'Fill mode activated with radius {0}.  Right click an area to fill'
    Notes: '0: fill radius'
  TransferClaimPermission:
    Text: '此命令需要領地主人的權限'
  TransferClaimMissing:
    Text: '這邊沒有領地  站在你想要轉移的領地內'
  TransferClaimAdminOnly:
    Text: 'Only administrative claims may be transferred to a player'
  PlayerNotFound2:
    Text: '找不到此玩家'
  TransferTopLevel:
    Text: '只能轉移最高級的領地(不包含子領地) 請站在子領地外再試一次'
  TransferSuccess:
    Text: '領地轉移成功'
  TrustListNoClaim:
    Text: '站在你想查詢的領地內'
  ClearPermsOwnerOnly:
    Text: '只有領地主人能夠清除所有權限'
  UntrustIndividualAllClaims:
    Text: '撤銷 {0}的所有分享權限  如果你想設定單一權限 請站在領地內'
    Notes: '0: untrusted player'
  UntrustEveryoneAllClaims:
    Text: '撤銷領地的所有分享權限 如果你想設定單一權限 請站在領地內'
  NoPermissionTrust:
    Text: '你沒有 {0} 的許可權限'
    Notes: '0: claim owner's name'
  ClearPermissionsOneClaim:
    Text: '清除領地內的所有權限 如果想要一次設定所有領地的權限 請站在領地外'
  UntrustIndividualSingleClaim:
    Text: '撤消 {0}的分享權限  如果想要一次設定所有領地的權限 請站在領地外'
    Notes: '0: untrusted player'
  OnlySellBlocks:
    Text: '領地只能售出而不能購買'
  BlockPurchaseCost:
    Text: '每隔領地需花費 {0}.  你的金錢目前是 {1}'
    Notes: '0: cost of one block; 1: player's account balance'
  ClaimBlockLimit:
    Text: '你已達到最高領地擁有上限 無法再購買更多'
  InsufficientFunds:
    Text: '你沒有足夠的金錢 你總共需要 {0}, 但你只有 {1}'
    Notes: '0: total cost; 1: player's account balance'
  PurchaseConfirmation:
    Text: '從你的金錢中收取 {0}  你現在擁有 {1} 格領地'
    Notes: '0: total cost; 1: remaining blocks'
  OnlyPurchaseBlocks:
    Text: '領地只能購買而不能賣出'
  BlockSaleValue:
    Text: '每隔領地價值 {0}.  你有 {1} 格領地可以賣出'
    Notes: '0: block value; 1: available blocks'
  NotEnoughBlocksForSale:
    Text: '你沒有這麼多領地可以賣出'
  BlockSaleConfirmation:
    Text: '在你的帳戶中存入 {0}  現在你有 {1} 格領地'
    Notes: '0: amount deposited; 1: remaining blocks'
  AdminClaimsMode:
    Text: 'Administrative claims mode active.  Any claims created will be free and editable by other administrators'
  BasicClaimsMode:
    Text: '開啟一般領地模式'
  SubdivisionMode:
    Text: '子領地模式 使用金鏟細分領地 或是輸入 /basicclaims 結束子領地模式'
  SubdivisionVideo2:
    Text: '點擊獲得幫助 {0}'
    Notes: 0:video URL
  DeleteClaimMissing:
    Text: '此處無領地'
  DeletionSubdivisionWarning:
    Text: '這個領地包含子領地 如果確定一起刪除 請再一次輸入 /DeleteClaim '
  DeleteSuccess:
    Text: '已刪除領地'
  CantDeleteAdminClaim:
    Text: '你沒有權限刪除管理員領地'
  DeleteAllSuccess:
    Text: '刪除 {0} 所有的領地'
    Notes: '0: owner's name'
  NoDeletePermission:
    Text: '你沒有刪除該領地的權限'
  AllAdminDeleted:
    Text: '刪除所有管理員領地'
  AdjustBlocksSuccess:
    Text: '調整 {0}領地格數從 {1} 增加到 {2}'
    Notes: '0: player; 1: adjustment; 2: new total'
  NotTrappedHere:
    Text: '已到安全地區'
  RescuePending:
    Text: '請不要移動 將在十秒內傳送至安全地區'
  NonSiegeWorld:
    Text: '圍城已結束'
  AlreadySieging:
    Text: '你已參與圍城'
  NotSiegableThere:
    Text: '{0} 無該領地保護'
    Notes: '0: defending player'
  SiegeTooFarAway:
    Text: 'You re too far away to siege''
  NoSiegeYourself:
    Text: 'You cannot siege yourself, don t be silly'
  NoSiegeDefenseless:
    Text: 'That player is defenseless.  Go pick on somebody else'
  AlreadyUnderSiegePlayer:
    Text: '{0} is already under siege.  Join the party!'
    Notes: '0: defending player'
  AlreadyUnderSiegeArea:
    Text: 'That area is already under siege.  Join the party!'
  NoSiegeAdminClaim:
    Text: 'Siege is disabled in this area'
  SiegeOnCooldown:
    Text: 'You're still on siege cooldown for this defender or claim.  Find another
      victim''
  SiegeAlert:
    Text: 'You're under siege!  If you log out now, you will die.  You must defeat
      {0}, wait for him to give up, or escape'
    Notes: '0: attacker name'
  SiegeConfirmed:
    Text: 'The siege has begun!  If you log out now, you will die.  You must defeat
      {0}, chase him away, or admit defeat and walk away'
    Notes: '0: defender name'
  AbandonClaimMissing:
    Text: '站在你想要刪除的領地內 或是使用 /AbandonAllClaims 以刪除所有領地'
  NotYourClaim:
    Text: '這不是你的領地'
  DeleteTopLevelClaim:
    Text: '如果要刪除子領地 請站在領地內 或是使用 /AbandonTopLevelClaim 來刪除所有子領地'
  AbandonSuccess:
    Text: '放棄領地  你現在擁有 {0} 格領地'
    Notes: '0: remaining claim blocks'
  CantGrantThatPermission:
    Text: '你不能給予你自己沒有的權限'
  GrantPermissionNoClaim:
    Text: '站在你想要給予的領地再給予權限'
  GrantPermissionConfirmation:
    Text: '給與 {0} 權限 {1} 在 {2}'
    Notes: '0: target player; 1: permission description; 2: scope (changed claims)'
  ManageUniversalPermissionsInstruction:
    Text: '一次管理所有權限 請站在領地外面'
  ManageOneClaimPermissionsInstruction:
    Text: '管理單個領地權限 請站在領地裡面'
  CollectivePublic:
    Text: '開放'
    Notes: as in 'granted the public permission to..'
  BuildPermission:
    Text: '建築許可'
  ContainersPermission:
    Text: '容器與動物許可'
  AccessPermission:
    Text: '按鈕與拉桿許可'
  PermissionsPermission:
    Text: '管理權限'
  LocationCurrentClaim:
    Text: '在領地內'
  LocationAllClaims:
    Text: '所有領地'
  PvPImmunityStart:
    Text: '只要你的背包是空的 就無法受到玩家攻擊'
  SiegeNoDrop:
    Text: 'You can't give away items while involved in a siege.
  DonateItemsInstruction:
    Text: '要丟棄左手上的物品 請再次左鍵箱子'
  ChestFull:
    Text: '這個箱子是滿的'
  DonationSuccess:
    Text: '傳送物品至箱子內!'
  PlayerTooCloseForFire2:
    Text: '你不能對一個鄰近的玩家開火'
  TooDeepToClaim:
    Text: '這個箱子在地底下太深處 無法受到保護'
  ChestClaimConfirmation:
    Text: '這個箱子受到保護'
  AutomaticClaimNotification:
    Text: '這個箱子可以防止受到破壞'
  UnprotectedChestWarning:
    Text: '這個箱子沒有紹到保護 請考慮拓寬領地'
  ThatPlayerPvPImmune:
    Text: '你不能攻擊手無寸鐵的玩家'
  CantFightWhileImmune:
    Text: '你身上必須要有物品才能攻擊另一位玩家'
  NoDamageClaimedEntity:
    Text: '這屬於 {0}'
    Notes: '0: owner name'
  ShovelBasicClaimMode:
    Text: '切換至一般領地模式'
  RemainingBlocks:
    Text: '你還可以再設置 {0} 格領地'
    Notes: '0: remaining blocks'
  CreativeBasicsVideo2:
    Text: '點擊獲得幫助: {0}'
    Notes: '{0}: video URL'
  SurvivalBasicsVideo2:
    Text: '點擊獲得幫助: {0}'
    Notes: '{0}: video URL'
  TrappedChatKeyword:
    Text: '陷阱;卡住'
    Notes: When mentioned in chat, players get information about the /trapped command
      (multiple words can be separated with semi-colons)
  TrappedInstructions:
    Text: '你卡在別人的領地/陷阱內了嗎 試試看輸入/trapped '
  PvPNoDrop:
    Text: 'PVP中部可以丟棄物品'
  SiegeNoTeleport:
    Text: 'You can't teleport out of a besieged area.
  BesiegedNoTeleport:
    Text: 'You can't teleport into a besieged area.
  SiegeNoContainers:
    Text: 'You can't access containers while involved in a siege.
  PvPNoContainers:
    Text: '在PVP狀態中無法開啟'
  PvPImmunityEnd:
    Text: '現在你可以攻擊其他玩家了'
  NoBedPermission:
    Text: '{0} 沒有給予你權限使用床'
    Notes: '0: claim owner'
  NoWildernessBuckets:
    Text: '你只能儲存在有你的領地的地方'
  NoLavaNearOtherPlayer:
    Text: '你不能在 {0} 領地附近放岩漿'
    Notes: '0: nearby player'
  TooFarAway:
    Text: '太遠了'
  BlockNotClaimed:
    Text: '沒有人的領地'
  BlockClaimed:
    Text: '這裡是 {0} 的領地'
    Notes: '0: claim owner'
  SiegeNoShovel:
    Text: 'You can't use your shovel tool while involved in a siege'
  RestoreNaturePlayerInChunk:
    Text: 'Unable to restore.  {0} is in that chunk'
    Notes: '0: nearby player'
  NoCreateClaimPermission:
    Text: '你沒有權限劃設領地'
  ResizeNeedMoreBlocks:
    Text: '你沒有足夠的領地數目  你還需要 {0} 格'
    Notes: '0: how many needed'
  NoCreativeUnClaim:
    Text: '你無法取消這塊領地 但可以使用金鏟拓寬領地或創建其他領地'
  ClaimResizeSuccess:
    Text: '已重新調整領地大小 你還有 {0} 格領地'
    Notes: '0: remaining blocks'
  ResizeFailOverlap:
    Text: '無法調整領地大小 附近有其他領地與你重疊'
  ResizeStart:
    Text: '重新調整領地中 請使用金鏟點擊新的領地大小位置'
  ResizeFailOverlapSubdivision:
    Text: '你不能在這邊創建子領地 因為它會與另一個子領地重疊 試試看使用 /abandonclaim 刪除子領地 或使用金鏟調整領地大小'
  SubdivisionStart:
    Text: '子領地設定! 使用金鏟調整新的子領地大小'
  CreateSubdivisionOverlap:
    Text: '你選擇的範圍跟另一個子領地重疊'
  SubdivisionSuccess:
    Text: '子領地以創建! 使用 /trust 分享權限給你的朋友們'
  CreateClaimFailOverlap:
    Text: '你不能在這邊創建領地 因為它會與另一個領地重疊 試試看使用 /abandonclaim 刪除領地 或使用金鏟調整領地大小'
  CreateClaimFailOverlapOtherPlayer:
    Text: 'Y你不能在這邊創建領地 因為它會與 {0} 的領地重疊'
    Notes: '0: other claim owner'
  ClaimsDisabledWorld:
    Text: '無法在這個世界創建領地'
  ClaimStart:
    Text: '已選取領地角落，請在對角再次點選，即可創建領地。如果要取消劃設，請將金鏟放下。官網教學：http://www.meowwo.net/?p=594'
  NewClaimTooNarrow:
    Text: '這個領地範圍太小了! 至少需要 {0} 寬'
    Notes: '0: minimum claim width'
  CreateClaimInsufficientBlocks:
    Text: '你沒有足夠的領地劃設 你還需要 {0} 格'
    Notes: '0: additional blocks needed'
  AbandonClaimAdvertisement:
    Text: '如果要移除領地 請使用 /AbandonClaim'
  CreateClaimFailOverlapShort:
    Text: '你選取的範圍與現有領地重疊'
  CreateClaimSuccess:
    Text: '已成功創建領地!  使用 /trust 與你的朋友分享權限'
  SiegeWinDoorsOpen:
    Text: '恭喜!  按鈕跟門暫時解鎖'
  RescueAbortedMoved:
    Text: '你移動了! 取消安全區域傳送'
  SiegeDoorsLockedEjection:
    Text: 'Looting time is up!  Ejected from the claim'
  NoModifyDuringSiege:
    Text: 'Claims can't be modified while under siege'
  OnlyOwnersModifyClaims:
    Text: '只有 {0} 可以修改領地'
    Notes: '0: owner name'
  NoBuildUnderSiege:
    Text: 'This claim is under siege by {0}.  No one can build here'
    Notes: '0: attacker name'
  NoBuildPvP:
    Text: '你不能在PVP中建設'
  NoBuildPermission:
    Text: '你沒有 {0} 給予的建築權限'
    Notes: '0: owner name'
  NonSiegeMaterial:
    Text: 'That material is too tough to break'
  NoOwnerBuildUnderSiege:
    Text: 'You can't make changes while under siege.
  NoAccessPermission:
    Text: '你沒有 {0} 的使用權限'
    Notes: '0: owner name.  access permission controls buttons, levers, and beds'
  NoContainersSiege:
    Text: 'This claim is under siege by {0}.  No one can access containers here right
      now'
    Notes: '0: attacker name'
  NoContainersPermission:
    Text: '你沒有 {0} 的使用權限'
    Notes: '0: owner's name.  containers also include crafting blocks'
  OwnerNameForAdminClaims:
    Text: '管理員'
    Notes: as in 'You don't have an administrator's permission to build here'
  ClaimTooSmallForEntities:
    Text: '這個領地不夠大 請試著拓寬它'
  TooManyEntitiesInClaim:
    Text: '這個領地已經有太多的實體方塊或是生物 請試著擴大領地或是刪除一些動物、展示框、礦車'
  YouHaveNoClaims:
    Text: '你沒有任何領地'
  ConfirmFluidRemoval:
    Text: '刪除領地將會一併移除領地內的岩漿 如果確定執行請再次輸入/AbandonClaim'
  AutoBanNotify:
    Text: 'Auto-banned {0}({1}).  See logs for details'
  AdjustGroupBlocksSuccess:
    Text: 'arnn加權領地格數 {0} 權限 {1}.  總共為: {2}'
    Notes: '0: permission; 1: adjustment amount; 2: new total bonus'
  InvalidPermissionID:
    Text: '請在括號中指定玩家ID'
  HowToClaimRegex:
    Text: '(^|.*\W)how\W.*\W(claim|protect|lock)(\W.*|$)'
    Notes: This is a Java Regular Expression.  Look it up before editing!  It's used
      to tell players about the demo video when they ask how to claim land.
  NoBuildOutsideClaims:
    Text: '除非有創建領地 否則無法直接建造'
  PlayerOfflineTime:
    Text: '  上次登入時間: {0} 天前'
    Notes: '0: number of full days since last login'
  BuildingOutsideClaims:
    Text: '其他玩家也可以在這邊建造 請考慮使用領地保護 http://www.meowwo.net/?p=594'
  TrappedWontWorkHere:
    Text: '抱歉 目前找不到安全的地點 請聯絡管理員'
  CommandBannedInPvP:
    Text: '在PVP中無法使用這個指令'
  UnclaimCleanupWarning:
    Text: '無人認領的領地可能會被其他玩家/管理員清理或是創建領地'
  BuySellNotConfigured:
    Text: '抱歉 無法使用購買或是販賣領地格數'
  NoTeleportPvPCombat:
    Text: '當你與其他玩家戰鬥時無法傳送'
  NoTNTDamageAboveSeaLevel:
    Text: '警告: TNT 無法破壞海平面以上的物品'
  NoTNTDamageClaims:
    Text: '警告: TNT 不會破壞領地內的方塊'
  IgnoreClaimsAdvertisement:
    Text: '要覆蓋權限 請使用 /IgnoreClaims'
  NoPermissionForCommand:
    Text: '你沒有權限使用這個命令'
  ClaimsListNoPermission:
    Text: '你沒有權限獲得其他玩家的領地資訊'
  ExplosivesDisabled:
    Text: '這個領地目前可以防爆 使用 /ClaimExplosions 切換狀態'
  ExplosivesEnabled:
    Text: '開啟領地內爆炸 再次使用 /ClaimExplosions 返回爆炸保護'
  ClaimExplosivesAdvertisement:
    Text: '如果要開啟領地內爆炸 請使用/ClaimExplosions'
  PlayerInPvPSafeZone:
    Text: '那個玩家在PVP安全地區'
  NoPistonsOutsideClaims:
    Text: '警告: 活塞不能在領地外使用'
  SoftMuted:
    Text: 'Soft-muted {0}'
    Notes: '0: The changed player's name'
  UnSoftMuted:
    Text: 'Un-soft-muted {0}'
    Notes: '0: The changed player's name'
  DropUnlockAdvertisement:
    Text: '其他玩家不能撿起你領地內的物品 使用 /UnlockDrops 開啟領地掉落'
  PickupBlockedExplanation:
    Text: '你不能撿起物品 除非 {0} 開啟 /UnlockDrops.'
    Notes: '0: The item stack's owner'
  DropUnlockConfirmation:
    Text: '鎖定領地掉落  其他玩家可以撿起掉落物直到你再次輸入此指令'
  DropUnlockOthersConfirmation:
    Text: '鎖定 {0} 的領地掉落'
    Notes: '0: The owner of the unlocked drops'
  AdvertiseACandACB:
    Text: '你可以使用 /ACB 給予你自己更多的領地 或是使用 /AdminClaims 創建免費管理員領地'
  AdvertiseAdminClaims:
    Text: 'You could create an administrative land claim instead using /AdminClaims,
      which you'd share with other administrators'
  AdvertiseACB:
    Text: '你可以使用 /ACB 給予你自己更多的領地'
  NotYourPet:
    Text: '只有 {0} 有權力給予寵物 請使用 /GivePet 轉移寵物'
    Notes: '0: owner name'
  PetGiveawayConfirmation:
    Text: '寵物轉移'
  PetTransferCancellation:
    Text: '取消寵物轉移'
  ReadyToTransferPet:
    Text: '準備好轉移  右鍵你要給予他人的寵物或是使用 /GivePet 取消'
  AvoidGriefClaimLand:
    Text: '劃設領地! 學會劃設領地後即可獲得物資的完整保護'
  BecomeMayor:
    Text: '細分你的子領地!'
  ClaimCreationFailedOverClaimCountLimit:
    Text: '你已達到領地擁有值的最高上限  使用 /AbandonClaim 刪除一些用不到的領地'
  CreateClaimFailOverlapRegion:
    Text: '你不能在這劃設領地'
  ResizeFailOverlapRegion:
    Text: '你沒有權限建設 所以無法劃設領地'
  NoBuildPortalPermission:
    Text: '你沒有 {0} 的權限建設 所以無法劃設領地'
    Notes: '0: Destination land claim owner's name'
  ShowNearbyClaims:
    Text: '搜尋到 {0} 領地'
    Notes: '0: Number of claims found'
  NoChatUntilMove:
    Text: '請在發言前移動一下 好讓系統確認非機器人'
  SiegeImmune:
    Text: 'That player is immune to /siege'
  SetClaimBlocksSuccess:
    Text: '成功更新領地'
  IgnoreConfirmation:
    Text: '無視該玩家的發言'
  NotIgnoringPlayer:
    Text: '可視該玩家的發言'
  UnIgnoreConfirmation:
    Text: '你無法無視該玩家的發言'
  SeparateConfirmation:
    Text: '這些玩家現在互相禁言對方'
  UnSeparateConfirmation:
    Text: '這些玩家不再互相禁言對方'
  NotIgnoringAnyone:
    Text: '你沒有無視任何人的發言'
  TrustListHeader:
    Text: '所有權限:'
  Manage:
    Text: 'PT管理權'
  Build:
    Text: 'TR建築權'
  Containers:
    Text: 'CT容器權'
  Access:
    Text: 'AT存取權'
  HasSubclaimRestriction:
    Text: '此子領地不繼承原領地的權限'
  StartBlockMath:
    Text: '{0} 方塊 + {1} 額外方塊 = 總共 {2} 格領地'
  ClaimsListHeader:
    Text: '全領地:'
  ContinueBlockMath:
    Text: ' (-{0} blocks)'
  EndBlockMath:
    Text: ' = {0} 剩餘領地'
  NoClaimDuringPvP:
    Text: '你不能在PVP中劃設領地'
  UntrustAllOwnerOnly:
    Text: '只有領地主人才能清除所有權限'
  ManagersDontUntrustManagers:
    Text: '只有領地主人才能調整權限給予'
  BookAuthor:
    Text: 'Nekoret'
  BookTitle:
      Text: '如何劃設領地'
  BookIntro:
    Text: '使用領地來保護你的資產  點擊金鏟領地詳細教學：http://www.meowwo.net/?p=594'
  BookDisabledChestClaims:
    Text: '  On this server, placing a chest will NOT claim land for you'
  BookUsefulCommands:
    Text: 'Useful Commands:'
  BookLink:
    Text: 'Click: {0}'
    Notes: '{0}: video URL'
  BookTools:
    Text: 'Our claim tools are {0} and {1}'
    Notes: '0: claim modification tool name; 1:claim information tool name'
  ResizeClaimTooNarrow:
    Text: 'This new size would be too small.  Claims must be at least {0} blocks wide'
    Notes: '0: minimum claim width'
  ResizeClaimInsufficientArea:
    Text: 'This claim would be too small.  Any claim must use at least {0} total claim'
      blocks.
    Notes: '0: minimum claim area'
  NoProfanity:
    Text: 'Please moderate your language'
  PlayerNotIgnorable:
    Text: 'You can't ignore that player.
  NoEnoughBlocksForChestClaim:
    Text: 'Because you don't have any claim blocks available, no automatic land claim
      was created for you.  You can use /ClaimsList to monitor your available claim
      block total.
  IsIgnoringYou:
    Text: '此玩家已禁言你'
  MustHoldModificationToolForThat:
    Text: '你需要拿著金鏟才能使用'
  StandInClaimToResize:
    Text: '站在你想要調整領地大小的領地內'
  ClaimsExtendToSky:
    Text: '領地保障從天到地的範圍'
  ClaimsAutoExtendDownward:
    Text: '當你設置領地時 領地會自動延伸從天至地'
  MinimumRadius:
    Text: 'Minimum radius is {0}'
    Notes: '0: minimum radius'
  RadiusRequiresGoldenShovel:
    Text: 'You must be holding a golden shovel when specifying a radius'
  ClaimTooSmallForActiveBlocks:
    Text: '領地太小了 請拓展領地再使用活動型方塊 ex 漏斗'
  TooManyActiveBlocksInClaim:
    Text: '領地處於極限了 請拓展領地再使用活動型方塊 ex 漏斗'
  ConsoleOnlyCommand:
    Text: '這個指令只能在後台黑盒子使用'
  WorldNotFound:
    Text: '找不到此世界'
  AdjustBlocksAllSuccess:
    Text: '增加所有線上玩家的領地 {0}'
    Notes: '0: adjustment amount'
  TooMuchIpOverlap:
    Text: 'Sorry, there are too many players logged in with your IP address'
  StandInSubclaim:
    Text: 'You need to be standing in a subclaim to restrict it'
  SubclaimRestricted:
    Text: 'This subclaim's permissions will no longer inherit from the parent claim'
  SubclaimUnrestricted:
    Text: 'This subclaim's permissions will now inherit from the parent claim'
  NetherPortalTrapDetectionMessage:
    Text: 'It seems you might be stuck inside a nether portal. We will rescue you in
      a few seconds if that is the case!'
    Notes: Sent to player on join, if they left while inside a nether portal.

```
