### ISSUE TITLE
Thread hang on mysql access

### ISSUE THREAD

**Issue by Darkweasam** [GriefPrevention/GriefPrevention#468]
### What happened:
Something probably went wrong in GriefPrevention plugin, everyone got timed out

### Steps to reproduce:
Have no idea

### Server and GriefPrevention version:
Paste of `/version`: Paper version git-Paper-1449 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.8

### Stack trace/error or server log
Nothing seemed

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    resource: -1
    SpawnV2: -1
    dungeons: -1
    copy: -1
    TwilightWorld: -1
  Claims:
    Mode:
      copy: Survival
      world_the_end: Disabled
      dungeons: Disabled
      SpawnV2: Disabled
      world: Survival
      world_nether: Disabled
      resource: Disabled
      TwilightWorld: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: false
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 200000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 1
    MinimumArea: 1
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 60
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: '&2Please stop spamming...'
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: true
      world_the_end: true
      resource: true
      SpawnV2: true
      dungeons: true
      copy: true
      TwilightWorld: true
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/warp;/fly
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: false
    AllowFlintAndSteelNearOtherPlayers: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    UserName: xxxxxxxxxxxx
    Password: xxxxxxxxxx
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust: []
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 60
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


```
MOST IMPORTANT IMAGE: https://i.imgur.com/BPQVaJn.png

**Comment by RoboMWM** [comment]
Need link to timings

**Comment by Darkweasam** [comment]
https://timings.aikar.co/?id=0b61d3dca0304fb899f5e8a197fac144

You have to move those small slides on the top of the screen to select the correct period

**Comment by RoboMWM** [comment]
Your paper version is nearly 150 versions out of date. Newer Paper builds print out stacktraces when server spikes occur.

**Comment by RoboMWM** [comment]
As for the lag spike - might be related to the issue seen in #427 with your MySQL server lagging out at that time.

**Comment by RoboMWM** [comment]
Btw, I went ahead and deleted the revision from the edit history, but obviously would be a good idea to change your credentials if possible

**Comment by Darkweasam** [comment]
https://timings.aikar.co/?id=3cdd0e1f998443a3a58d336bf9634874
My server crashes almost every single day at almost the same time, luckily it didnt crash it this time so I could make a timings report

Thu, 21. Feb 2019 19:24:28 EST 
Tue, 19. Feb 2019 19:18:44 EST 
Mon, 18. Feb 2019 19:28:45 EST 
Sun, 17. Feb 2019 19:24:31 EST 
Sat, 16. Feb 2019 18:55:20 EST 
Fri, 15. Feb 2019 19:29:53 EST ...

Here is log
https://pastebin.com/1ZJj09nf

P.S Actually I am unsure if this is the same thing and should I've made a new issue form instead of replying to this

**Comment by bigpresh** [comment]
Yeah, I don't think it'll be the same cause as the other user's issue, so I've raised #468 for you and will respond on that.

**Comment by RoboMWM** [comment]
@bigpresh, @Darkweasam is the author of this ticket...

**Comment by RoboMWM** [comment]
> https://timings.aikar.co/?id=3cdd0e1f998443a3a58d336bf9634874

This was the result of a user running /abandonallclaims, and I guess some of these claims are in creative worlds so they trigger a cleanup task. Since this is also a data operation, this also points to a slow SQL connection/server.

Also, you still haven't updated Paper btw.

v20 is implementing async operations for data manipulation - though you really should get that SQL server/connection checked out, seems like some sort of maintenance task is happening consistently at that time?

**Comment by RoboMWM** [comment]
Also, a significant reason why you should update Paper is because of what I mentioned nearly a month ago:

> Newer Paper builds print out stacktraces when server spikes occur.

Having this stacktrace will allow us to pinpoint exactly where the issue is occurring.

**Comment by bigpresh** [comment]
Oh, LOL - I completely missed that it was an update from the same person.  My apologies.

I read it as a different user commenting on this one because it's vaguely-related rather than raise their own, hence raising a new one for it.  I closed this one, because it hadn't been touched in nearly a month since you suggested a newer Paper build.

**Comment by RoboMWM** [comment]
I don't close due to inactivity unless it's been way over a year or something and/or some sort of tentative resolution has been stated. IMO I rather have comments on something vaguely related instead of a new issue - if it turns out to not be related at all, then I'll just comment stating to make a new issue. It's far more often the case to have duplicate issues created than people "hijacking" tickets.

**Comment by Darkweasam** [comment]
Updated to the yesterday's version of paper

```
INFO This server is running Paper version git-Paper-1599 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) 
26.02 04:27:49 [Server] INFO Previous version: git-Paper-1449 (MC: 1.12.2) 
26.02 04:27:49 [Server] INFO Checking version, please wait... 
26.02 04:27:50 [Server] INFO You are 1 version(s) behind
```


Lagg spike happened again at Mon, 25. Feb 2019 19:31:26 EST (Almost same +-10mins again as usual)
https://timings.aikar.co/?id=8e8d4d6d458d47d68f4d0e5a020c3ef0
(Please move the dots to the correct place again, to the giant red spike)


Contacted our hosting about mysql they said

> There's no maintenance task happening, the problem is probably related to the size of our SQL server and the specifications of it. We use a platter disk for our database server, and unfortunately, given the size of some databases, that can cause some performance issues with seek times. The database is hosted in the same datacenter as the NA nodes, and the latency is very small to our EU location -- none of these would be probable cause for the issues you are having
The only thing that I could do is improve the caching to save some common databases into memory, but even then all that's going to do is eat memory for those who have massive databases
If you're going to have a database that's over 10-20GB in size, a VPS is a viable option for you
(They improved the caching to me)

My mysql was 14GBs, however I purged the database so now it takes only 4GBs of place, but as you see the giant lagg spike happened again

Here is a log, contains useful information now because of the updated paper
https://pastebin.com/iAvcb28K

**Comment by RoboMWM** [comment]
Oh, so you're on shared hosting. So I'm guessing others are using the SQL server as well. Perhaps someone/a lot of usage is occurring at that time?

Thank you for the log, that's very helpful. As you can see in the stacktrace, the MySQL driver is waiting for a reply (hanging on the `socketRead()` method) from the MySQL server. The query for updating the `nextClaimID` value and saving the claim are shown in both stacktraces, which suggests that the SQL server is responding slowly to both queries.

Since it's happening at a particular time, as I mentioned at the beginning of this comment, there seems to be some sort of excessive use with anything related to the SQL server. Either it's the server itself not being able to handle the queries quickly at this time or the connection to it being choked out. Since it's happening at a regular time perhaps you can ask them to see if they have any logs of queries being executed around that time. Maybe someone else who uses the SQL server is running an unoptimized query at this time daily? It could even be a plugin performing SQL queries at this time (asynchronously).

As I mentioned in a comment earlier, the entire datastore system will be asynchronous in v20 (as it should be), which will make it far more resilient to these sorts of I/O issues.

**Comment by RoboMWM** [comment]
As an FYI: aside from server start, the only other times the SQL database is queried is when:
- a claim is created, resized, or removed
- players are trusted/untrusted
- claim cleanup task, when checking the owner's playerdata if they haven't logged in within the last 90 days (or for newer GP versions, whatever `offline_cache_days` is set in the config)

**Comment by RoboMWM** [comment]
To summarize, there are two issues:
- Design flaw in GP, having nearly all I/O operations synchronous (addressed in v20)
- SQL server/connection issue (which we can't do anything about, see prior comment for advice)

**Comment by Darkweasam** [comment]
```
    Expiration:
      ChestClaimDays: 60
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
```
I do have claim cleanup, if I disable this could that solve the problem? Since there is no true/false option I believe setting them to -1 would work?

Also what do you mean by     * (addressed in v20)
The current version I see is 16.11.5
And as far I know the latest version for 1.12.2 is 16.8

**Comment by RoboMWM** [comment]
v20 is the upcoming rewrite of GP.

Disabling claim cleanup won't resolve this issue, as the database is also accessed on claim create, resize, delete, and trustlist modification.

**Comment by Darkweasam** [comment]
Two things to add
I rebooted my server at 19:08EST manually, then it crashed again at19:54EST
Also turned out that ANY kind of unexpected shutdown will reset claimblocks in griefprevention (if using mysql)
I believe there is no way going back to flatfile without reseting the whole database sadly...

**Comment by RoboMWM** [comment]
Claimblocks are saved on player logout iirc.

Though I agree that all database access should be async, your MySQL server/connection shouldn't be that slow.

I wonder if anyone built a converter back. If you want you could request I make one

**Comment by Darkweasam** [comment]
I would love to have a converter backwards please! Thanks!

**Comment by RoboMWM** [comment]
https://www.spigotmc.org/threads/requests-for-robomwm.293977/

**Comment by Darkweasam** [comment]
"Thread is too old to reply to"

I put my stuff here in case I can reply again to that thread so I can just copy this: 
> Hello, I would like to request a converter that converts back griefprevention data from mysql to flatfile
https://github.com/TechFortress/GriefPrevention/issues/468

Also, It would be cool to have something like /gp purge t:60d
So I could purge manually old data myself If I have the automated one disabled, or I just want to purge data that are older than 30days while my autopurge is set on 60days for different reasons like storage management

**Comment by Darkweasam** [comment]
How come that I found a player who's been offline for 3months+3days and claim expiration is set on 60days

**Comment by Jikoo** [comment]
>How come that I found a player who's been offline for 3months+3days and claim expiration is set on 60days

How many claim blocks do they have? Your config:
```YAML
Griefprevention.Claims.Expiration.AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
```
