### ISSUE TITLE
Horses and Pigs despawning in creative plot

### ISSUE THREAD

**Issue by mattc4t** [GriefPrevention/GriefPrevention#495]
### What happened:
Animals spawned in a plot, using eggs in a world configured for Creative, are despawning after a period of time.

### What you expected:
Animals should not be despawning.  We have seen horses and pigs despawn after a while.

### Steps to reproduce:
In a world with GP configured with Creative:
1. Create a small plot (10x10 will  do)
2. Create a closed pen with fence
3. Spawn horses in the pen
4. At some random period of time, a horse will disappear - followed later by more horses.

### Server and GriefPrevention version:
GriefPrevention: v16.11.6.dev
Spigot: 1.13.2

### Stack trace/error or server log
N/A

### GriefPrevention config.yml

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Shipyard: -1
    Shipyard_the_end: -1
    BSkyBlock_world: -1
    BSkyBlock_world_nether: -1
    BSkyBlock_world_the_end: -1
    SkyGrid-world: -1
    SkyGrid-world_nether: -1
    SkyGrid-world_the_end: -1
    Mainland: -1
    test: -1
    neverland: -1
    GreyHavens: -1
    Nether3: -1
    paintball: -1
    nightmare: -1
    creative: -1
    GameLobby: -1
    MobArena: -1
    paradise: -1
  Claims:
    Mode:
      BSkyBlock_world_the_end: Disabled
      Shipyard: Disabled
      BSkyBlock_world_nether: Disabled
      GreyHavens: Disabled
      GameLobby: Disabled
      BSkyBlock_world: Disabled
      SkyGrid-world_the_end: Disabled
      creative: Disabled
      SkyGrid-world_nether: Disabled
      Mainland: Disabled
      neverland: Creative
      paintball: Disabled
      Shipyard_the_end: Disabled
      paradise: Disabled
      nightmare: Disabled
      SkyGrid-world: Disabled
      Nether3: Disabled
      test: Disabled
      MobArena: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 10000
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 100000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 10
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Shipyard: false
      Shipyard_the_end: true
      BSkyBlock_world: true
      BSkyBlock_world_nether: true
      BSkyBlock_world_the_end: true
      SkyGrid-world: true
      SkyGrid-world_nether: true
      SkyGrid-world_the_end: true
      Mainland: true
      test: true
      neverland: true
      GreyHavens: false
      Nether3: true
      paintball: true
      nightmare: false
      creative: false
      GameLobby: true
      MobArena: true
      paradise: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 10.0
    ClaimBlocksSellValue: 9.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 12
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
Plugins (65): Admin-Chat-Channel, AdminNotes, AntiWorldFly, BanManager, BentoBox, BookManager, BookShelf, BukkitCompat, ChatControl, CheckNameHistory, Citizens, ColorCodeTeacher, ColoredChat, ColoredSigns, CommandNPC, CoreProtect, CraftBook, CustomOreGen, DIYspy, Essentials, EssentialsChat, ExtraContexts, ExtraHardMode, FastAsyncWorldEdit, FirstJoinPlus, GriefPrevention, HolographicDisplays, Hordes, InfernalMobs, Jobs, LeadTheWay, LuckPerms, MaintenanceSpigot, MobArena, MobHeads, MonsterApocalypseRevamped, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MyCommand, MyWarp, OreAnnouncer, Paintball, PerWorldInventory, PickupArrows, PlaceholderAPI, PlayerDeathLocation, PlugMan, ProtocolLib, QuickShop, SafeTrade, Shopkeepers, Stables, Statscraft, TicketMaster, TouchscreenHolograms, TreeGravity, UndineMailer, VanishNoPacket, Vault, WorldBorder, WorldEdit, WorldGuard, XpBank, LWC
