### ISSUE TITLE
Claim still present with very inactive owner

### ISSUE THREAD

**Issue by MithrandirCraft** [GriefPrevention/GriefPrevention#496]
### What happened:
An inactive player still has their claim.
![Screenshot_1](https://user-images.githubusercontent.com/6623704/54481779-8a2c3700-4839-11e9-959d-c7e80cb11970.png)

### What you expected:
Claim should no longer be there. The player has exceeded the configured ammount of time (30 days) offline. No idea how many claimblocks the user has, but I highly doubt the threshold was reached (I'm pretty sure it's impossible). In any case, I wouldn't even know how to check this (DB maybe?)

### Steps to reproduce:
No idea man, it just happens. I also receive usual complaints about claims not unclaiming after the configured ammounts of time (like after 31, 32 days), allthough this is usually undone with some extra patience, and the claims dissapear.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:  git-Spigot-3cb9dcb-40cbae4 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: 16.11.5

### Stack trace/error or server log
No errors

Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Survival: -1
    Survival_nether: -1
    Survival_the_end: -1
    PVE-EVENT: -1
  Claims:
    Mode:
      Survival: Survival
      Survival_nether: Survival
      Survival_the_end: Survival
      PVE-EVENT: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 3000
    Claim Blocks Accrued Per Hour:
      Default: 250
    Max Accrued Claim Blocks:
      Default: 13000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: GOLDEN_AXE
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 30
        ExceptWhenOwnerHasTotalClaimBlocks: 999999
        ExceptWhenOwnerHasBonusClaimBlocks: 999999
      AutomaticNatureRestoration:
        SurvivalWorlds: true
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 20
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 5
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/whisper;/t;/msg
    WarningMessage: No spamees porfavor.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Survival: false
      Survival_nether: true
      Survival_the_end: true
      PVE-EVENT: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 10
    AllowCombatItemDrop: false
    BlockedSlashCommands: '[]'
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 6.0E11
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 30
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: *
    UserName: *
    Password: *
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
Probably not, just ask.

**Comment by RoboMWM** [comment]
> In any case, I wouldn't even know how to check this (DB maybe?)

`/claimslist <player>`

Claim Expiration check rate is slow and scans one claim at a time every 60 seconds (though I believe it was recently refactored to check owners, will have to doublecheck what I did). If you wish to speed this up modify the value in Advanced.ClaimExpirationCheckRate

**Comment by MithrandirCraft** [comment]
There shouldn't be so many claims on my server for me to reach a point of needing to accelerate this check, + most claims dissappear in their normal time.

**Comment by RoboMWM** [comment]
The claim check is random, and it _will_ skip players that meet any of the claimblock requirements...

**Comment by MithrandirCraft** [comment]
![imagen](https://user-images.githubusercontent.com/6623704/54482572-e5fcbd00-4845-11e9-8fda-b5be5584aa85.png)
Doesn't seem like the claimblock threshold is being met. It would be rather impossible anyway.
Also... random checking seriously? ._. are you doing it that way for efficiency? Some claims could theoretically never be checked...

**Comment by RoboMWM** [comment]
It starts at a random position but iterates through all claims. Big_Scary's implementation. Definitely done for efficiency, since the other group complains that expiration makes a big scary number in timings. I don't think creating a timer for each claim that'd have to be updated on player joins/quits would be any better.

Enable debug logging in the config to see info about claim expiration checks. Then you could search for the uuid of the player who's claim should expire.

**Comment by MithrandirCraft** [comment]
One of my players suggested the following:
Provide a command which will check if current claim has expired, and if so, unclaims it.

It's actually even better than auto unclaiming. We could even disable the autounclaim and allow players to declaim themselves if they're interested in the terrain, and the terrain is expired.

Unless you consider the benefit of inactive claim removal to be the desaturation fo inactive claims (In which case having both systems would be the best outcome)

**Comment by bigpresh** [comment]
I actually quite like the idea of a "request expired claim drop" command, I'd find that useful.  Personally, I'd probably want it to mark the claim as due to be dropped in a random time (between hours and days), so that it's less useful for people simply looking to drop a claim solely for the purposes of looting builds where that player isn't around any more, but is still useful for people who legitimately want that bit of land.

**Comment by MithrandirCraft** [comment]
Also, if you could give out a permission for claim preserving, that would be nice.

**Comment by TomLewis** [comment]
My claim expire has never worked, ever. I find claims that are 4 years old from time to time still.
Having a system where players can request old claims be removed, would be fantastic, at present we have to do this via forums.

**Comment by Jikoo** [comment]
>Also, if you could give out a permission for claim preserving, that would be nice.

I can see this causing issues - a lot of permissions plugins don't support offline permissions well.

A command to do an expiration check manually would be simple, and could easily be done with a small addon.

**Comment by MithrandirCraft** [comment]
I don't see the issue. However that random iteration check works, it just has to check if the owner has a certain permission. If it can delete the claim, it should be capable of doing that first and preventing the deletion.

The way I see it, it would be a great permission to offer to donnors, since you give them a reason to contribute for preserving their claims, if they just don't feel like contributing by being "somewhat active". And you can defend better against people who complain about losing claims for inactivity by just telling them to buy a vip rank x'D

**Comment by Jikoo** [comment]
>I don't see the issue. However that random iteration check works, it just has to check if the owner has a certain permission. If it can delete the claim, it should be capable of doing that first and preventing the deletion.

Yes, and then someone's permission plugin doesn't load permissions for offline players and the permission always evaluates false, leading to their donor who paid for exemption complaining, yielding another unhappy server owner here.
It's not a bad idea, just needs a prominent disclaimer that it's not Robo's problem if you're using a perms system that can't handle it.

**Comment by MithrandirCraft** [comment]
If the permission system fails (Mine doesn't, just switch over to LuckPerms if yours does, because that sounds like a serious issue, and it's not too hard to migrate), I'm assuming the most intelligent thing to do by GP would be assume the user HAS the permission, or stop iterating for inactive claims all-together if the permission system fails (These details may even be configurable).

**Comment by MithrandirCraft** [comment]
Wait, you mean offline, as in "cracked" users?

**Comment by Jikoo** [comment]
>If the permission system fails (Mine doesn't, just switch over to LuckPerms if yours does, because that sounds like a serious issue, and it's not too hard to migrate), I'm assuming the most intelligent thing to do by GP would be assume the user HAS the permission, or stop iterating for inactive claims all-together if the permission system fails (These details may even be configurable).

Last I was aware, while LP does allow offline access, it will not initiate loads for offline players through standard requests. This is (or at least was) to prevent people from causing lag by making load requests on the main thread. Back when I initially swapped to LP, I had to use its API over Vault in order to actually use offline perms.

There is no differentiation provided by perms systems beyond set, true or false, or unset. You cannot determine if a provider has not loaded perms or the server owner has not set them using standard APIs. GP cannot fall through like that.

>Wait, you mean offline, as in "cracked" users?

No, offline as in currently not online.

**Comment by RoboMWM** [comment]
Offline permissions do not exist in Bukkit. Permissions are attached to the Player object; there is no such interface for OfflinePlayers.

Please enable debug logging in GP config to determine what's happening with the expiration check. This data is needed to start determining where to look for issues in this feature. 

Although I skimmed through some, a lot of suggestions here would be perfect for addons (adding a command, etc.)

**Comment by RoboMWM** [comment]
FYI, the new expiration task has been working for others. https://github.com/RoboMWM/ClaimClassifier/issues/10#issuecomment-481644070

> Btw, going through players instead of claims has been really great because absentee land owners are found way faster.

So yea, will need GP debug logging to see the expiration task in action.

**Comment by MithrandirCraft** [comment]
Sorry I answered soo late. But I just updated the plugin to the latest release, for my 1.13.2 server.

Still don't have any results, but maybe unclaiming starts working more precisely to the expiry date as you commented.

**Comment by MithrandirCraft** [comment]
It looks like this issue is still happening with GP 16.11.6, Spigot 1.13.2
> 
> Please enable debug logging in GP config to determine what's happening with the expiration check. This data is needed to start determining where to look for issues in this feature.
> 
I guess I'll do this then.
>
> Although I skimmed through some, a lot of suggestions here would be perfect for addons (adding a command, etc.)
>
Please consider this.

**Comment by MithrandirCraft** [comment]
Hey. I know this ticket is substantially old. I actually missinterpreted the instructions (probably).
I thought I should maybe wait untill I found a claim that wasn't being autoremoved, and then take the logs. But maybe you only need some regular logs. So I started the debug yesterday and this is how it's currently doing:
[2019_11_26.log](https://github.com/TechFortress/GriefPrevention/files/3894155/2019_11_26.log)

I'm not sure because I haven't checked, and none has been reported. But I would bet there should be some claim that's well beyond the 30 day inactivity unclaim threshold on my survival world.

Maybe these logs will be helfull, allthough at first glance they don't seem to contain any usefull information. On my side, all I can say is that claims don't unclaim after 30 days. Last claim we found was 50 days old (yesterday) in owner inactivity, and we had to remove it manually (case for which a player command would be really usefull).

I'm always using GP's latest version, allthough new releases don't seem to come out that often.

**Comment by RoboMWM** [comment]
Idk if you have debug mode enabled (I think you do, just thought I put more in for the expired claim check but I guess not). But ya, would need to know the UUID of the player.

**Comment by MithrandirCraft** [comment]
Will do.

**Comment by MithrandirCraft** [comment]
Here's a terrain, which by the way, presents a bug where it doesn't show the owner's name, but instead the UUID. Which in this case seems rather convenient:
![imagen](https://user-images.githubusercontent.com/6623704/69735934-d0a89400-1131-11ea-8b7b-c5cb1381d9ae.png)
UUID from image: 1603e2f5-a3da-1321-95d5-57ed04d7d8d7
The days also look messed up in this case. 
I also found another terrain with a player name which I couldn't convert to UUID, but had 71 days of inactivity.
And some more logs:
[2019_11_27.log](https://github.com/TechFortress/GriefPrevention/files/3897492/2019_11_27.log)

**Comment by RoboMWM** [comment]
You can modify the rate and player cache in the config. Looks like it didn't get around to checking that player in that log.

**Comment by MithrandirCraft** [comment]
ClaimExpirationCheckRate: 60
OfflinePlayer_cache_days: 90

This is how I have them. I found no information on these options, what do they do, and what units do they use?

**Comment by Jikoo** [comment]
> ClaimExpirationCheckRate: 60

1 player checked per 60 seconds

> OfflinePlayer_cache_days: 90

Players' names will be cached for 90 days

**Comment by MithrandirCraft** [comment]
Is there any point in modifying the player cache days (whatever that does)?
Furthermore, is there any point on chacheing players for 90d if their claims get deleted after 30d?

As for ClaimExpirationCheckRate, I'll try making it lower, see if that helps. 
But something tells me it won't since there's claims reaching up to 70 day owner inactivity, and there's not that many claims on my server. In just a single day GP could revise them all if it's every 60s, and still have spare time.

**Comment by Jikoo** [comment]
> Is there any point in modifying the player cache days (whatever that does)?
Furthermore, is there any point on chacheing players for 90d if their claims get deleted after 30d?

It's a pretty minimal amount of data, but there's no real point beyond the deletion threshold.

Could you post a new GP log (or, ideally, two) of a run of claim checks and a UUID of a player whose claim was missed? GP theoretically checks 1440 players per 24 hours with default settings. I'm wondering if the new system starts at the same position, so if you have too many and too short uptime, it never reaches the final few.

**Comment by Jikoo** [comment]
Actually never mind, that's exactly it, looked in your previous logs.

![image](https://user-images.githubusercontent.com/1353270/75627378-90780800-5b9d-11ea-8634-032bbd972eb0.png)

**Comment by MithrandirCraft** [comment]
Is there a dev build for this? Or will a release come soon?

**Comment by Jikoo** [comment]
You can download dev builds off the [CI server](https://ci.appveyor.com/project/RoboMWM39862/griefprevention/build/artifacts). I doubt a release will be pushed soon, there've only been 2 commits since last release.

**Comment by MithrandirCraft** [comment]
Hi. Please reopen. This issue still persists with your latest dev build.

I insist, my server isn't that large, cleaning up 10 inactive claims from a total of 500 at the most, shouldn't be a task taking days to complete.

**Comment by RoboMWM** [comment]
Please attach logs from multiple days. Also, have you decreased the check interval? Please also paste config.

**Comment by RoboMWM** [comment]
Will also need a paste of /version GriefPrevention too

**Comment by MithrandirCraft** [comment]
Logs from multiple days:
[Logs.zip](https://github.com/TechFortress/GriefPrevention/files/4303413/Logs.zip)

GP Config:
[config.txt](https://github.com/TechFortress/GriefPrevention/files/4303414/config.txt)

/version GriefPrevention output:
GriefPrevention version 16.13.0-49d51a3

**Comment by RoboMWM** [comment]
Logs: https://gist.github.com/RoboMWM/c7d790d787ab69683c325116a6bdf497

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Survival: -1
    Survival_nether: -1
    Survival_the_end: -1
  Claims:
    Mode:
      Survival: Survival
      Survival_the_end: Survival
      Survival_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 3000
    Claim Blocks Accrued Per Hour:
      Default: 250
    Max Accrued Claim Blocks:
      Default: 13000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: GOLDEN_AXE
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 100
        ExceptWhenOwnerHasTotalClaimBlocks: 999999
        ExceptWhenOwnerHasBonusClaimBlocks: 999999
      AutomaticNatureRestoration:
        SurvivalWorlds: true
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 20
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 5
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/whisper;/t;/msg
    WarningMessage: No spamees porfavor.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Survival: true
      Survival_nether: true
      Survival_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 10
    AllowCombatItemDrop: false
    BlockedSlashCommands: '[server]'
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 6.0E11
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 30
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: jdbc:mysql:<more would be here>
    UserName: <username would be here>
    Password: <password would be here>
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 15
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: true
      Muted Chat Messages: false
```

**Comment by RoboMWM** [comment]
What day and time did you start using `16.13.0-49d51a3`? Also, is there a list of claims and UUIDs that are supposed to be expired? Would also like to see /claimslist of these players.

**Comment by RoboMWM** [comment]
~~It seems that it's checking the same set of players multiple times.~~ So yea, would appreciate some sort of list of what's supposed to be gone - and if possible, if you can find the corresponding claim file.

**Comment by RoboMWM** [comment]
Oh, I didn't realize #736 turned the collection into a List - this would make the check take vastly longer. Going to see if possible to fix...

**Comment by RoboMWM** [comment]
Just realized #736 uses a list, and as such does not remove duplicate owner entries, so those with more claims will be checked more often than those with less claims. I've just committed a fix to remove the duplicate entries as it did before, while keeping the randomization that was added.

**Comment by MithrandirCraft** [comment]
> 
> 
> What day and time did you start using `16.13.0-49d51a3`? Also, is there a list of claims and UUIDs that are supposed to be expired? Would also like to see /claimslist of these players.

4 days ago when @Jikoo pointed me to the latest dev builds.

We don't have a list, my staff just remove them manually when they encounter them. I'll ask if you want for any claims still lying around.

**Comment by RoboMWM** [comment]
yea without a list of what should be removed logs are a bit useless since we don't have the full state. Anyways, try 0cf0171

**Comment by Jikoo** [comment]
~~The Stream operation `Stream::distinct` removes duplicates.~~

Edit: Clearly not though, the heck. Reason I swapped to a list was shuffling didn't accept a set, I may be blind though.

Did some more research, distinct only works on ordered collections. My bad, sorry.

**Comment by RoboMWM** [comment]
I looked this up bri

**Comment by RoboMWM** [comment]
I looked this up briefly and it seems it works for unordered or ordered, just that it won't preserve order afterwards if unordered.

**Comment by MithrandirCraft** [comment]
@RoboMWM @Jikoo 
Issue persists, please reopen.
Inactivity time for claim removal is 30 days.
/version griefprevention output:
GriefPrevention version 16.13.0-0cf0171
Here's the updated logs:
[Updated GP logs.zip](https://github.com/TechFortress/GriefPrevention/files/4340760/Updated.GP.logs.zip)
Here's the list of affected claims as requested previously:
[New persistent claims images.zip](https://github.com/TechFortress/GriefPrevention/files/4340776/New.persistent.claims.images.zip)

**Comment by RoboMWM** [comment]
Hi,
From the config above, 30 days is only for new claims. So I'm not sure what config option you changed.
You are also not running the version that has the fix.
Also, I'm going to add debug logs.
Please wait for the debug logs to be added before testing.
I also strongly suggest testing on a server with no other plugins. You could also play with the date to simulate time passing if need be, or modifying player NBT data. Or just set the days to 1 to see what happens.
If it still occurs, it'd be preferable for images to be uploaded somewhere like imgur and logs to gist.github.com.

**Comment by RoboMWM** [comment]
Please try https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/31513110/artifacts and highly recommend testing on a server without plugins first.

**Comment by MithrandirCraft** [comment]
> Hi,
> From the config above, 30 days is only for new claims. So I'm not sure what config option you changed.

`      UnusedClaimDays: 30`
What is a new claim? I mean, no matter what "UnusedClaim" represents, **this is the highest possible value for an inactive claim**, thus no claims should possibly persist more than 30 days right? Are there any other thresholds or elements I may not know of that could make a claim persist above 30 days?

I changed nothing all I did was update your jar. My config is, and always has been as I've shown you long ago.

> Also, I'm going to add debug logs.
> Please wait for the debug logs to be added before testing.
> I also strongly suggest testing on a server with no other plugins. You could also play with the date to simulate time passing if need be, or modifying player NBT data. Or just set the days to 1 to see what happens.
> If it still occurs, it'd be preferable for images to be uploaded somewhere like imgur and logs to gist.github.com.

Sure.

**Comment by Jikoo** [comment]
>What is a new claim?

Frankly, not sure. I assume it has to do with player activity inside it, a couple block placements and breaks so it's considered used. It definitely does not indicate a structure or any form of real long-term living.

>**this is the highest possible value for an inactive claim**, thus no claims should possibly persist more than 30 days right?

Per your last provided config, 100 days is the maximum possible. `GriefPrevention.Claims.Expiration.AllClaims.DaysInactive`
```YAML
GriefPrevention:
  Claims:
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 100
        ExceptWhenOwnerHasTotalClaimBlocks: 999999
        ExceptWhenOwnerHasBonusClaimBlocks: 999999
```
