### ISSUE TITLE
GP claim tool not setting second corner

### ISSUE THREAD

**Issue by Dhenier** [GriefPrevention/GriefPrevention#568]
### What happened:
Initial chest claim works.
Unable to use Gold Shovel (default tool) to resize or claim blocks.
Note: Doing all of this with 1.13.2 using GriefPrevention-16.11.6 works just as expected. Tool works for non-chest claims and for resizing.
      Using GriefPrevention-16.11.6 on Paper 1.14.4 produces the same bug results as the GriefPrevention-16.12.alpha

### What you expected:
Be able to use Gold Shovel (default tool) to resize or claim blocks.

### Steps to reproduce:
Paper 1.14.4 Built on July 24, 2019
GriefPrevention-16.12.alpha
Vault-1.7.2
1. Start new server and login (brand new world)
2. Config is default with debug enabled. In config world shows claim mode is Survival.
3. OP user and leave spawn area
4. /ACB <user> 1000 (increased my claim blocks by 1000)
5. Use Gold Shovel (default tool) - message shows I have 1100 claim blocks available.
   5.a Set first claim block - Diamond box appears on ground
   5.b Go to second block that makes area greater than 100 blocks and click to set
   5.c Result - first claim block is set to this second block instead of marking it as second corner and creating the claim
6. Use a stick - see that no blocks have been claimed.
7. Set down a chest - new claim created
8. Use a stick can see that blocks have been claimed in area shown around chest.
9. Use Gold Shovel to resize chest claim area:
   9.a Use Gold Shovel on corner of chest claim - message to resize claim appears
   9.b Use Gold Shovel on new corner for resized claim
   9.c Result - see that no blocks have been added and this second block is set as a first corner block
10. Use a stick and see that original chest claim shows claimed blocks but the resized area shows no claimed blocks.
11. Repeat in creative mode - same results.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
This server is running Paper version git-Paper-141 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
GriefPrevention version 16.12.alpha.1

### Stack trace/error or server log
No error is reported, but here is the log:
https://gist.github.com/Whist34/6b32089a3d747097f4ca3174170d538a

### GriefPrevention config.yml

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Phenalon: -1
    Phenalon_nether: -1
    Phenalon_the_end: -1
  Claims:
    Mode:
      Phenalon_the_end: Disabled
      Phenalon: Survival
      Phenalon_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 100
    CreationRequiresWorldGuardBuildPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Phenalon: false
      Phenalon_nether: false
      Phenalon_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: true
      Muted Chat Messages: false
```

### Plugin list (if applicable):
GriefPrevention-16.12.alpha
Vault-1.7.2
