### ISSUE TITLE
Messages File back to default (cannot edit)

### ISSUE THREAD

**Issue by Emivg** [GriefPrevention/GriefPrevention#604]
### What happened:
Every time I update the "messages.yml" file with my language, it gets reset to default and I get some errors while running commands

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Edit "messages.yml" messages
2. Save the file
3. Reload/restart server
4. Not working, file came back to default language and some errors while running commands

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: git-paper-175 (1.14.4)
Paste of `/version GriefPrevention`: 16.11.6

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_the_end: Disabled
      world_nether: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 250
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 10000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 5
    ExtendIntoGroundDistance: 200
    MinimumWidth: 5
    MinimumArea: 50
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 80
        ExceptWhenOwnerHasTotalClaimBlocks: 1000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 5.0
    ClaimBlocksSellValue: 1.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 2
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


```

### New messages file:

```yml

# Use a YAML editor like NotepadPlusPlus to edit this file.  
# After editing, back up your changes before reloading the server in case you made a syntax error.  
# Use dollar signs ($) for formatting codes, which are documented here: http://minecraft.gamepedia.com/Formatting_codes
Messages:
  RespectingClaims:
    Text: $aAhora estas respetando las protecciones.
  IgnoringClaims:
    Text: $cAhora estas ignorando las protecciones.
  SuccessfulAbandon:
    Text: Proteccion Abandonada. Tienes $6{0} $aBloques de proteccion.
    Notes: '0: bloques restantes.'
  RestoreNatureActivate:
    Text: Ready to restore some nature!  Right click to restore nature, and use /BasicClaims
      to stop.
  RestoreNatureAggressiveActivate:
    Text: Aggressive mode activated.  Do NOT use this underneath anything you want
      to keep!  Right click to aggressively restore nature, and use /BasicClaims to
      stop.
  FillModeActive:
    Text: Fill mode activated with radius {0}.  Right click an area to fill.
    Notes: '0: fill radius'
  TransferClaimPermission:
    Text: $4Este comando necesita permisos de administrador.
  TransferClaimMissing:
    Text: $cNo hay un claim aqui.  Ponte sobre un claim administrativo.
  TransferClaimAdminOnly:
    Text: $cSolo las claims administrativas se pueden transferir.
  PlayerNotFound2:
    Text: $cEste usuario no se ha conectado recientemente.
  TransferTopLevel:
    Text: Only top level claims (not subdivisions) may be transferred.  Stand outside
      of the subdivision and try again.
  TransferSuccess:
    Text: Claim transferida.
  TrustListNoClaim:
    Text: Ponte sobre el claim que quieras inspeccionar.
  ClearPermsOwnerOnly:
    Text: $cSolo el propietario del claim puede quitar los permisos.
  UntrustIndividualAllClaims:
    Text: Has quitado el acceso a {0} en todas tus protecciones.
    Notes: '0: untrusted player'
  UntrustEveryoneAllClaims:
    Text: Cleared permissions in ALL your claims.  To set permissions for a single
      claim, stand inside it.
  NoPermissionTrust:
    Text: $cNo tienes permiso de {0} para cambiar los permisos del claim.
    Notes: '0: claim owner''s name'
  ClearPermissionsOneClaim:
    Text: Has quitado todos los permisos de este claim.
  UntrustIndividualSingleClaim:
    Text: Has quitado el acceso a {0} en este claim.
    Notes: '0: untrusted player'
  OnlySellBlocks:
    Text: Los claimblocks solo se pueden vender.
  BlockPurchaseCost:
    Text: Precio de un (1) claimblock {0}$. Tu dinero: {1}$.
    Notes: '0: cost of one block; 1: player''s account balance'
  ClaimBlockLimit:
    Text: Has alcanzado el limite de claimblocks. No puedes tener mas.
  InsufficientFunds:
    Text: No tienes suficiente dinero. Necesitas {0}, pero solo tienes {1}.
    Notes: '0: total cost; 1: player''s account balance'
  PurchaseConfirmation:
    Text: Has pagado {0}.  Ahora tienes {1} claimblocks.
    Notes: '0: total cost; 1: remaining blocks'
  OnlyPurchaseBlocks:
    Text: Los claimblocks solo se pueden comprar.
  BlockSaleValue:
    Text: Un claimblock se vende por {0}.  Tienes {1} claimblocks disponibles.
    Notes: '0: block value; 1: available blocks'
  NotEnoughBlocksForSale:
    Text: No tienes suficientes claimblocks para vender.
  BlockSaleConfirmation:
    Text: Has obtenido {0}$. Aun te quedan {1} claimblocks.
    Notes: '0: amount deposited; 1: remaining blocks'
  AdminClaimsMode:
    Text: Modo de claims administrativas. Cualquier claim de este tipo se puede editar.
  BasicClaimsMode:
    Text: Has vuelto al modo de claims basico.
  SubdivisionMode:
    Text: Modo Subdivisiones.  Usa tu pala para crear subdivisiones en tu claim
      existente.  Usa /basicclaims para salir de este modo.
  SubdivisionVideo2:
    Text: 'Clic para ayuda con las subdivisiones: {0}'
    Notes: 0:video URL
  DeleteClaimMissing:
    Text: No hay un claim aqui.
  DeletionSubdivisionWarning:
    Text: Este claim tiene subdivisiones. Si estas seguro de que quieres borrarlo,
      utiliza /DeleteClaim de nuevo.
  DeleteSuccess:
    Text: Claim eliminada.
  CantDeleteAdminClaim:
    Text: No tienes permiso para eliminar claims.
  DeleteAllSuccess:
    Text: Todas las claims de {0} han sido eliminadas.
    Notes: '0: owner''s name'
  NoDeletePermission:
    Text: No tienes permiso para eliminar claims.
  AllAdminDeleted:
    Text: Has borrado todas las claims administrativas.
  AdjustBlocksSuccess:
    Text: 'Ajustados los bloques de {0} a {1}.  Cantidad de claimblocks nueva: {2}.'
    Notes: '0: player; 1: adjustment; 2: new total'
  NotTrappedHere:
    Text: No puedes construir aqui.
  RescuePending:
    Text: If you stay put for 10 seconds, you'll be teleported out.  Please wait.
  NonSiegeWorld:
    Text: Siege is disabled here.
  AlreadySieging:
    Text: You're already involved in a siege.
  NotSiegableThere:
    Text: '{0} isn''t protected there.'
    Notes: '0: defending player'
  SiegeTooFarAway:
    Text: You're too far away to siege.
  NoSiegeYourself:
    Text: You cannot siege yourself, don't be silly
  NoSiegeDefenseless:
    Text: That player is defenseless.  Go pick on somebody else.
  AlreadyUnderSiegePlayer:
    Text: '{0} is already under siege.  Join the party!'
    Notes: '0: defending player'
  AlreadyUnderSiegeArea:
    Text: That area is already under siege.  Join the party!
  NoSiegeAdminClaim:
    Text: Siege is disabled in this area.
  SiegeOnCooldown:
    Text: You're still on siege cooldown for this defender or claim.  Find another
      victim.
  SiegeAlert:
    Text: You're under siege!  If you log out now, you will die.  You must defeat
      {0}, wait for him to give up, or escape.
    Notes: '0: attacker name'
  SiegeConfirmed:
    Text: The siege has begun!  If you log out now, you will die.  You must defeat
      {0}, chase him away, or admit defeat and walk away.
    Notes: '0: defender name'
  AbandonClaimMissing:
    Text: Entra al claim que quieras abandonar, o usa /abandonallclaims para abandonar
      todas.
  NotYourClaim:
    Text: Este no es tu claim.
  DeleteTopLevelClaim:
    Text: Para eliminar una subdivision debes estar dentro de ella. De lo contrario, utiliza /AbandonTopLevelClaim
      para eliminar este claim y todas sus subdivisiones.
  AbandonSuccess:
    Text: Claim abandonada.  Ahora tienes {0} claimblocks.
    Notes: '0: remaining claim blocks'
  CantGrantThatPermission:
    Text: No puedes dar permisos que no tienes.
  GrantPermissionNoClaim:
    Text: Debes estar dentro del claim del que quieres dar permisos.
  GrantPermissionConfirmation:
    Text: Dado permiso "{1}" a {0} en {2}.
    Notes: '0: target player; 1: permission description; 2: scope (changed claims)'
  ManageUniversalPermissionsInstruction:
    Text: To manage permissions for ALL your claims, stand outside them.
  ManageOneClaimPermissionsInstruction:
    Text: Para gestionar los permisos de un claim debes estar dentro de el.
  CollectivePublic:
    Text: publico
    Notes: as in 'granted the public permission to...'
  BuildPermission:
    Text: construir
  ContainersPermission:
    Text: acceso a containers y animales
  AccessPermission:
    Text: usar botones y palancas
  PermissionsPermission:
    Text: gestionar permisos
  LocationCurrentClaim:
    Text: este claim
  LocationAllClaims:
    Text: todos tus claims
  PvPImmunityStart:
    Text: Estas protegido frente ataques porque tu inventario esta vacio.
  SiegeNoDrop:
    Text: You can't give away items while involved in a siege.
  DonateItemsInstruction:
    Text: To give away the item(s) in your hand, left-click the chest again.
  ChestFull:
    Text: Este cofre esta lleno.
  DonationSuccess:
    Text: Item(s) transferred to chest!
  PlayerTooCloseForFire2:
    Text: You can't start a fire this close to another player.
  TooDeepToClaim:
    Text: Este cofre no esta protegido. Piensa en moverlo.
  ChestClaimConfirmation:
    Text: Este cofre esta protegido.
  AutomaticClaimNotification:
    Text: Este cofre y alrededores han sido protegidos automaticamente.
  UnprotectedChestWarning:
    Text: Este cofre NO esta protegido. Amplia tu proteccion o crea una nueva.
  ThatPlayerPvPImmune:
    Text: No puedes herir a jugadores.
  CantFightWhileImmune:
    Text: No puedes luchar contra otros jugadores.
  NoDamageClaimedEntity:
    Text: Esto pertenece a {0}.
    Notes: '0: owner name'
  ShovelBasicClaimMode:
    Text: Pala cambiado a modo de claims basicos.
  RemainingBlocks:
    Text: Tienes {0} claimsblocks.
    Notes: '0: remaining blocks'
  CreativeBasicsVideo2:
    Text: 'Click for Land Claim Help: {0}'
    Notes: '{0}: video URL'
  SurvivalBasicsVideo2:
    Text: 'Clic para ver un tutorial:$3$n https://youtu.be/gF4ADNOfVGA'
    Notes: '{0}: video URL'
  TrappedChatKeyword:
    Text: trapped
    Notes: When mentioned in chat, players get information about the /trapped command.
  TrappedInstructions:
    Text: Are you trapped in someone's land claim?  Try the /trapped command.
  PvPNoDrop:
    Text: No puedes tirar items cuando estas en combate.
  SiegeNoTeleport:
    Text: You can't teleport out of a besieged area.
  BesiegedNoTeleport:
    Text: You can't teleport into a besieged area.
  SiegeNoContainers:
    Text: You can't access containers while involved in a siege.
  PvPNoContainers:
    Text: No puedes abrir cofres cuando estas en combate.
  PvPImmunityEnd:
    Text: Ahora puedes luchar con quien quieras.
  NoBedPermission:
    Text: '{0} no te ha dado permisos para dormir aqui.'
    Notes: '0: claim owner'
  NoWildernessBuckets:
    Text: You may only dump buckets inside your claim(s) or underground.
  NoLavaNearOtherPlayer:
    Text: No puedes poner lava tan cerca de {0}.
    Notes: '0: nearby player'
  TooFarAway:
    Text: Esto esta muy lejos.
  BlockNotClaimed:
    Text: Nadie ha claimeado este bloque.
  BlockClaimed:
    Text: Este bloque ha sido claimeado por {0}.
    Notes: '0: claim owner'
  SiegeNoShovel:
    Text: You can't use your shovel tool while involved in a siege.
  RestoreNaturePlayerInChunk:
    Text: Unable to restore.  {0} is in that chunk.
    Notes: '0: nearby player'
  NoCreateClaimPermission:
    Text: You don't have permission to claim land.
  ResizeNeedMoreBlocks:
    Text: No tienes suficientes bloques. Necesitas {0} mas.
    Notes: '0: how many needed'
  NoCreativeUnClaim:
    Text: You can't unclaim this land.  You can only make this claim larger or create
      additional claims.
  ClaimResizeSuccess:
    Text: Claim editada. Te quedan {0} claimblocks.
    Notes: '0: remaining blocks'
  ResizeFailOverlap:
    Text: No puedes editar tu claim porque hay otro cerca.
  ResizeStart:
    Text: Estas editando tu claim.  Usa tu pala otra vez para marcar la otra esquina.
  ResizeFailOverlapSubdivision:
    Text: No puedes crear otra subdivision aqui porque interferiria con otra subdivision. Prueba
      /abandonclaim para eliminarla, o usa tu pala en la otra esquina para redimensionarla.
  SubdivisionStart:
    Text: Esquina de la Subdivision marcada!  Usa tu pala en la otra esquina para crear la
      nueva subdivision.
  CreateSubdivisionOverlap:
    Text: Tu area seleccionada interfiere con otra subdivision.
  SubdivisionSuccess:
    Text: Subdivision creada!  Utiliza /trust para compartirla con amigos.
  CreateClaimFailOverlap:
    Text: No puedes crear un claim porque tienes otro cerca.
  CreateClaimFailOverlapOtherPlayer:
    Text: No puedes crear tu claim aqui por la proteccion de {0}.
    Notes: '0: other claim owner'
  ClaimsDisabledWorld:
    Text: Claims desabilitadas de este mundo.
  ClaimStart:
    Text: Esquina marcada!  Usa la pala de oro en la esquina opuesta para crea el
      claim.
  NewClaimTooNarrow:
    Text: Este claim es muy escaso. Minimo: {0}.
    Notes: '0: minimum claim width'
  CreateClaimInsufficientBlocks:
    Text: No tienes suficientes bloques para claimear esto. Necesitas {0} bloques mas.
    Notes: '0: additional blocks needed'
  AbandonClaimAdvertisement:
    Text: To delete another claim and free up some blocks, use /AbandonClaim.
  CreateClaimFailOverlapShort:
    Text: El area que has seleccionado interfiere con un claim ya existente.
  CreateClaimSuccess:
    Text: Claim creada! Usa /trust para dar permisos.
  SiegeWinDoorsOpen:
    Text: Congratulations!  Buttons and levers are temporarily unlocked (five minutes).
  RescueAbortedMoved:
    Text: You moved!  Rescue cancelled.
  SiegeDoorsLockedEjection:
    Text: Looting time is up!  Ejected from the claim.
  NoModifyDuringSiege:
    Text: Claims can't be modified while under siege.
  OnlyOwnersModifyClaims:
    Text: Solo {0} puede modificar el claim.
    Notes: '0: owner name'
  NoBuildUnderSiege:
    Text: This claim is under siege by {0}.  No one can build here.
    Notes: '0: attacker name'
  NoBuildPvP:
    Text: No puedes construir mientras estas en combate.
  NoBuildPermission:
    Text: No tienes permiso de {0} para construir.
    Notes: '0: owner name'
  NonSiegeMaterial:
    Text: That material is too tough to break.
  NoOwnerBuildUnderSiege:
    Text: You can't make changes while under siege.
  NoAccessPermission:
    Text: No tienes permiso de {0}.
    Notes: '0: owner name.  access permission controls buttons, levers, and beds'
  NoContainersSiege:
    Text: This claim is under siege by {0}.  No one can access containers here right
      now.
    Notes: '0: attacker name'
  NoContainersPermission:
    Text: No tienes permiso de {0}.
    Notes: '0: owner''s name.  containers also include crafting blocks'
  OwnerNameForAdminClaims:
    Text: un administrador
    Notes: as in 'You don't have an administrator's permission to build here.'
  ClaimTooSmallForEntities:
    Text: This claim isn't big enough for that.  Try enlarging it.
  TooManyEntitiesInClaim:
    Text: This claim has too many entities already.  Try enlarging the claim or removing
      some animals, monsters, paintings, or minecarts.
  YouHaveNoClaims:
    Text: No tienes ningun claim creado.
  ConfirmFluidRemoval:
    Text: Abandoning this claim will remove lava inside the claim.  If you're sure,
      use /AbandonClaim again.
  AutoBanNotify:
    Text: Auto-banned {0}({1}).  See logs for details.
  AdjustGroupBlocksSuccess:
    Text: 'Claimblocks editados para el grupo {0} por {1}.  Nuevo total: {2}.'
    Notes: '0: permission; 1: adjustment amount; 2: new total bonus'
  InvalidPermissionID:
    Text: Escoge a un jugador o un permiso entre []..
  HowToClaimRegex:
    Text: (^|.*\W)how\W.*\W(claim|protect|lock)(\W.*|$)
    Notes: This is a Java Regular Expression.  Look it up before editing!  It's used
      to tell players about the demo video when they ask how to claim land.
  NoBuildOutsideClaims:
    Text: You can't build here unless you claim some land first.
  PlayerOfflineTime:
    Text: '  Ultima conexion: Hace {0} dias.'
    Notes: '0: number of full days since last login'
  BuildingOutsideClaims:
    Text: Other players can build here, too.  Consider creating a land claim to protect
      your work!
  TrappedWontWorkHere:
    Text: Sorry, unable to find a safe location to teleport you to. Contact an admin.
  CommandBannedInPvP:
    Text: You can't use that command while in PvP combat.
  UnclaimCleanupWarning:
    Text: The land you've unclaimed may be changed by other players or cleaned up
      by administrators.  If you've built something there you want to keep, you should
      reclaim it.
  BuySellNotConfigured:
    Text: La compra/venta de claimblocks esta deshabilitada.
  NoTeleportPvPCombat:
    Text: No puedes teletransportarte en combate.
  NoTNTDamageAboveSeaLevel:
    Text: 'Aviso: La TNT no destruye bloques!'
  NoTNTDamageClaims:
    Text: 'Aviso: La TNT no destruye bloques!'
  IgnoreClaimsAdvertisement:
    Text: Illouuuuuu tate quietouuuuu.
  NoPermissionForCommand:
    Text: No tienes permiso para ejecutar este comando.
  ClaimsListNoPermission:
    Text: No tienes permiso para ver los claims de otros usuarios.
  ExplosivesDisabled:
    Text: Esta claim esta ahora protegido de las explosiones. Utiliza /ClaimExplosions de nuevo
      para activarlas.
  ExplosivesEnabled:
    Text: Este claim es ahora vulnerable a las explosiones. Utiliza /ClaimExplosions de nuevo
      para deshabilitarlas.
  ClaimExplosivesAdvertisement:
    Text: Para permitir que la TNT rompa bloques usa /ClaimExplosions.
  PlayerInPvPSafeZone:
    Text: El jugador esta en zona segura.
  NoPistonsOutsideClaims:
    Text: 'Warning: Pistons won''t move blocks outside land claims.'
  SoftMuted:
    Text: Muteado {0}.
    Notes: '0: The changed player''s name.'
  UnSoftMuted:
    Text: Desmuteado {0}.
    Notes: '0: The changed player''s name.'
  DropUnlockAdvertisement:
    Text: Otros usuarios no pueden cojer tus cosas del suelo.
  PickupBlockedExplanation:
    Text: No puedes recoger estos objetos, a no ser que {0} utilice /UnlockDrops.
    Notes: '0: The item stack''s owner.'
  DropUnlockConfirmation:
    Text: Has desbloqueado tus objetos. Otros jugadores podran recogerlos hasta que mueras de nuevo.
      again).
  DropUnlockOthersConfirmation:
    Text: Unlocked {0}'s drops.
    Notes: '0: The owner of the unlocked drops.'
  AdvertiseACandACB:
    Text: Puedes usar /ACB para obtener claimblocks.
  AdvertiseAdminClaims:
    Text: You could create an administrative land claim instead using /AdminClaims,
      which you'd share with other administrators.
  AdvertiseACB:
    Text: Puedes usar /ACB para obtener claimblocks.
  NotYourPet:
    Text: Esto pertenece a {0} hasta que te lo de con /GivePet.
    Notes: '0: owner name'
  PetGiveawayConfirmation:
    Text: Mascota transferida.
  PetTransferCancellation:
    Text: Pet giveaway cancelled.
  ReadyToTransferPet:
    Text: Ready to transfer!  Right-click the pet you'd like to give away, or cancel
      with /GivePet cancel.
  AvoidGriefClaimLand:
    Text: Prevent grief!  If you claim your land, you will be grief-proof.
  BecomeMayor:
    Text: Subdivide your land claim and become a mayor!
  ClaimCreationFailedOverClaimCountLimit:
    Text: You've reached your limit on land claims.  Use /AbandonClaim to remove one
      before creating another.
  CreateClaimFailOverlapRegion:
    Text: No puYou can't claim all of this because you're not allowed to build here.
  ResizeFailOverlapRegion:
    Text: No puedes construir aqui.
  NoBuildPortalPermission:
    Text: You can't use this portal because you don't have {0}'s permission to build
      an exit portal in the destination land claim.
    Notes: '0: Destination land claim owner''s name.'
  ShowNearbyClaims:
    Text: Encontradas {0} claims.
    Notes: '0: Number of claims found.'
  NoChatUntilMove:
    Text: Sorry, but you have to move a little more before you can chat.  We get lots
      of spam bots here.  :)
  SiegeImmune:
    Text: That player is immune to /siege.
  SetClaimBlocksSuccess:
    Text: Updated accrued claim blocks.
  IgnoreConfirmation:
    Text: Ahora ignoras los mensajes de ese jugador.
  NotIgnoringPlayer:
    Text: No estas ignorando a ese jugador.
  UnIgnoreConfirmation:
    Text: Ya no ignoras los mensajes de ese jugador.
  SeparateConfirmation:
    Text: Esos jugadores ahora se ignoran el uno al otro en el chat.
  UnSeparateConfirmation:
    Text: Esos jugadores ya no se ignoraran el uno al otro en el chat.
  NotIgnoringAnyone:
    Text: No estas ignorando a nadie.
  TrustListHeader:
    Text: 'Explicit permissions here:'
  Manage:
    Text: Gestionar
  Build:
    Text: Construir
  Containers:
    Text: Containers
  Access:
    Text: Acceso
  StartBlockMath:
    Text: '{0} Bloques por jugar + {1} bonus = {2} total.'
  ClaimsListHeader:
    Text: 'Claims:'
  ContinueBlockMath:
    Text: ' (-{0} blocks)'
  EndBlockMath:
    Text: ' = {0} bloques disponibles para gastar'
  NoClaimDuringPvP:
    Text: You can't claim lands during PvP combat.
  UntrustAllOwnerOnly:
    Text: Only the claim owner can clear all its permissions.
  ManagersDontUntrustManagers:
    Text: Only the claim owner can demote a manager.
  BookAuthor:
    Text: Emivg
  BookTitle:
    Text: Proteger tu Casa
  BookIntro:
    Text: Protege tu base!  Haz clic abajo para aprender a hacerlo en menos de 3 minutos.  :)
  BookDisabledChestClaims:
    Text: En este servidor, poner un cofre no protegera tu casa.
  BookUsefulCommands:
    Text: 'Comandos:'
  BookLink:
    Text: 'Clic:$3$n https://youtu.be/gF4ADNOfVGA'
    Notes: '{0}: video URL'
  BookTools:
    Text: Tus herramientas para claimear son {0} y {1}.
    Notes: '0: claim modification tool name; 1:claim information tool name'
  ResizeClaimTooNarrow:
    Text: El nuevo tama�o es muy peque�o. Tiene que ser de {0} bloques minimo.
    Notes: '0: minimum claim width'
  ResizeClaimInsufficientArea:
    Text: Ese claim es muy peque�o.  El claim tiene que ser de{0} bloques. blocks.
    Notes: '0: minimum claim area'
  NoProfanity:
    Text: Por favor modera el lenguaje.
  PlayerNotIgnorable:
    Text: No puedes ignorar a ese jugador.
  NoEnoughBlocksForChestClaim:
    Text: Because you don't have any claim blocks available, no automatic land claim
      was created for you.  You can use /ClaimsList to monitor your available claim
      block total.
  IsIgnoringYou:
    Text: Este jugador te esta ignorando.
  MustHoldModificationToolForThat:
    Text: Debes tener la pala de oro para hacer eso.
  StandInClaimToResize:
    Text: Permanece dentro del claim que quieras modificar.
  ClaimsExtendToSky:
    Text: Land claims always extend to max build height.
  ClaimsAutoExtendDownward:
    Text: Land claims auto-extend deeper into the ground when you place blocks under
      them.
  MinimumRadius:
    Text: El radio minimo de proteccion es {0}.
    Notes: '0: minimum radius'
  RadiusRequiresGoldenShovel:
    Text: Necesitas la pala de oro para especificar el rango del claim.
  ClaimTooSmallForActiveBlocks:
    Text: This claim isn't big enough to support any active block types (hoppers,
      spawners, beacons...).  Make the claim bigger first.
  TooManyActiveBlocksInClaim:
    Text: This claim is at its limit for active block types (hoppers, spawners, beacons...).  Either
      make it bigger, or remove other active blocks first.
  ConsoleOnlyCommand:
    Text: Ese comando solo se ejecuta desde la consola.
  WorldNotFound:
    Text: Mundo no encontrado.
  AdjustBlocksAllSuccess:
    Text: Adjusted all online players' bonus claim blocks by {0}.
    Notes: '0: adjustment amount'
  TooMuchIpOverlap:
    Text: Sorry, there are too many players logged in with your IP address.
  HasSubclaimRestriction:
    Text: This subclaim does not inherit permissions from the parent
  StandInSubclaim:
    Text: You need to be standing in a subclaim to restrict it
  SubclaimRestricted:
    Text: This subclaim's permissions will no longer inherit from the parent claim
  SubclaimUnrestricted:
    Text: This subclaim's permissions will now inherit from the parent claim
  NetherPortalTrapDetectionMessage:
    Text: It seems you might be stuck inside a nether portal. We will rescue you in
      a few seconds if that is the case!
    Notes: Sent to player on join, if they left while inside a nether portal.

```

Regards!
