### ISSUE TITLE
ERROR Could not pass event PlayerPortalEvent to GriefPrevention v16.11.6 (Console Spam)

### ISSUE THREAD

**Issue by Cshinshilla** [GriefPrevention/GriefPrevention#624]
### What happened:
https://paste.ofcode.org/iec5JuNhJta2YvE5mdQ63B (Spams the console)

### What you expected:
Not this error.
### Steps to reproduce:
Not quite sure what people are doing while this error is being spammed.

### Server and GriefPrevention version:
16.11.6
Running Paper#187 at the time, but has been happening for a long while.

### Stack trace/error or server log

```
19.09 16:32:10 [Server] ERROR Could not pass event PlayerPortalEvent to GriefPrevention v16.11.6
19.09 16:32:10 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.useTravelAgent()Z
19.09 16:32:10 [Server] INFO at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerPortal(PlayerEventHandler.java:1067) ~[?:?]
19.09 16:32:10 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:854) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2215) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:398) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:240) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:370) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2285) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:426) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1232) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:32:10 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
19.09 16:36:06 [Server] INFO [BuycraftX] Fetching all due players...
19.09 16:36:06 [Server] INFO [BuycraftX] Fetched due players (0 found).
19.09 16:37:29 [Server] INFO LoveKyoki was shot by xJustiins
19.09 16:39:46 [Server] ERROR Could not pass event PlayerPortalEvent to GriefPrevention v16.11.6
19.09 16:39:46 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.useTravelAgent()Z
19.09 16:39:46 [Server] INFO at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerPortal(PlayerEventHandler.java:1067) ~[?:?]
19.09 16:39:46 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:854) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2215) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:398) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:240) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:370) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2285) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:426) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1232) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-187]
19.09 16:39:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_nether: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 50
    Max Accrued Claim Blocks:
      Default: 200000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 7
      AllClaims:
        DaysInactive: -1
        ExceptWhenOwnerHasTotalClaimBlocks: 1000000
        ExceptWhenOwnerHasBonusClaimBlocks: 1000000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: -1
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg;/w;/t
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: false
    PunishLogout: true
    CombatTimeoutSeconds: 25
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa;/pv;/warp;/back;/tpaccept;/tpahere;/heal;/feed
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


```

### Plugin list (if applicable):
https://i.imgur.com/d2XMe08.png
