### ISSUE TITLE
Grief Prevention Flags Command not working

### ISSUE THREAD

**Issue by MrBuushy** [GriefPrevention/GriefPrevention#636]
### What happened:
/ClaimFlag (/cf) are not commands

### What you expected:
To see them be commands

### Steps to reproduce:
1. Go into claim
2. Type "/cf" or "/ClaimFlag" in the commands box
3. See that the area is red and does not work when you enter the command
4. FAIL

### Server and GriefPrevention version:
GriefPrevention version 16.12.0-d4d7ac4

### Stack trace/error or server log
```
None

```

### GriefPrevention config.yml

```yml

multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: file
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
updater: true
alwaysUpdate: false

```

### Plugin list (if applicable):
WorldEdit
StackMob
ClearLag
WorldSpawns
SilkSpawners
Multiverse-Core
ItemStay
EggThrow (custom)
Minepacks
Multiverse-Inventories
Vivecraft-Spigot-Extensions
PermissionsEx
Invsee_v1.0.3
Vault
GriefPrevention
MyCommand
ChestShop
Essentials
LockettePro
Flags
GPRealEstate
EssentialsChat
ItemJoin
ChestIcon
FlagsCore
FlagsBorderPatrol
FlagsCreatureSpawn
FlagsBlock
