### ISSUE TITLE
Claiming land is not working!

### ISSUE THREAD

**Issue by CTN-Originals** [GriefPrevention/GriefPrevention#701]
**Hello, My name is CTN.**

I'm the owner of a minecraft server with a survival world on it, and of course that world needs **griefprovention** so players can safely build their bases and such. A week or 2 ago i was getting a **bug-report** from a player that the golden shovel is not doing what its supposed to do, so i checked it out and he/she was right. 

When holding the shovel and right-clicking a block in survival it does turn the block into a diamond block. When i tried to click the second block within the minimum of 100 blocks it still gives me a message that that is to small. 
But when I click some block that meets every condition it wont do anything... It doesn't claim the area, it doesn't give any message in chat, it doesn't extract the claim blocks and it doesn't change the 2nd block into glowstone.
It does give a very long **error message in the console** tho... [console error will be provided]

I really need some help with this because players started to grief a lot when they found out and i had to close that world until it was fixed... but after a week its still the same and cant find out what the problem is....

**Server Information**
Server Version: Java 1.15.1
Server Host: ShockByte
Server Plugins: 
![afbeelding](https://user-images.githubusercontent.com/60195597/72927569-cc29e180-3d56-11ea-9000-37d3af093ab3.png)

If you can help me, feel free to message me on discord since i mostly am online there and react within the same hour.
**Discord Username/Tag:**  CTN#3460

## Console Error
```txt
22.01 18:57:04 [Server] Server thread/ERROR Could not pass event PlayerInteractEvent to GriefPrevention v16.8
22.01 18:57:04 [Server] INFO org.bukkit.event.EventException: null
22.01 18:57:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:442) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1250) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:893) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
22.01 18:57:04 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/permission/RegionPermissionModel
22.01 18:57:04 [Server] INFO at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:36) ~[GriefPrevention.jar:?]
22.01 18:57:04 [Server] INFO at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:863) ~[GriefPrevention.jar:?]
22.01 18:57:04 [Server] INFO at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerInteract(PlayerEventHandler.java:2440) ~[GriefPrevention.jar:?]
22.01 18:57:04 [Server] INFO at sun.reflect.GeneratedMethodAccessor597.invoke(Unknown Source) ~[?:?]
22.01 18:57:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
22.01 18:57:04 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
22.01 18:57:04 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot_Latest_1.15.1.jar:git-Spigot-037559e-661bebc]
22.01 18:57:04 [Server] INFO ... 19 more
```

## Config.yml
```yml
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    Build_World: -1
    Builds: -1
    TLT_the_end: -1
    TLT_nether: -1
    IridiumSkyblock: -1
    Parkour: -1
    HUB: -1
    Creative: -1
    IridiumSkyblock_nether: -1
    PrisonSpawn_tmp: -1
    hub_old: -1
    TLT: -1
  Claims:
    Mode:
      TLT: Disabled
      IridiumSkyblock_nether: Disabled
      IridiumSkyblock: Disabled
      Parkour: Disabled
      TLT_nether: Disabled
      Creative: Disabled
      Builds: Disabled
      hub_old: Disabled
      Build_World: Disabled
      PrisonSpawn_tmp: Disabled
      TLT_the_end: Disabled
      world: Survival
      world_the_end: Survival
      HUB: Disabled
      world_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 8000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 20
      AllClaims:
        DaysInactive: 30
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      Build_World: true
      Builds: true
      TLT_the_end: true
      TLT_nether: true
      IridiumSkyblock: true
      Parkour: true
      HUB: true
      Creative: true
      IridiumSkyblock_nether: true
      PrisonSpawn_tmp: true
      hub_old: true
      TLT: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 5
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust: []
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Advanced:
    fixNegativeClaimblockAmounts: true
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

[Griefprovention_consoleError.txt](https://github.com/TechFortress/GriefPrevention/files/4099490/Griefprovention_consoleError.txt)

[CTN-Craft_GriefProvention_serverFile.zip](https://github.com/TechFortress/GriefPrevention/files/4099509/CTN-Craft_GriefProvention_serverFile.zip)
