### ISSUE TITLE
Players can make wolves tamed by another player outside of their claim sit/stand

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#709]
### What happened:
I made a wolf who was sitting, not tamed by me, stand up. The wolf instantly teleported to the owner (who was online) instantly afterwards.

### What was expected:
A message stating that I cannot interact with this wolf.

### Steps to reproduce:

Given a player "Greg" with a tamed wolf
And another player "Bob"

1. Greg has his wolf sit outside of a claim.
2. Bob right-clicks the wolf with an empty hand

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

Paste of `/version`: git-Paper-77 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.12.0-d4d7ac4

### GriefPrevention config.yml

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_the_end: Survival
      world_nether: Survival
      world: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 900
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 800000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 14
    ExtendIntoGroundDistance: 25
    MinimumWidth: 3
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: WOODEN_SHOVEL
    Expiration:
      ChestClaimDays: 30
      UnusedClaimDays: 0
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 5000
        ExceptWhenOwnerHasBonusClaimBlocks: 500
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: '[]'
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 480
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 15
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/pm;/w;/whisper;/t;/msg;/m
    WhisperSlashCommands: /tell;/pm;/w;/whisper;/t;/msg;/m
    WarningMessage: Your last couple messages are indicative of spamming. Please stop
      spamming. Spammers will be banned.
    BanOffenders: false
    BanMessage: 'Infracted rule #3. Appeal code: . Appeal at http://techfortress.robomwm.com'
    AllowedIpAddresses: techfortress.hopto.org; tf.us.to
    DeathMessageCooldownSeconds: 0
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 7
    AllowCombatItemDrop: false
    BlockedSlashCommands: /getmeout;/confirmdeath;/movein;/sethomeregion;/sethomepost;/setspawn;/sethome;/setspawnpost;/pvp;/claimpvp
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 365
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: false
      Administrative Activity: true
      Debug: false
      Muted Chat Messages: true
```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
