### ISSUE TITLE
trusting people and they still can't do anything

### ISSUE THREAD

**Issue by unholymac** [GriefPrevention/GriefPrevention#794]
### What happened:
for some reason i can't trust some people in certain claims, it says player has been granted permissiontrust but they still can't build or doing anything?

### What was expected:
expect them to be trusted in the claim

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
not sure what this means

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
GriefPrevention 16.13.0
Paper git-Paper-211 (MC: 1.15.2)

### Stack trace/error or server log
no error in console
```
Paste entire stack trace right here inside these backticks.
not sure what this means?
```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml
GriefPrevention:
SeaLevelOverrides:
Survival: -1
Survival_nether: -1
Survival_the_end: -1
unholymac: -1
EasterEggHunt: -1
ShoppingWorld: -1
URVanilla_the_end: -1
URVanilla: -1
PVP: -1
URVanilla_nether: -1
KOTHShrines: -1
ShoppingWorldtest: -1
ZuthixArena: -1
IceCave: -1
Spawn: -1
Claims:
Mode:
URVanilla_the_end: Disabled
Survival_nether: Survival
Survival: Survival
Spawn: Disabled
EasterEggHunt: Disabled
URVanilla_nether: Disabled
unholymac: Disabled
ShoppingWorld: Disabled
ShoppingWorldtest: Disabled
URVanilla: Disabled
IceCave: Survival
Survival_the_end: Survival
KOTHShrines: Disabled
PVP: Disabled
ZuthixArena: Disabled
PreventGlobalMonsterEggs: true
PreventTheft: true
ProtectCreatures: true
PreventButtonsSwitches: true
LockWoodenDoors: false
LockTrapDoors: false
LockFenceGates: true
EnderPearlsRequireAccessTrust: true
ProtectHorses: true
ProtectDonkeys: true
ProtectLlamas: true
InitialBlocks: 1000
Claim Blocks Accrued Per Hour:
Default: 150
Max Accrued Claim Blocks:
Default: 200000
Accrued Idle Threshold: 0
AccruedIdlePercent: 0
AbandonReturnRatio: 1.0
AutomaticNewPlayerClaimsRadius: 4
ExtendIntoGroundDistance: 5
MinimumWidth: 5
MinimumArea: 100
MaximumDepth: 0
InvestigationTool: STICK
ModificationTool: GOLDEN_SHOVEL
Expiration:
ChestClaimDays: 7
UnusedClaimDays: 14
AllClaims:
DaysInactive: 365
ExceptWhenOwnerHasTotalClaimBlocks: 10000
ExceptWhenOwnerHasBonusClaimBlocks: 5000
AutomaticNatureRestoration:
SurvivalWorlds: false
AllowTrappedInAdminClaims: false
MaximumNumberOfClaimsPerPlayer: 0
CreationRequiresWorldGuardBuildPermission: true
VillagerTradingRequiresPermission: true
CommandsRequiringAccessTrust: /sethome
DeliverManuals: true
ManualDeliveryDelaySeconds: 30
RavagersBreakBlocks: true
FireSpreadsInClaims: false
FireDamagesInClaims: false
LecternReadingRequiresAccessTrust: true
Spam:
Enabled: true
LoginCooldownSeconds: 60
LoginLogoutNotificationsPerMinute: 5
ChatSlashCommands: /me;/global;/local
WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
WarningMessage: Please reduce your noise level. Spammers will be muted.
BanOffenders: false
BanMessage: Banned for spam.
AllowedIpAddresses: 1.2.3.4; 5.6.7.8
DeathMessageCooldownSeconds: 120
Logout Message Delay In Seconds: 0
PvP:
RulesEnabledInWorld:
Survival: false
Survival_nether: false
Survival_the_end: false
unholymac: false
EasterEggHunt: true
ShoppingWorld: false
URVanilla_the_end: true
URVanilla: true
PVP: false
URVanilla_nether: true
KOTHShrines: false
ShoppingWorldtest: false
ZuthixArena: false
IceCave: false
Spawn: false
ProtectFreshSpawns: false
PunishLogout: true
CombatTimeoutSeconds: 15
AllowCombatItemDrop: false
BlockedSlashCommands: /home;/vanish;/spawn;/tpa
ProtectPlayersInLandClaims:
PlayerOwnedClaims: true
AdministrativeClaims: true
AdministrativeSubdivisions: true
AllowLavaDumpingNearOtherPlayers:
PvPWorlds: true
NonPvPWorlds: false
AllowFlintAndSteelNearOtherPlayers:
PvPWorlds: true
NonPvPWorlds: false
ProtectPetsOutsideLandClaims: false
Economy:
ClaimBlocksPurchaseCost: 0.0
ClaimBlocksSellValue: 0.0
ProtectItemsDroppedOnDeath:
PvPWorlds: false
NonPvPWorlds: true
BlockLandClaimExplosions: true
BlockSurfaceCreeperExplosions: true
BlockSurfaceOtherExplosions: true
LimitSkyTrees: true
LimitTreeGrowth: false
CheckPistonMovement: true
LimitPistonsToLandClaims: true
FireSpreads: false
FireDestroys: false
AdminsGetWhispers: true
AdminsGetSignNotifications: true
SmartBan: true
Mute New Players Using Banned Words: true
MaxPlayersPerIpAddress: 3
Siege:
Worlds: []
BreakableBlocks:
- DIRT
- GRASS_BLOCK
- GRASS
- FERN
- DEAD_BUSH
- COBBLESTONE
- GRAVEL
- SAND
- GLASS
- GLASS_PANE
- OAK_PLANKS
- SPRUCE_PLANKS
- BIRCH_PLANKS
- JUNGLE_PLANKS
- ACACIA_PLANKS
- DARK_OAK_PLANKS
- WHITE_WOOL
- ORANGE_WOOL
- MAGENTA_WOOL
- LIGHT_BLUE_WOOL
- YELLOW_WOOL
- LIME_WOOL
- PINK_WOOL
- GRAY_WOOL
- LIGHT_GRAY_WOOL
- CYAN_WOOL
- PURPLE_WOOL
- BLUE_WOOL
- BROWN_WOOL
- GREEN_WOOL
- RED_WOOL
- BLACK_WOOL
- SNOW
DoorsOpenDelayInSeconds: 300
CooldownEndInMinutes: 60
EndermenMoveBlocks: false
SilverfishBreakBlocks: false
CreaturesTrampleCrops: false
RabbitsEatCrops: true
HardModeZombiesBreakDoors: false
Database:
URL: ''
UserName: ''
Password: ''
UseBanCommand: false
BanCommandPattern: ban %name% %reason%
Advanced:
fixNegativeClaimblockAmounts: true
ClaimExpirationCheckRate: 60
OfflinePlayer_cache_days: 90
Abridged Logs:
Days To Keep: 7
Included Entry Types:
Social Activity: true
Suspicious Activity: true
Administrative Activity: false
Debug: false
Muted Chat Messages: false

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):
Advanced Achievements
AdvancedBan
AuctionHouse
BeastWithdraw
BuycraftX
ChatColor2
ClearLag
CoreProtect
CrazyCrates
DeluxeMenus
DeluxeTags
DiscordSRV
eGlow
EntityTrackerFixer
Essentials
EssentialsAntiBuild
EssentialsChat
Essentials Protect
Essentials Spawn
FeatherBoard
GadgetsMenu
Harbor
Head Database
Holographic Displays
iReports
Jobs
KOTH
McMMO
Multiverse-core
Multiverse Inventories
Multiverse NetherPortals
MVdWPlaceholderAPI
Placeholder API
PlotSquared
ProtocolLib
Quickshop
Redprotect
Reserve
ShopGUIPlus
SuperTrails
SuperVanish
TAB
UltimateStacker
UltraCosmetics
Ultra Permissions
Vault
Votifier
VotingPlugin
Wild
WorldEdit
WorldGuard

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
