### ISSUE TITLE
Abandoned and deleted claims in creative world not restoring nature.

### ISSUE THREAD

**Issue by RWoof** [GriefPrevention/GriefPrevention#896]
### What happened:
Players (myself included) have created and either abandoned or deleted claims in my creative world "Creative", I was under the impression that those worlds would remove builds in abandoned claims, but they remain forever. There is also no warning about abandoning a claim restoring nature as mentioned in the wiki. Do I need Worldguard or something for this feature to work? Maybe it was a function of the original GP but not this current version?

Relevant text from the wiki:
"When blocks are unclaimed, they are reverted back to a natural state (the build disappears)."

"Because a griefer might want to make a temporarily claim just to build something awful and then unclaim it, any unclaimed blocks will be automatically cleaned-up. Players get a warning about this when they unclaim blocks, and have a couple of minutes to undo their changes in response."

### What was expected:
Claims that were abandoned in creative restoring nature when abandoned, players getting a warning about this as well.

### Steps to reproduce:
1. Go to a creative world
2. Create a claim
3. Place some blocks
4. Delete or abandon the claim - the claim will delete but the blocks remain.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running Paper version git-Paper-88 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.14.0

### Stack trace/error or server log
No error is generated.

### GriefPrevention config.yml

```yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    hello new world im dino girl: -1
    hello new world im dino girl_nether: -1
    hello new world im dino girl_the_end: -1
    Creative: -1
    Creative2_nether: -1
    Creative2_the_end: -1
    Creative2: -1
  Claims:
    Mode:
      hello new world im dino girl_the_end: Survival
      hello new world im dino girl_nether: Survival
      Creative2: Survival
      hello new world im dino girl: Survival
      Creative2_nether: Survival
      Creative2_the_end: Survival
      Creative: Creative
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 480
    Claim Blocks Accrued Per Hour:
      Default: 240
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 14
      UnusedClaimDays: 180
      AllClaims:
        DaysInactive: 180
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      hello new world im dino girl: true
      hello new world im dino girl_nether: true
      hello new world im dino girl_the_end: true
      Creative: true
      Creative2_nether: true
      Creative2_the_end: true
      Creative2: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 5.0
    ClaimBlocksSellValue: 0.25
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):
Plugins (30): CoreProtect, dynmap*, Dynmap-Essentials*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FarmLimiter, GriefPrevention, GriefPreventionFlags, IllegalStack, Invincible-World-Chests, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Panilla, PlayerShopGUIPlus, ProtocolLib, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, Spartan, Vault, ViaBackwards, ViaVersion, VillagerOptimiser, WorldEdit

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
