### ISSUE TITLE
Public or private container trust not working for any user other than admin

### ISSUE THREAD

**Issue by tkmoney01** [GriefPrevention/GriefPrevention#970]
### What happened:
I created an admin claim around the spawn area and gave all users public container access. I had two users log in, and they experience strange behavior with a double chest that predated the claim. the users are either able to just open the chest with it appearing empty, or they cant interact with the chest at all. I even tried to remove the public access and directly give container access to the users.

### What was expected:
I expected all users to be able to open the chest and take items from it as sort of a kick start for them. At the same time, I expect the environment in the claim to not be modifiable by anyone but admins because it only has the containertrust property assigned.

### Steps to reproduce:
1. place a chest
2.create an admin claim around the chest
3. use "/containertrust public" within the admin claim
4. have a non admin user try to use the chest and verify whether or not they can open it. if they can verify there are no items displaying in it,

### Server and GriefPrevention version:
This server is running CraftBukkit version git-spigot-4d9262c-dc7c3c6 (MC: 1.16.1) (Implementing API version1.16.1-R0.1-SNAPSHOT)
Checking version, please wait....
You are 53 version(s) behind

GriefPrevention version 16.14.0

### Stack trace/error or server log

```
13.08 02:15:31 [PebbleHost] Received start command
13.08 02:15:31 [PebbleHost] Starting server!
13.08 02:15:33 [PebbleHost Loader] -----------------------------------
13.08 02:15:33 [PebbleHost Loader] PebbleHost Server Loader Starting...
13.08 02:15:33 [PebbleHost Loader] The following settings have been detected: RAM: -Xmx5120M, JAR: spigot-1.16.1.jar, SERVERID: 132792, SIZE: 545M
13.08 02:15:33 [PebbleHost Loader] Testing server configuration...
13.08 02:15:33 [PebbleHost Loader] Server loader version: v3.0.3 (using configuration version v1.3.5)
13.08 02:15:33 [PebbleHost Loader] Jar passed checksum check
13.08 02:15:34 [PebbleHost Loader] Server passed size check
13.08 02:15:34 [PebbleHost Loader] Server passed file check
13.08 02:15:34 [PebbleHost Loader] Configuring your servers settings...
13.08 02:15:34 [PebbleHost Loader] Server passed all checks, Booting...
13.08 02:15:34 [PebbleHost Loader] -----------------------------------
13.08 02:15:34 [Server] INFO *** Error, this build is outdated ***
13.08 02:15:34 [Server] INFO *** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
13.08 02:15:34 [Server] INFO *** Server will start in 20 seconds ***
13.08 02:15:54 [Server] INFO Loading libraries, please wait...
13.08 02:15:59 [Server] main/INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
13.08 02:16:00 [Server] main/INFO Reloading ResourceManager: Default, bukkit
13.08 02:16:01 [Server] Worker-Main-11/INFO Loaded 7 recipes
13.08 02:16:02 [Server] main/INFO Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
13.08 02:16:02 [Server] main/INFO Reloading ResourceManager: Default, bukkit
13.08 02:16:02 [Server] Worker-Main-11/INFO Loaded 7 recipes
13.08 02:16:03 [Server] Server thread/INFO Starting minecraft server version 1.16.1
13.08 02:16:03 [Server] Server thread/INFO Loading properties
13.08 02:16:03 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-4d9262c-dc7c3c6 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
13.08 02:16:03 [Server] Server thread/INFO Server Ping Player Sample Count: 12
13.08 02:16:03 [Server] Server thread/INFO Using 4 threads for Netty based IO
13.08 02:16:03 [Server] Server thread/INFO Debug logging is disabled
13.08 02:16:03 [Server] Server thread/INFO Default game type: SURVIVAL
13.08 02:16:03 [Server] Server thread/INFO Generating keypair
13.08 02:16:04 [Server] Server thread/INFO Starting Minecraft server on ***REDACTED***
13.08 02:16:04 [Server] Server thread/INFO Using epoll channel type
13.08 02:16:05 [Server] Server thread/INFO [GriefPrevention] Loading GriefPrevention v16.14.0
13.08 02:16:05 [Server] Server thread/INFO Preparing level "***REDACTED***"
13.08 02:16:06 [Server] Server thread/INFO -------- World Settings For [Eden] --------
13.08 02:16:06 [Server] Server thread/INFO Mob Spawn Range: 6
13.08 02:16:06 [Server] Server thread/INFO Experience Merge Radius: 3.0
13.08 02:16:06 [Server] Server thread/INFO Cactus Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Cane Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Melon Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Mushroom Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Pumpkin Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Sapling Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Beetroot Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Carrot Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Potato Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Wheat Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO NetherWart Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Vine Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Cocoa Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Bamboo Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO SweetBerry Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Kelp Growth Modifier: 100%
13.08 02:16:06 [Server] Server thread/INFO Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
13.08 02:16:06 [Server] Server thread/INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
13.08 02:16:06 [Server] Server thread/INFO Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
13.08 02:16:06 [Server] Server thread/INFO Max TNT Explosions: 100
13.08 02:16:06 [Server] Server thread/INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
13.08 02:16:06 [Server] Server thread/INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
13.08 02:16:06 [Server] Server thread/INFO Allow Zombie Pigmen to spawn from portal blocks: true
13.08 02:16:06 [Server] Server thread/INFO Item Despawn Rate: 6000
13.08 02:16:06 [Server] Server thread/INFO Item Merge Radius: 2.5
13.08 02:16:06 [Server] Server thread/INFO View Distance: 10
13.08 02:16:06 [Server] Server thread/INFO Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
13.08 02:16:06 [Server] Server thread/INFO Zombie Aggressive Towards Villager: true
13.08 02:16:06 [Server] Server thread/INFO Nerfing mobs spawned from spawners: false
13.08 02:16:06 [Server] Server thread/INFO Preparing start region for dimension minecraft:overworld
13.08 02:16:08 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:08 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:08 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:08 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:08 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:10 [Server] Server thread/INFO Preparing spawn area: 8%
13.08 02:16:10 [Server] Server thread/INFO Preparing spawn area: 8%
13.08 02:16:10 [Server] Server thread/INFO Preparing spawn area: 8%
13.08 02:16:10 [Server] Server thread/INFO Preparing spawn area: 8%
13.08 02:16:11 [Server] Server thread/INFO Time elapsed: 4765 ms
13.08 02:16:11 [Server] Server thread/INFO Preparing start region for dimension minecraft:the_nether
13.08 02:16:12 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:12 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:12 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:12 [Server] Worker-Main-12/INFO Preparing spawn area: 83%
13.08 02:16:13 [Server] Worker-Main-8/INFO Preparing spawn area: 83%
13.08 02:16:13 [Server] Worker-Main-13/INFO Preparing spawn area: 83%
13.08 02:16:14 [Server] Worker-Main-12/INFO Preparing spawn area: 83%
13.08 02:16:15 [Server] Worker-Main-10/INFO Preparing spawn area: 83%
13.08 02:16:16 [Server] Worker-Main-9/INFO Preparing spawn area: 87%
13.08 02:16:16 [Server] Worker-Main-10/INFO Preparing spawn area: 88%
13.08 02:16:17 [Server] Worker-Main-10/INFO Preparing spawn area: 98%
13.08 02:16:17 [Server] Server thread/INFO Time elapsed: 6130 ms
13.08 02:16:17 [Server] Server thread/INFO Preparing start region for dimension minecraft:the_end
13.08 02:16:17 [Server] Server thread/INFO Preparing spawn area: 0%
13.08 02:16:17 [Server] Worker-Main-14/INFO Preparing spawn area: 17%
13.08 02:16:18 [Server] Worker-Main-12/INFO Preparing spawn area: 83%
13.08 02:16:18 [Server] Server thread/INFO Time elapsed: 1270 ms
13.08 02:16:18 [Server] Server thread/INFO [GriefPrevention] Enabling GriefPrevention v16.14.0
13.08 02:16:18 [Server] Server thread/INFO [GriefPrevention] Finished loading configuration.
13.08 02:16:18 [Server] Server thread/INFO [GriefPrevention] 3 total claims loaded.
13.08 02:16:19 [Server] Server thread/INFO [GriefPrevention] Customizable messages loaded.
13.08 02:16:19 [Server] Server thread/INFO [GriefPrevention] Finished loading data (File Mode).
13.08 02:16:19 [Server] Server thread/INFO [GriefPrevention] Boot finished.
13.08 02:16:19 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it
13.08 02:16:19 [Server] Startup Done (13.565s)! For help, type "help"

```

```yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Eden: -1
    Eden_nether: -1
    Eden_the_end: -1
  Claims:
    Mode:
      Eden: Survival
      Eden_nether: Disabled
      Eden_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: false
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 20000
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 1
    MinimumArea: 1
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: true
    FireDamagesInClaims: true
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Eden: true
      Eden_nether: true
      Eden_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


```

### Plugin list (if applicable):

Harbor

### Debugging steps attempted
 - [x] this server was created 8/10/2020 hosted by pebblehost
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
  - [x] upgraded to latest spigot version, and uploaded the custom jar to my server. Issue persisted after restart of server
  - [x] deleted the admin claim and had a normal user try to access the chest. they could still not do it. the stick verified the blocks were not claimed
  - [x] verified the user could edit original terrain that was in the admin claim, but any modifications I had made to the spawn prior to making the original admin claim (including new chests placed on those blocks) remain inaccessible to any user but me. 
  - [x] doublchecked admin and my personal claim list and verified here were non in the proximity
  - [x] created a new claim and a new admin claim each with a chest and in the space where the original admin claim was. Confirmed those behaves as expected after i gave public container access. it is like the unatural blocks in the original admin claim are corrupted or something
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
