### ISSUE TITLE
Error returns when entering a pvp free zone

### ISSUE THREAD

**Issue by Xiri99** [GriefPrevention/GriefPrevention#987]
### What happened:
_What you saw_
Whenever you enter a pvp free zone on TownyAdvanced the following error returns:
"You can't fight someone while you're protected from PvP."
This only happens for one of my players.
https://i.imgur.com/Pq3sarF.png

### What was expected:
_What you expected to see_
No error message when entering the zone

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Entering a Towny pvp safe zone

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: git-Tuinity-"ae2d7fc" (MC: 1.15.2)
Paste of `/version GriefPrevention`: 16.12.0-d4d7ac4

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Towny: -1
    Towny_nether: -1
    Towny_the_end: -1
    Resource: -1
    Event: -1
    StoryMode: -1
  Claims:
    Mode:
      Towny_nether: Disabled
      Towny_the_end: Disabled
      Event: Survival
      Towny: Survival
      StoryMode: Survival
      Resource: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Towny: true
      Towny_nether: true
      Towny_the_end: true
      Resource: true
      Event: true
      StoryMode: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 12.5
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Plugin list (if applicable):
ActionHealth*, AdvancedEnchantments, AdvancedPortals, AdvanceParticle, AntiDonkeyDupe, AreaShop, ArmorPlus, AutoBroadcast, BanItem, BannerBoard*, BeastWithdraw, BigDoors, BimmCore, BKCommonLib, BuildersWand, ChatColorGUI*, ChatFeelings, Chunkmaster, Citizens, CleanMotD*, CMI, CMIEInjector*, CMIPaperLib, CommandItems, CommandNPC*, CommandSigns, ConsoleSpamFix, CoreProtect, CraftingStore, CrazyCrates, CustomCommands, DeathMessagesPrime, DefensiveTurrets, DeluxeMenus, DiamondBrokeMessage*, DiceFurniture, DiscordSRV, Elevator, EliteMobs, Fireworks*, FurnitureLib, GCore, GriefPrevention, GSlotMachine, HeadDatabase*, HeartUWU*, HolographicDisplays, HolographicExtension, HubParkour, ImmortalTags, InteractionVisualizer, InteractiveChat, InventoryRollback, ItemEdit, ItemSoulBind, JetsMinions, Jobs, JumpPads, KiteBoard, LeaderHeadsRevamped, LibsDisguises, LightAPI, LightCleaner, LimitPillagers, LiteBans, LootChest, LuckPerms, MarriageMaster, mcMMO, MineableSpawners, MoarBows, MobArena, MovingDevApi, Multiverse-Core, MyPet, NBTAPI, NerfPhantoms, NoPlugins, NoteBlockAPI, PetBlocks*, PlaceholderAPI, PlayerParticles, PlayerVaults, PlugMan, ProtocolLib, PyroFishingPro, PyroMining, Quests, QuickShop, Rankup, RewardPRO, SayallToEveryone*, Sentinel, Spectator*, SpleefX, StaffChat*, SuperbVote, SuperTrails*, TAB, TCPShield*, TheBridge*, Towny, TownyChat, TownyNameUpdater, TutorialCreator, VarLight, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGenerator, VoteParty, Votifier, Vouchers, VoxelSniper*, Weathertimevote, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, XironiteJoin*, XPBoost

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
